### ISSUE TITLE
[Chains] make needs an ip flag

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1007]
@zramsay commented on [Thu Sep 29 2016](https://github.com/eris-ltd/eris-cm/issues/50)

**Problem:** manually setting the IP in the `config.toml` is a PITA and requires extra bash to automate

**Solution:** flag to set the default IP of a "root" validator peer, to whom everyone dials into.

**Comment by compleatang** [comment]
Partially implemented by https://github.com/eris-ltd/eris-cm/pull/52 (which will need to move post repository merging)

**Comment by zramsay** [comment]
closes by #1098
