### ISSUE TITLE
[Chains] Warn users when making chains that have no validators

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1012]
@j-h-scheufen commented on [Sat Mar 12 2016](https://github.com/eris-ltd/eris-cm/issues/9)

`eris chains make -h` lists same examples for account-type combinations that are not usable without further modifications, because they do not result in a usable chain configuration due to 0 validators.

```
$ eris chains make myChain --account-types=Root:1,Developer:0,Validator:0,Participant:1 -- will use the flag to make your chain named myChain (non-interactive)
$ eris chains make myChain --account-types=Root:1,Developer:0,Validator:0,Participant:1 --chain-type=simplechain -- account types trump chain types, this command will use the flags to make the chain (non-interactive)
```

The resulting genesis.json has an empty "validators" array and instantiating a chain via `eris chains new ...` using this file results in a chain that is not making any blocks.
A lot of users (me included) regularly fall into the trap that the chain seemingly was created successfully, but subsequent interactions fail and only the logs reveal that the chain is 'dead'.
### Solution Proposal
- [x] Change the help output and always have 1 root and 1 validator in the samples (in case users copy it from here)
- [ ] When validators are set to 0, output a warning that the resulting chain configuration will need additional manual work to be valid (and that for non-test scenarios at least 4 validators are needed).

---

@zramsay commented on [Thu Sep 29 2016](https://github.com/eris-ltd/eris-cm/issues/9#issuecomment-250492591)

this has been cleaned up on CLI's end with the recent refactor: 1) https://github.com/eris-ltd/eris-cli/pull/932/files#diff-b0a7e837e8946dd03dcd220c54cd6692L90 and 2) https://github.com/eris-ltd/eris-cli/pull/932/files#diff-b0a7e837e8946dd03dcd220c54cd6692R397

**Comment by zramsay** [comment]
closed by #1095
