### ISSUE TITLE
[Pkgs] Implement dynamic type tuple returns

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1014]
@VoR0220 commented on [Fri Apr 15 2016](https://github.com/eris-ltd/eris-pm/issues/112)

need returns for struct, bytes (the plain one), and string. 

---

@compleatang commented on [Sat Aug 13 2016](https://github.com/eris-ltd/eris-pm/issues/112#issuecomment-239590521)

where are we on this?

**Comment by VoR0220** [comment]
to an extent this is implemented...its a matter of solidity catching up. Closing for now.
