### ISSUE TITLE
[Pkgs] Bundle Management Lock File Design

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1015]
@VoR0220 commented on [Wed Aug 31 2016](https://github.com/eris-ltd/eris-pm/issues/205)

We have talked about the manifest file design with the bundle.json but I wanted to talk about how the lock file will be generated and created. When designing a lock file we want it to keep track of information on multiple different chains, all the chains that the user has interacted with while using this bundle, we also want it to keep track of ABIs for different objects, and bytecode for the version of compilers that they are using. We also want it to be known if the user wants it to be findable and registered if the user wants it public, and private if the user wants it private. Overall, we want reusability, whether on private or a public chain. 

To lay it out simply, here's how it should be set up:

```
{
       ProjectHash: Hash,
       ProjectTimestamp: TimeStamp,
       Chain: 
       PublicComponents: 
       [

              ChainId: [
                          ModuleHash: {
                               DeploymentAddrs: [ModuleAddress1 : Block1, ModuleAddress2:BlockN] 
                               Libraries: LibraryString,
                               Binary: BinaryOutput,
                               ABI: ABIjson,
                               Solc: {Solc Object detailing settings to get this compile)
                               Locations: [
                                    IPFS: IPFSHash,
                                    Swarm: EthereumAddress,
                                    Github: GithubAddress, 
                             ]
                    },
           ],
     ],
     PrivateComponents:
     [
             ChainId: [
                          ModuleName (maybe hash because name conflicts) : {
                               DeploymentAddrs: [ModuleAddress1 : Block1, ModuleAddress2:BlockN]  
                               Libraries: LibraryString,
                               Binary: BinaryOutput,
                               ABI: ABIjson,
                               Solc: {Solc Object detailing settings to get this compile)
                    },
           ],
    ]
}
```

The problem I'm thinking is how do we specify what is a private component and what is a public component in a user friendly way on EPM. (Chain IDs are inherent, but they too could use a friendlier command line feel to them. Perhaps a config file setting in bundle.json?)

In any case, another command for EPM that may come in handy as a consequence of this is a simple verify command that will be useful per new Solidity metadata in the binaries. 

---

@AFDudley commented on [Wed Aug 31 2016](https://github.com/eris-ltd/eris-pm/issues/205#issuecomment-243776123)

i'm really confused why we are talking about a permissionless chain use-case at all.

---

@VoR0220 commented on [Wed Aug 31 2016](https://github.com/eris-ltd/eris-pm/issues/205#issuecomment-243794822)

Because we're offering it as a chain to deploy on? 

---

@j-h-scheufen commented on [Wed Aug 31 2016](https://github.com/eris-ltd/eris-pm/issues/205#issuecomment-243797871)

We can talk about the lock file and related requirements in our call, but I only see parts of this being relevant to achieve our primary goal: `Support Eris customers as well as our own developers and client developers to be able to consume and reference bundles in their development`. We should split up the requirements for this issue into features for a later time (e.g. multi chain deployment) and "day 1" priorities (e.g. versioning, binary vs source).

---

@VoR0220 commented on [Wed Sep 07 2016](https://github.com/eris-ltd/eris-pm/issues/205#issuecomment-245368164)

updated this with thoughts based on https://github.com/eris-ltd/eris-db/issues/265

**Comment by VoR0220** [comment]
Closing as design has been generally sorted and decided to use ethpm standard.
