### ISSUE TITLE
[Pkgs] remove wait: true from required fields in epm.yaml

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1029]
@compleatang commented on [Sun Aug 21 2016](https://github.com/eris-ltd/eris-pm/issues/199)

**Problem** -- it is ultra rare that on calls and most transactions that wait would be set to false. While there is a use case for that, it is far from the standard. At this time having `wait: true` as needed at all in the epm.yaml's is overkill and a line of code that users shouldn't need to type. 

**Solution** -- Set proper default of `wait: true` and remove all the waits from the fixtures. 

---

@VoR0220 commented on [Sun Aug 21 2016](https://github.com/eris-ltd/eris-pm/issues/199#issuecomment-241263989)

Totally agree

**Comment by VoR0220** [comment]
I would also like to add to this that we should change the variable `wait` to be named `async` and set it default `false`. Because that is what it really is and seems more intuitive.

**Comment by benjaminbollen** [comment]
As discussed in the Monday meeting, it suffices to default to `wait: true` and remove it from the fixtures
