### ISSUE TITLE
[Pkgs] Consumption of Library Should not Require Instance

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1035]
@VoR0220 commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-pm/issues/202)

Problem: While investigating #198 I discovered that if the instance of the consuming contract is not declared during deployment, an ABI error occurs and subsequent calls to the contract are not allowed. This should be fixed.

Solution: Investigate the problem more and report back here when more is found out.

**Comment by VoR0220** [comment]
closing in favor of #1071
