### ISSUE TITLE
[Chains] Simplify chains make + start sequence for simplechain

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#1036]
The changes in 0.12.0-rc3 have already improved the user experience, but can be simplified further to make the creation of "simplechain" types more intuitive.

Currently:
```
eris chains make myChain
eris chains start myChain --init-dir ~/.eris/chains/myChain
```
or (simpler):
```
eris chains make myChain
eris chains start myChain --init-dir myChain
```
The presence of the directory under `~/.eris/chains/` with the same name as the chain is currently a requirement (see #964). In that light, the user having to specify the "init-dir" in this case seems redundant and unnecessary typing.

The following sequence is more intuitive and should be supported:
```
eris chains make myChain
eris chains start myChain
```
The command can assume that the required `init-dir` can be found by under the same name as the chain in `~/.eris/chains`

**Comment by zramsay** [comment]
This feature request conflicts somewhat with #964, does it not? While I agree with simplifying even further, it adds more assumption (& thus complexity) the tool makes. It also obfuscates the use of --init-dir, which is ~essential to the chain init process on complex chains. 

Conversely, I'd suggest that `chains make [simplechain]` (or any chains make with a single account type) should make a directory structure identical to a chain with >1 account type (i.e., not having all the files in the chains main dir)

**Comment by benjaminbollen** [comment]
perhaps `--init-dir <dir>` can be interchanged with `eris chains start myChain --validator 1` which would be equivalent to `eris chains start myChain --init-dir ~/.eris/chains/myChain/myChain_validator_001`; similarly for `eris chains start myChain --participant x` which should then start a non-validating, but verifying entity

**Comment by j-h-scheufen** [comment]
@benjaminbollen All valid thoughts above, but we should be careful introducing too many convenience shortcuts as this increases the test and maintenance footprint.
The main suggestion this ticket presents is that the most simple sequence of `make` and `start` for a simplechain unnecessarily makes me type the `--init-dir` location even though (from the user's point of view) it's obvious what the intention is, i.e. start a chain with the configuration I just made under the same name.

**Comment by zramsay** [comment]
how about a short-flag for `--init-dir`? the simplification proposed will add too much complexity/assumption in the code.

**Comment by j-h-scheufen** [comment]
@zramsay The same assumptions already exist when making the chain, because the result is autimatically output into `~/.eris/chains`. Using the same assumptions when starting a chain I find just consequential and totally makes sense from a UX pov. It just means that you can have an "easy life", if you accept that the eris tools handle a lot under the hood through the special home directory, once you become more familiar with the tools you can use flags to customize behavior.

**Comment by zramsay** [comment]
closing as rejected (per extensive slack discussion); this would only work on simplechains.

**Comment by j-h-scheufen** [comment]
I did not find that our slack discussion lead to the consensus to reject this. Request to re-open.
