### ISSUE TITLE
[pkgs] Hide 'INFO' output in console

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#1041]
Eris version: 0.12.0-rc3

The below output from the console shows large amounts of technical information that distracts from the actual tests and test results. Especially, because it contains the contracts binaries and can get quite long!

```
Deploying Contract                       name=BaseErrors
INFO[10-14|15:05:58] Starting WSClient                        module=rpcclient impl="chain:46657, /websocket"
INFO[10-14|15:05:58] URI request to http://chain:46657 (broadcast_tx): map[tx:[[2,{"input":{"address":"CDB00407B6EDBF6735A88AA5B34FA24A8984D421","amount":9999,"sequence":1,"signature":[1,"A27E8E4625984105D5338641D11CB8613EB9357E49DB659527541070F2E7F28CE9BD27C0DE5066033B598B03A1B61AF980B83830F08630877544E8B2BD51A704"],"pub_key":[1,"340999236B9A635C06E1B72FC1653D6BEC0F697F99932E045A5593059D107DB5"]},"address":"","gas_limit":1111111111,"fee":1234,"data":"6060604052600A8060106000396000F360606040526008565B00"}]]] module=rpcclient
```
## Requirements

Remove the lines starting with `INFO` from the regular output and make it available only in debug `-d` and/or verbose `-v` mode.

**Comment by VoR0220** [comment]
This is the case in the latest branch. Closing.

**Comment by benjaminbollen** [comment]
Issue regressed

**Comment by VoR0220** [comment]
Is this issue still prevalent?

**Comment by zramsay** [comment]
since it was re-opened as regressed, then almost certainly so

**Comment by VoR0220** [comment]
See the merge right after it.

**Comment by VoR0220** [comment]
confirm this is done.
