### ISSUE TITLE
[pkgs] The EPM log output should print return values in human-readable form

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#1046]
Eris Version 0.12.0-rc3

For many data types the log output since 0.12.0-rc3 has been switched to print the bytes of return values rather than the correctly parsed content. This makes it very hard to debug and follow the test scripts.
Note: String values seem to be printed as expected when returned from `call` jobs, but not when returned from `query-contract` jobs. (see first line of below example vs. job "agreementName").

Exampel output: 
```
Return Value                                  success
Executing Job                                 assertVersionSigning
Assertion Succeeded                           success == success
Executing Job                                 finalAgreement
Return Value                                  [0 0 0 0 0 0 0 0 0 0 0 0 146 165 12 142 15 222 127 248 55 15 42 194 176 140 189 147 186 190 179 201]
Executing Job                                 finalVersion
Return Value                                  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 28 107 104 56 55 116 106 71 70 121 116 102 54 53 103 104 102 121 102 55 54 116 55 121 117 71 89 71 89 0 0 0 0]
Executing Job                                 testConfirmedVersion
Return Value                                  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
Executing Job                                 assertConfirmedVersion
Assertion Succeeded                           1 == 1
Executing Job                                 signatory1
Return Value                                  [0 0 0 0 0 0 0 0 0 0 0 0 8 0 43 144 8 95 164 32 103 161 42 117 199 246 65 53 88 107 184 158]
Executing Job                                 agreementName
Return Value                                  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 11 65 103 114 101 101 109 101 110 116 32 49 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Executing Job                                 assertName
Assertion Succeeded                           Agreement 1 == Agreement 1
```
As can be seen, this information is initially worthless to a developer or user of EPM, because it has to be processed to make sense. As far as I remember, this was done better in past versions and can be considered a regression.
Note: When using the return values in assertions they are printed as they should. See the last two jobs in the example (agreementName and assertName).

## Requirements
- The output should be converted from it bytes representation and formatted to be human-readable before printing it to the log.
- The original bytes representation should still be available to be printed in `-d` debug mode

**Comment by VoR0220** [comment]
This will be fixed when the new ABI is merged in.

**Comment by VoR0220** [comment]
@j-h-scheufen can you check if this bug is persisting in the latest push?

**Comment by VoR0220** [comment]
Aha! I have found the reason why. Pushing up fix soon.
