### ISSUE TITLE
[Chains] On Chains Start Imported Keys are Not Set to Proper User

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1052]
**Problem** -- the keys that are imported from the new start `--init-dir` are not properly changing their owner to the eris user. for rc3

**Comment by pietv** [comment]
@compleatang could you give a little more detail or a small script to reproduce this problem? Some files imported on `chains make` into a data container not owned by `eris`, is that it? Also what "for rc3" stand for, tested on "#master"?

**Comment by compleatang** [comment]
sorry. was in the midst of a call with Jan so mostly logging so I didn't forget. I'll provide a reproducible case shortly.

**Comment by compleatang** [comment]
To confirm bug (and to test fix) perform the following sequence. 

```
eris chains make simpletest 
eris services rm -fx keys
eris chains start simpletest --init-dir simpletest 
eris services exec keys -- ls - la /home/eris/.eris/keys/data
```

Before the fix the keys will be owned by root and therefore unavailable to eris-keys server (which is running as the eris user). After the fix from the associated PR the keys will properly belong to the eris user.

**Comment by pietv** [comment]
Thanks! I was able to reproduce the issue with this snippet. Will fix.
