### ISSUE TITLE
[Compilers] Build and push a solidity v 4 docker image

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1054]
**Problem** -- there were large breaking changes between solidity v 0.3.X and solidity v. 0.4.X. While the 0.12.0 compilers are pinned to 0.3.6, many users will want to utilize the new solidity features available in 0.4.X. 

**Solution** -- build and push a tested version of the compilers image that utilizes 0.4.X with the docker tag of `quay.io/eris/compilers:0.12.0-solidity4` This image can be pulled, the compilers service definition file updated, and users can utilize using `--local-compilers`.

**Comment by VoR0220** [comment]
still trying to make it fully compatible with the compilers service and that means putting warnings into JSON format.

**Comment by VoR0220** [comment]
Linked to #997

**Comment by zramsay** [comment]
- closed here https://github.com/eris-ltd/eris-compilers/pull/111/files#diff-3254677a7917c6c01f55212f86c57fbfR5
- `quay.io/eris/compilers:0.16.0` is now on `solc --version` 0.4.4
