### ISSUE TITLE
`import` requires double quotes (and failes with single quotes)

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#1055]
I am running eris 0.11.4 installed as binary from github release on a DO machine running Ubuntu 16.04.1x64 and attempt to compile a solidity file that has an `import 'test.sol';` statement as first line. Compiling it via epm gives me an error
```
Error: Source not found: File not found.
import 'test.sol';
```
But this does work out when changing the single quotes `'test.sol'` to double quotes `"test.sol"`.

**Comment by VoR0220** [comment]
Hey @SCBuergel, just wanted to let you know that this has been fixed in 0.12.0.
