### ISSUE TITLE
optional `pin to gateway` flag on `files put` 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#106]
pin to a remote IPFS on cloud vs. pinning to local IPFS instance.

**Comment by zramsay** [comment]
Do you mean `add` to gateway?... `files put` == `ipfs add` != `ipfs pin` / `files cache`. Or, do you want `files put` to have the option of pinning as well? (if so, that already happens by ipfs default). Or, do you want the option to pin/add/get via either the gateway or API?

 I left `files put` & `files get` going through the gateway...the API can behave unexpectedly.

**Comment by compleatang** [comment]
now that `files cache` is done we should be able to do this easily via a flag. 

let's test using the eris `ipfs.erisboostrap.sexy` gateway that we run on AWS (soon moving to packet).

**Comment by zramsay** [comment]
what is this feature achieving? the point of pinning (as I understand it) is to keep files around locally that may otherwise be garbage collected. what's the use case where someone wants to `put` to the ipfs gateway while also `pin` to boostrap.sexy? besides, the gateway doesn't support pinning.

**Comment by compleatang** [comment]
I think the terminology here is confusing. What we should be able to achieve is to dump a file into the ipfs network but to have our eris gateway be able to "keep" that file available as it is in the cloud and not on someone's harddrive.

Use case basically would be I want folks to have access to a service definition file all the time but my laptop isn't always on and so I would want an ipfs instance in the cloud (which i'm calling a gateway for the purposes of this discussion) that can reliably be able to serve that file. IPFS runs a gateway at gateway.ipfs.io we also run one at the url listed above (both being the same thing).

**Comment by zramsay** [comment]
ok now I understand. so with this new feature and more to come, our ipfs code is getting messy. i'm gonna take a stab at a refactor and try out the revised go-ipfs-shell (now with far fewer imported packages). this should address #133 and #137, and allow for #114

**Comment by zramsay** [comment]
closed by a570f4

**Comment by zramsay** [comment]
should this flag be a string instead of bool, so that users can specify their own gateway host?
