### ISSUE TITLE
[pkgs] `balance` of contract not zero (and increasing)

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#1060]
I am on eris0.11.4 on Ubuntu16.04.1x64 on DO but you know that ;)
I have deployed a bunch of random contracts before but never `send` any Ether to any of them. When checking their balance via the following minimal contract, I observe that the `balance` (via `getBalanceA`) seems to increase by ` whenever I write the address of that contract to storage by calling `setA)
```
contract A {
  address mya;
  function A(address a) {
    mya = a;
  }
  function getBalanceA() constant returns (uint) {
    return mya.balance;
  }
  function getA() constant returns (address a) {
    return mya;
  }
  function setA(address a) {
    mya = a;
  }
}
```

**Comment by VoR0220** [comment]
Hmmm...I wonder if this has something to do with the default fee and if that's being put in with the payload.

**Comment by zramsay** [comment]
@SCBuergel did this go away in 0.12.0 ?

**Comment by VoR0220** [comment]
closing this as not responded. @SCBuergel let us know if this is still persisting.
