### ISSUE TITLE
[pkgs] deployment error: panic: interface conversion: interface is int, not string

### ISSUE THREAD

**Issue by marc4gov** [eris-ltd/eris-cli#1065]
When deploying contracts, everything seems deployed, but the job is finishing with a go error:
This happens randomly around included contracts of the deployed main contract. In the snippets underneath Multisig has an interface contract "owned" and a child member of contract "DoublyLinkedList"

`name=Multisig
Response                                  abi=[{"inputs":[],"type":"constructor"}]
                                          bin=60606040525b33600060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055505b600a80603d6000396000f360606040526008565b00
                                         name=owned
panic: interface conversion: interface is int, not string`

I get these errors also in other included contracts:

name=DoublyLinkedList
panic: interface conversion: interface is int, not string

goroutine 1 [running]:
panic(0x5619ba0c5840, 0xc420059240)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/eris-ltd/eris-pm/perform.deployContract(0xc4200dc240, 0xc42044f680, 0xc4200153e0, 0x8, 0xc42031a000, 0x4ab2, 0xc4204bd000, 0xf96, 0xc420490d20, 0x16, ...)

This is the epm.yaml:

jobs:

- name: deployMultisig
  job:
    deploy:
      contract: MultiSig.sol
      function: MultiSig
      data: [ 2, 4, 1, 604800]
      wait: true

- [ ] `docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   23cf638
 Built:        Sat Sep 10 02:45:38 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64`

- [ ] `eris version`
`Eris CLI Version: 0.12.0 (002c63e)`

- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
`docker-machine version 0.8.2, build e18a919`
- [ ] operating system details (osx/windows/linux)
`macOS`
- [ ] what you expected to happen
- [ ] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by VoR0220** [comment]
Just want to update you on something you should fix but I've determined is not the problem @marc4gov you don't need to add the function in the deploy, by default the deploy job only puts data towards a constructor if there even is one.

**Comment by VoR0220** [comment]
Found the problem with this and it is not abi related...rather its preprocessing the inputs in a constructor related. Fixing currently, should have it fixed up in a couple of hours.

**Comment by marc4gov** [comment]
🐿

2016-11-07 21:21 GMT+01:00 RJ <notifications@github.com>:

**Comment by VoR0220** [comment]
Should be working now @marc4gov

**Comment by marc4gov** [comment]
Ok, I'll try

Op dinsdag 8 november 2016 heeft RJ <notifications@github.com> het volgende
geschreven:

**Comment by marc4gov** [comment]
Seems ok now, however after successful execution I don't have an abi directory nor a jobs.output file....

**Comment by VoR0220** [comment]
strange...investigating.

**Comment by marc4gov** [comment]
Sorry RJ, my mistake, they are there (was looking at git files...)

**Comment by VoR0220** [comment]
Lol. I hear that.

**Comment by marc4gov** [comment]
Somewhat fresher now.... unfortunately, this problem occurs indeed. Now looking at Finder, no abi dir nor a jobs.output file. stdout by the way produces all the info like this:

Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 deployUser
Response                                  abi=[{"constant":true,"inputs":[],"name":"tail","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":false,"inputs":[{"name":"key","type":"address"}],"name":"getData","outputs":[{"name":"","type":"bytes32"}],"type":"function"},{"constant":false,"inputs":[{"name":"key","type":"address"}],"name":"removeElement","outputs":[{"name":"result","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"key","type":"address"},{"name":"data","type":"bytes32"}],"name":"addElement","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[{"name":"key","type":"address"}],"name":"getNext","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"head","outputs":[{"name":"","type":"address"}],"type":"function"},{"constant":true,"inputs":[],"name":"size","outputs":[{"name":"","type":"uint256"}],"type":"function"}]
                                          bin=6060604052610982806100126000396000f36060604052361561007f576000357c01000000000000000000000000000000000000000000000000000000009004806313d8c8401461008157806338266b22146100ba5780635f2fb08e146100e6578063751a022514610112578063765e0159146101475780638f7dcfa3146101895780

**Comment by marc4gov** [comment]
I did a fresh install of eris 0.12 via brew install eris, but the issue still persists. 
So IMHO compilation went fine, writing the ABI and Bytecode to the console went OK, but no writing to ./abi dir and no writing to a jobs.output. 
Something wrong with permissions then?

**Comment by VoR0220** [comment]
Interesting. I'm currently trying to reproduce this...and I can't seem to do so. Are you trying to write to an old abi directory or somewhere else in the filepath? Same for outputs.json?

**Comment by marc4gov** [comment]
Exactly! It seems that if I use my 'old' project directories where I used to compile my contracts with eris 0.11.4, things go wrong (even after a 0.12 eris init). 
When I use a brand new project directory, everything is OK.

**Comment by VoR0220** [comment]
So it's a problem of legacy settings...do you want to keep this open or close the issue?

**Comment by marc4gov** [comment]
I think you can close it, maybe mention in the release notes or something.

Thanks, sorry for the trouble

Op ma 14 nov. 2016 om 22:24 schreef RJ <notifications@github.com>
