### ISSUE TITLE
[Pkgs] Creation of a Ecosystem Application Binary Setup

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#1075]
I know that this title is confusing but bare with me here. I have been thinking about how a package manager like this could work in creating back end ecosystem applications (dapps) and the thought occurred to me that a binary command could be generated based on multiple epm run files each set to a command to run x tasks. These could be housed in a "commands" directory and easily generated to run different commands in an application. Thoughts on this approach?

**Comment by zramsay** [comment]
@VoR0220 could you elaborate with a problem/solution? i'd like to close unless there is more information.

**Comment by VoR0220** [comment]
Problem(s): redundant naming in regards to run files requires that we become more opinionated and separate out our runs from our actual package management. Furthermore jobs are by their nature such that there should be multiple job scripts capable for complex packages. 

Solution: The proposed setup specifies that we become more opinionated for our package and create a directory specifically to handle jobs that are named to different commands and create binaries from said commands for the creation of backend ecosystem applications.

**Comment by VoR0220** [comment]
Closing as been decided by libraries team not to utilize this approach.
