### ISSUE TITLE
[Pkgs] Fix Negative Arrays

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#1080]
* This is pretty much done, but there was a small fix up needed in the ABI for negative arrays in that they were still returning unconverted full unsigned integers.

**Comment by zramsay** [comment]
status? i think https://github.com/eris-ltd/eris-pm/pull/268 went in after i started moving epm into cli, so it'll need to be ported

**Comment by VoR0220** [comment]
Done
