### ISSUE TITLE
[Pkgs] Stagger Imports with Import Field? 

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#1081]
per request of @compleatang (and need further clarification of this), implement imports the same UX we do with a libraries string.

**Comment by zramsay** [comment]
does this refer to the cleaning up / re-organization of package imports in #1083 or something else entirely?

**Comment by compleatang** [comment]
closing. the problem we were having is solved and this feature would add a lot of complexity for little gain.
