### ISSUE TITLE
Getting Started Tutorial for Mac Fails

### ISSUE THREAD

**Issue by andytudhope** [eris-ltd/eris-cli#1085]
The first step in the [getting started](https://monax.io/docs/tutorials/getting-started/) tutorial for Mac fails when I run this command. I expected it to run successfully, but it just failed with the below error.

`brew install eris docker-machine virtualbox`

<img width="472" alt="screen shot 2016-11-17 at 9 23 09 am" src="https://cloud.githubusercontent.com/assets/13001517/20419256/c7d12b02-ad5d-11e6-846b-cdf522a8a824.png">

Virtualbox was not installed on the machine when I ran that so maybe that was the issue (I'm new to Mac and brew, so still learning). Nevertheless after getting virtualbox, it still printed the same error - the only way I could get Eris to init was by installing docker manually.

- [ 1.12.3] `docker version`
- [0.12.0] `eris version`
- [1.7.3] `go version` (if applicable)
- [0.8.2] `docker-machine version` (if applicable / !linux)
- [OS X El Capitan] operating system details (osx/windows/linux)

**Comment by pietv** [comment]
@andytudhope thank you spotting this problem. This is a documentation issue, and the proper sequence command(s) should be 
```
brew cask install virtualbox
brew install docker docker-machine eris
```
The documentation will be updated shortly.

**Comment by andytudhope** [comment]
no problem, thought it would be something simple like that, but not being familiar with brew left me unable to work out the missing step properly. Feel free to close here when the update is live.

**Comment by zramsay** [comment]
fix merged to stating on website. will go live in ~2 days

**Comment by zramsay** [comment]
site is live with fix.
