### ISSUE TITLE
Unable to connect to seed

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-cli#1087]
- [1.12.3 ] `docker version`
- [0.12.0 ] `eris version`
- [0.8.2 ] `docker-machine version` (if applicable / !linux)
- [linux ] operating system details (osx/windows/linux)

I new eris 0.12.0, create permissioned chain with 1 full account, 5 participants, 3 validators. When I try to deploy the chain to the validator nodes (docker machines with amazonec2 driver) it deployes but when I try to connect to the same chain locally, in the log it says unable to connect to the seed. 

In previous version this worked as explained in the example https://monax.io/docs/documentation/cm/latest/examples/chain-deploying/ 

In the latest version I see the config.toml has changed and I get this error. 

*note I mentioned the ip:port in the seed. like this
35.162.241.216:46656,35.161.173.154:46656,35.163.94.135:46656

Is there something I am missing here?? 

log looks like this:
[34mINFO[0m[11-21|14:27:07] Failed dialing address                   [34mmodule[0m=p2p [34maddress[0m=35.163.94.135:46656 [34merror[0m="dial tcp 35.163.94.135:46656: i/o timeout"
[31mEROR[0m[11-21|14:27:07] Error dialing seed                       [31mmodule[0m=p2p [31merror[0m="dial tcp 35.163.94.135:46656: i/o timeout"

After eris init, the default folder is empty. Is that part of the improvement? Or my setup is not correct?

**Comment by zramsay** [comment]
Hi @somak12 if I understand correctly, the way you are deploying your chain is identical between 0.11.4 and 0.12.0 ? 

I would suggest deploying the full account locally (leaving the "seeds" field blank) then have each validator with an identical `config.toml` that points to your full account node.

**Comment by somak12** [comment]
@zramsay  yes I was doing that in the same way. Like in every config.toml I specified the seeds to be the ip:port of all  the validators. 

Docker machine in aws didn't had the ports open fro TCP by default as was the case earlier. I have added the rules manually and its working fine now. :) 

Like you mentioned in the comment "(leaving the "seeds" field blank) then have each validator with an identical config.toml that points to your full account node" does the two approach differ in any way? In either case in the seeds field I have to specify the node's ip right?

**Comment by zramsay** [comment]
Glad to hear that opening the ports fixed your issue.

The difference in approach is quite minor. The way I proposed is somewhat simpler & potentially easier to debug. Having multiple "seeds" is fine so long as it points to other full/validator nodes that are up and running.

>  In either case in the seeds field I have to specify the node's ip right?
Yes

**Comment by zramsay** [comment]
closing as resolved:
>  its working fine now.
