### ISSUE TITLE
[compilers] Cache should go through IPFS

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#1089]
Will explain in the morning but essentially really neat feature to reduce load times for all around by checking global cache. Should have an explicit "off" setting.

**Comment by zramsay** [comment]
what's the problem/solution?

**Comment by VoR0220** [comment]
Problem: We have all these cached files sitting on user sides and little way to gather KPI metrics. 

Solution: go through IPFS.

**Comment by zramsay** [comment]
dealt with in #1102
