### ISSUE TITLE
[chains] eris chains make broken

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-cli#1090]
**reproduction**
`rm -rf ~/.eris`
`eris init`
`eris chains make tester` silently fails to set up the chain

- `eris version 0.12.0`
- `docker version`
```12:49 $ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:53:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:53:11 2016
 OS/Arch:      linux/amd64
```

**Comment by zramsay** [comment]
i have some suspicions as to the source of the error & will attempt reproduction. #899 will help eliminate the edge case for which this occurs.

**Comment by zramsay** [comment]
unable to replicate on either develop or on the #1072 branch. 

Notably, on current develop, `eris init` only creates the ~/.eris/chains/account-types/ & chain-types` directories but does not fill them with the toml files. On the first run of `chains make` the files are copied out from the cm docker image. I suspect there's a docker edge case here.

On #1072, `eris init` writes these files just like the service definition files. Templates are forthcoming (#1003)

**Comment by zramsay** [comment]
closing as suspected edge case from pre-consolidation
