### ISSUE TITLE
eris compilers - certification expired

### ISSUE THREAD

**Issue by andrisurtans** [eris-ltd/eris-cli#1125]
- 1.12.3 `docker version`
- 0.11.4 `eris version`
- ubuntu operating system details (osx/windows/linux)
- what you expected to happen
Compile contracts using  `eris pkgs do --chain <chain_name> --address $addr` command (steps from https://monax.io/docs/tutorials/getting-started/)
- what actually happened
```
$ eris pkgs do --chain simplechain --address $addr 
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 setStorageBase
Executing Job                                 deployStorageK
failed to send HTTP request Post https://compilers.eris.industries:10114/compile: x509: certificate has expired or is not yet valid
Error compiling contracts
Post https://compilers.eris.industries:10114/compile: x509: certificate has expired or is not yet valid

Container interactive-1cd024e7-05fb-4647-8169-e753f088383e exited with status 1
```
I believe, certifcation expired issue is on eris-ltd side, right? if no, please, provide information, how to proceed as it stops working today without reason
- steps to reproduction
the same as in https://monax.io/docs/tutorials/getting-started/

**Comment by zramsay** [comment]
hi @andrisurtans, our apologies for the issue. The quickest fix is editing the `$HOME/.eris/eris.toml` file to look like:
```
CompilersHost = "https://compilers.monax.io"
```
It's also possible to specify the compiler URL with `--compiler` when running `eris pkgs do`. Note that in version 0.12.0, the `--local-compiler` flag is also available and this will become the default.

**Comment by zramsay** [comment]
Closing a resolved. Please re-open if issue is encountered again.
