### ISSUE TITLE
[Perform] Consider removing docker dependency

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#1132]
## Problem

Oh. Let us count the ways.

* we are requiring users to install an extra, probably unrequired external dependency on a semi-stable project resulting in installation friction, runtime instabilities, and a range of hard to debug edge cases.
* docker's path is unclear.

## Analysis 

Docker gets us:

* an abstraction between daemons we need running and the operating system
* a registration and distribution function

Docker costs us:

* to provide support for docker (more or less) and all of it's [quirks](https://thehftguy.wordpress.com/2016/11/01/docker-in-production-an-history-of-failure/).
* logging.

Container technology gets us:

* the ability to direct fleets of containers (essential for industrial IoT)
* a clean(ish) abstraction between runtime and kernel
* (when containers properly built and certified post distribution) a highly verifiable computation distribution mechanism.

Container technology costs us:

* very little...?

### `stay with docker`

```
an acceptable option?
```

This is our current state of play. However, we should fall into the falacy of sunk costs but rather have a clear and open discussion about our dependency on docker. 

What docker, perhaps, gives us is the first truly cross operating system container engine. If we are going to continue to make monax as easy for windows and osx developers as we are for application operators then this matters. However... `vagrant up`?

### `rkt`

```
probably the best middle route?
```

From their README:

> Some of rkt's key features and goals include:

> Security: rkt is developed with a principle of "secure-by-default", and includes a number of important security features like support for SELinux, TPM measurement, and running app containers in hardware-isolated VMs.

> Composability: rkt is designed for first-class integration with init systems (systemd, upstart) and cluster orchestration tools (fleet, Kubernetes, Nomad), and supports swappable execution engines.

> Open standards and compatibility: rkt implements the appc specification, supports the Container Networking Interface specification, can also run Docker images, and OCI images via docker2aci. Native OCI image support is in development.

[Kubernetes](https://github.com/coreos/rkt/blob/master/Documentation/using-rkt-with-kubernetes.md) support appears sane.

`rkt` is amazingly well documented and also has the feature set which we need. CoreOS has a commitment to security which is beyond dockers. Examples:

* rkt allows for both `sudo rkt` and just `rkt` actions... no more of this add the user to the frigging group nonsense if correctly installed.
* rkt requires/allows signing of container images.
* "rkt supports measuring container state and configuration into the Trusted Platform Module (TPM) event log... This provides a cryptographically verifiable audit log of the containers executed on a node, including the configuration of each."

rkt also has sane logging options. https://github.com/coreos/rkt/blob/60aff555ead629c2dc7067d17dff43b44d76a47c/Documentation/commands.md#logging

Downsides:

* rkt has fewer contributors than docker
* docker has traction and momentum in enterprise
* docker allows us to operate it as a daemon. see -> https://github.com/coreos/rkt/tree/master/api/v1alpha

### `libcontainer`

```
another option?
```

### `unikernals`

```
is this even an option?
```

### `purely native` 

```
my least preferred option.
```

functionally, what's docker doing for monax at this point in time? let's set aside the image registry and distribution functionality for now. docker is essentially starting, stoping, and connecting ports for some daemons we need to be running. there is an argument I can see wherein the `perform` package should just be proper mappings of how to do this for all the major operating systems we support. my worry with this option is surface area and edge cases which would increase exponentially.

**Comment by VoR0220** [comment]
Some performance metrics elsewhere in this blog that may be of interest, but I think this one is the most relevant to us: https://shivammaharshi.wordpress.com/2016/08/16/docker-vs-rkt-benchmarking-clustering/

When you look at the security problems, a lot of them are being addressed with Docker...and it does have massive amounts of community support...

**Comment by VoR0220** [comment]
This one is actually better. https://medium.com/@adriaandejonge/moving-from-docker-to-rkt-310dc9aec938#.vnhr2hdvn

**Comment by zramsay** [comment]
I'm open to rkt and having this discussion post consolidation & move to jenkins. It may be that docker ends up getting out of our way enough to not justify the cost of switching.

**Comment by zramsay** [comment]
at last meeting, @pietv provided an overview of his investigation into `rkt` and it did not sound too promising. I'm no longer in favour at all of moving to rkt at this time given the overhead  of switching / less mature ecosystem

**Comment by compleatang** [comment]
OK. All things considered it is probably the right move to stay where we are.
