### ISSUE TITLE
[chains] add more interesting information to `eris chains ls`

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#1137]
An interesting feature would be to add more useful chain related information to `eris chains ls`. Example fields could be:

Pretty much everything from the eris-db status command, that being:

`genesis hash`, `validator_pub_key`, `latest_block_hash`,  `latest_block_height`, `latest_block_time`. `ChainIP` would also be another welcome field. Yet another would be the `chain type` field (tendermint/eth/edb/bigchaindb/etc)

**Comment by zramsay** [comment]
this is handled by #1011. In the future, please review existing tickets before opening duplicate ones.
