### ISSUE TITLE
`eris files put --dir`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#114]
WIP. requires [this](https://github.com/eris-ltd/go-ipfs/commit/444424ccc283a2477726759dc359887e987aba41) update to IPFS. pr at https://github.com/ipfs/go-ipfs/pull/1543

**Comment by compleatang** [comment]
as this is waiting on IPFS gonna move to 0.11

**Comment by compleatang** [comment]
screw it. let's just loop over the dir for now. Paul and other users can use this now....

build a little csv logger thingy for now.

**Comment by compleatang** [comment]
@zramsay will leave closing this for you!
