### ISSUE TITLE
confusing semantics: `known`, `ls`, `ps`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#115]
So for #91 it makes sense to have `eris known` in addition to `eris ls` (i think), maybe also `eris ps`. There's some nuance to the difference in the three commands that is somewhat unclear. It might best be explained on `eris` ...there could be a short summary of common commands across several `eris [cmd]`. Thoughts?

**Comment by compleatang** [comment]
great. good idea. for anyone reviewing the issue, the difference is as follows:

**Comment by zramsay** [comment]
TODO: update these descriptions when done with #231

**Comment by compleatang** [comment]
Let's deprecate this issue and move to tracking only in #231 (cause they're the same)
