### ISSUE TITLE
Chain becomes unusable after timeout induced problem in smart contract

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#1158]
When running an EPM job with a (probably) faulty smart contract, the EPM job errors out with a timeout.
```
Executing Job                                 testUintBytes32ArrayMap
Encountered error waiting for event: timed out waiting for event

Executing Job                                 assertUintBytes32ArrayMap
Assertion Failed                               == success
assertion failed
```

Subsequent to this, running any further EPM jobs against that chain results in 1000s of lines of this output:
```
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
[eris-client] Failed to unmarshal json bytes for websocket event: unexpected end of JSON input
```

Running the `eris pkgs` command for the first time produces the timeout. Any invocation thereafter results in the JSON unmarshalling error.

The issue is caused by and can be reproduced with an endless loop:
`for (uint i = 10; i >= 0; i--) {}`
Because uint wraps around to the max uint value when reaching zero, the loop has not effective break condition.

Requirements:
- Even though the problem is due to a programming error in solidity, the timeout of the operation should not render the chain useless. This should be analyzed to find a way to allow contracts to fail in this way and still leave the chain in a usable state.

OSX version: 10.11.6
Eris CLI Version: 0.12.0
Docker:
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      darwin/amd64
Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
docker-machine version 0.8.2, build e18a919

**Comment by zramsay** [comment]
so it kills the chain? no more block get produced? looks like a bug in `eris-client` within eris-db

**Comment by j-h-scheufen** [comment]
I stumbled upon the root cause in my contract and this could be a serious bug in the EVM portion: A loop counting down to `0` causes the timeout.
This loop works:
`for (uint i = 10; i > 0; i--) {}`
and this one breaks:
`for (uint i = 10; i >= 0; i--) {}`

Only difference: the `>` comparison operator vs. `>=`

**Comment by benjaminbollen** [comment]
Do you have the solidity code that recreates the issue?

**Comment by ratranqu** [comment]
The reason for the for loop to break is because the type of i is uint, but so the last i-- will leave it at 0 (silent overflow), and it will never go negative, so your condition will always be true. This behaviour is mentioned somewhere in the solidity doc, but can't find the exact place anymore.

**Comment by j-h-scheufen** [comment]
@ratranqu Thanks! You're 100% correct. I had already changed the loop and included this in our best practices, but forgot to update the ticket. I'm going to change the ticket to request better handling of "runaway" code on the chain which should result in gas depletion.

**Comment by j-h-scheufen** [comment]
Closing issue in favor of https://github.com/eris-ltd/eris-db/issues/452
