### ISSUE TITLE
eris keys gen causes status 1 error

### ISSUE THREAD

**Issue by nettijoe96** [eris-ltd/eris-cli#1159]
I am following the [tutorial](https://monax.io/docs/tutorials/getting-started/index.html?redirect_from_eris=true) and I am getting an error when creating the first key. I am very new at Eris.

When I create the gen key in section 2.a.1 of the tutorial I get an error

Command:
`eris key gen`

Error:
`Container interactive-b16dd4b9-f45e-44a9-9c86-66764a31b55e exited with status 1`

I have followed all the previous steps in the tutorial and have used eris chains ls and eris services ls to check if it is running.

Docker version: 1.12.5
Eris Version: 0.12.0
Windows 10 operating system
Eris, docker tools, and virtual machine installed through chocolatey

**Comment by zramsay** [comment]
hi @nettijoe96 this error can usually be solved by restarting docker-machine: `docker-machine restart eris`

**Comment by zramsay** [comment]
closing as not responded. feel free to re-open if you encounter the problem again.
