### ISSUE TITLE
Download old releases

### ISSUE THREAD

**Issue by redaz24** [eris-ltd/eris-cli#1160]
Hello,

I'm currently using the new version of eris ( the 0.12.0 ) but i would like to use an old release. I would like to know how can i download the 0.11.4 release.

Thank you very much

**Comment by zramsay** [comment]
hi @redaz24 you can either download the binary from https://github.com/eris-ltd/eris-cli/releases/tag/v0.11.4
or install from source with the `release_0.11`  branch

**Comment by redaz24** [comment]
hi @zramsay i did try to download the binary from https://github.com/eris-ltd/eris-cli/releases/tag/v0.11.4 but at the end of the installation i still have the 0.12.0 version im not sure why i keep getting the new version

**Comment by zramsay** [comment]
Did you previously install 0.12.0 ? Could you please provide the information in the issue template [here](https://github.com/eris-ltd/eris-cli/blob/master/.github/ISSUE_TEMPLATE.md), especially the "steps to reproduction" detailing exactly how you installed eris.

**Comment by redaz24** [comment]
Yes i did previously install the 0.12.0 using the tutorial in the monax website: sudo add-apt-repository https://apt.monax.io
curl -L https://apt.monax.io/APT-GPG-KEY | sudo apt-key add -
sudo apt-get update && sudo apt-get install -y eris


now to download the 0.11.4 version i did this,
sudo add-apt-repository https://apt.monax.io
curl -L https://github.com/eris-ltd/eris-cli/releases/download/v0.11.4/eris_0.11.4_linux_amd64 > eris
chmod +x eris
sudo apt-get install -y eris

**Comment by zramsay** [comment]
after `chmod +x eris`, run something like `mv eris $(which eris)` to replace the current - still installed 0.12.0 binary and omit running `sudo apt-get install -y eris` as this will overwrite version 0.11.4 you've just installed.

**Comment by pietv** [comment]
one small bit. the binary for 0.11.4 is in a ZIP archive, you have to unpack it first as well (just in case this isn't obvious):

```
$ curl -L https://github.com/eris-ltd/eris-cli/releases/download/v0.11.4/eris_0.11.4_linux_amd64.tar.gz > eris_0.11.4.tar.gz
$ tar xf eris_0.11.4.tar.gz
```
and then move the binary to `$(which eris)` or to whatever path is in your `PATH`. Could be `/usr/local/bin`, for example:
```
$ mv eris_0.11.4_linux_amd64/eris /usr/local/bin
```

Also, please don't forget to scrap your `~/.eris` directory:
```
$ eris clean -y --dir
```

**Comment by redaz24** [comment]
Yes Its working now, thank you very much for your help, you can close the issue now.

Thanks
