### ISSUE TITLE
chain is not making blocks

### ISSUE THREAD

**Issue by Akriti-sahu** [eris-ltd/eris-cli#1181]
Please include in your bug report:

- [1.12.5 ] `docker version`- 
- [0.12.0 ] `eris version`
- [ 4.9.3 linux/amd64] `go version` (if applicable)
- [ubuntu 14.04 LTS ] operating system details (osx/windows/linux)

- I have created a blockchain with 1:full, 1:root and 2:validator nodes. Due to some reasons I restarted my root node without stoping the chain. and after restarting the system when I am trying to connect back to the chain using this root node it connects to the full node but not making blocks. and showing logs like this -

INFO[01-24|04:35:44] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" peerRound=0 height=9502 round=0 precommits=nil-BitArray index=1
INFO[01-24|04:35:44] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[NewRoundStep H:9502 R:0 S:RoundStepCommit LCR:0]"
INFO[01-24|04:35:44] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[CommitStep H:9502 BP:PartSet{T:1 6D7065F90B78} BA:BA{1:X}]"
INFO[01-24|04:35:44] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[NewRoundStep H:9503 R:0 S:RoundStepNewHeight LCR:0]"
INFO[01-24|04:35:44] Receive                                  module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[HasVote VI:2 V:{9502/00/2} VI:2]"

I don't know why it is not connecting to the chain properly. Can anyone phases this issue? Need help on this.

**Comment by Akriti-sahu** [comment]
I have restarted my whole chain by stoping the chain first then doing eris clean and then again started the chain. Now it is making block. But why it is so?? means if due to some reasons if my root node has been restarted that node becomes useless as it is not making any more blocks after reconnecting. As of my thought that should not be happened.

**Comment by zramsay** [comment]
Hi @Akriti-sahu without significantly more information about how you went about creating your chains, I cannot tell you why it didn't work the first time around. Since it sounds like you've got it working, I'm closing this issue for now. Feel free to re-open with much more detail if you encounter additional problems.

**Comment by Akriti-sahu** [comment]
hi @zramsay, thanks for your response. As I mentioned before, I have created a chain in local systems with 1:full, 1:root and 2:validators . It was working fine. but due to some reason my one system that I have created as a root node, has been restarted (It means i didn't stop the chain manually by typing **eris chains stop**). then I again started my chain by using **eris chains start** command. It is showing that my chain is started as when I type **eris chains ls**, it is showing that my chain is active. But when I am checking this on my browser by typing **http://localhost:46657/status** where I can see the blocks are generating, it was not generating the blocks and when I am checking it by **eris chains logs** it was showing me logs like this-

INFO[01-24|04:35:44] SetHasVote(round-match) module=consensus peer="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" peerRound=0 height=9502 round=0 precommits=nil-BitArray index=1
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[NewRoundStep H:9502 R:0 S:RoundStepCommit LCR:0]"
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[CommitStep H:9502 BP:PartSet{T:1 6D7065F90B78} BA:BA{1:X}]"
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[NewRoundStep H:9503 R:0 S:RoundStepNewHeight LCR:0]"
INFO[01-24|04:35:44] Receive module=consensus src="Peer{MConn{192.168.1.43:46656} D0D853AB9947 out}" chId=20 msg="[HasVote VI:2 V:{9502/00/2} VI:2]"

but the other nodes that is 1 full and 2 validators were generating blocks properly. only this root node system which is been restarted was not generating the blocks.
Then due to this issue I have stopped my whole chain completely by typing **eris chains stop** and clean the eris by typing **eris clean** and then again started the chains first I started the 1:full node, then  1:root node and 2:validators node. and now my system is up. 

So my question is that if due to some reason my root node system has been restarted and if I connect that node again to the chain it is no more creating any blocks, that means that root node is not working properly?? why it is so?? it should work properly after reconnect also as I thought but it was not.
