### ISSUE TITLE
eris services render

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#120]
"injecting" a particular chain into a service def template

eg `eris services render mindy mychain`

should write the service `mindy_mychain` which includes the mindy image and the mindy dependencies (including, now, mychain). Should take a `--name`

this will probably be a common theme: we have an "application definition", which is basically a service def without a chain dependency, and we want to inject a chain.

**Comment by compleatang** [comment]
Closing as this is handled via [this function](https://github.com/eris-ltd/eris-cli/blob/develop/services/operate.go#L137). 

To inject a chain, add the following line to any service definition file:

```toml
chain: "$chain"
```

Then when the service is started with `--chain MYCHAIN` the service boot loader will add the MYCHAIN service to the service group which is booted sequentially. It'll also add its volumes, links, etc.
