### ISSUE TITLE
CONTAINER_HOST var for where the containers are running (support kitematic)

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#124]
seems eris-cli and the mint-client tools hard code 0.0.0.0 as the address of containers, which is incompatible with running containers in vms (ala eg kitematic/boot2docker). We need an env var

**Comment by compleatang** [comment]
usually with the go http libs we only bind to 0.0.0.0 and which would be local host inside the container. 

the reason for this binding is that 127.0.0.1 doesn't always receive inbound http calls with the standard go container. i haven't taken a look for that.

but the container *usually* doesn't need to bind to a specific IP other than `localhost`. 

this isn't to say that we shouldn't add this feature, but it shouldn't really be blocking anything.

**Comment by ebuchman** [comment]
but isn't the problem that the container is running in a virtual machine, and the vm has its own IP from the perspective of the host?

**Comment by compleatang** [comment]
yes. indeed. asked slowtokyo (on his gist) to see if we can pull the vm's ipAddress via `eris services inspect ...`. if that fails then we'll have isolated the problem. 

the current fix is redundant in that we're already reading from the Host's EnvVar (just using a different varName than what Zach added), so all we need to do is set that. the globalConfig behaviour is that the EnvVar overwrites eris.toml config, and eris.toml config is plopped `postRun`. 

once we figure out exactly what we need to set (vm level or host level) for best cross platform compatibility then we'll just do that in when ipfs is started and fall back to it (the FindTheRightIPForIpfs function) if we get this error in the future.

**Comment by slowtokyo** [comment]
Hi, just letting you know that as on the gist, the workaround did not solve the problem.

**Comment by compleatang** [comment]
OK. Thanks. That isolates it then.

**Comment by zramsay** [comment]
@slowtokyo we've solved the issue. I got it working using the [toolbox](https://www.docker.com/toolbox) rather than Kitematic on its own. Also, `ERIS_IPFS_HOST` should include `http://` with the output of `docker-machine ip [name]`. I've updated the tutorial to reflect this.
