### ISSUE TITLE
disentangle tests

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#126]
it appears the eris-cli unit tests depend on one another. i think this needs to be disentangled so each can stand alone

**Comment by compleatang** [comment]
agree we should be doing independent unit tests. where have you seen dependencies?

**Comment by ebuchman** [comment]
tbh I'm not sure. I haven't seen those tests pass in weeks and I haven't really been working on that codebase much. but whenever i dive in it seems like tests depend on others. eg it seems like TestInspectService and TestLogsService are depending on TestStartService having been run

**Comment by compleatang** [comment]
oh. right. within the services tests there is some sequencing we have to do.

**Comment by ebuchman** [comment]
i think it would be best if each Test function did whatever it needed to set up the things it depends on and shut them down. what do you think? will it be too much overhead?

**Comment by compleatang** [comment]
Functionally all that would do would take disparate tests and make then more unified. I mean to test Inspect and Logs we have to have a service running.... if service start fails then something awful has gone wrong. I guess it is just different perspectives on what the "unit". 

I'm definitely open to any ideas for better testing practices, but I'm gonna bump this to 0.11 so we can give it time to think.

**Comment by ebuchman** [comment]
ya. so basically I'd still have a TestStartService. and it would call startService. And then TestInspect would also call startService, but it wouldn't bother doing all the checks, for example. or maybe it would still. 

its just harder to debug if you can't do `go test --test.run TestWhatever` for a single test at a time.

**Comment by compleatang** [comment]
OK. That's a good idea.

**Comment by compleatang** [comment]
This is done. Needs more work, but its fine for now. We can work against more precise issues as the need arises.
