### ISSUE TITLE
`eris chains new` requires a git user name

### ISSUE THREAD

**Issue by tom-seddon** [eris-ltd/eris-cli#143]
If you haven't got a git user name set up (e.g., with `git --global user.name`), you get a rather cryptic error when running `eris chains new`:

    Error on setupChain =>		the key `user.name` is not found

(the issue is that the error message is a bit unclear, not that you have to have a git user name necessarily!)

--Tom

**Comment by zramsay** [comment]
Good catch, I'll fix that today.

**Comment by compleatang** [comment]
fix pushed to master.
