### ISSUE TITLE
`eris chains new` fails

### ISSUE THREAD

**Issue by tom-seddon** [eris-ltd/eris-cli#144]
I'm using a vagrant VM set up with https://gist.github.com/tom-seddon/753fc3e9796d6786a3ce (host is VirtualBox 5.0.3 on OS X)

`eris chains new` fails to start the docker image and produces a couple of worrying-looking error messages as it does so:

    vagrant@vagrant-ubuntu-trusty-64:~$ docker --version
    Docker version 1.8.1, build d12ea79
    vagrant@vagrant-ubuntu-trusty-64:~$ eris chains new tom1
    Pulling image (eris/data) from repository. This could take a second.
    Pulling image (eris/erisdb:0.10) from repository. This could take a second.
    new chain: tom1
    Error: unknown flag: --single
    Run 'mintgen help' for usage.
    Type hostname: WARN[08-20|12:42:11] Error reading stdin                      module=config err=EOF
    File written to /home/eris/.eris/blockchains/tom1/config.toml.
    File written to /home/eris/.eris/blockchains/tom1/genesis.json.
    INFO[08-20|12:42:11] Generated PrivValidator                  module=node file=/home/eris/.eris/blockchains/tom1/priv_validator.json
    DBUG[08-20|12:42:11] addRound(round)                          module=consensus round=0
    DBUG[08-20|12:42:11] Local listener                           module=p2p ip=:: port=46656
    DBUG[08-20|12:42:11] Getting UPNP external address            module=p2p
    vagrant@vagrant-ubuntu-trusty-64:~$ docker ps
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
    vagrant@vagrant-ubuntu-trusty-64:~$

I'm a bit of a beginner with docker, so I'm not (yet) sure how to get more logs out of it than this.

--Tom

**Comment by tom-seddon** [comment]
This seems to be where the `--single` bit comes from: https://github.com/eris-ltd/eris-db/blob/develop/DOCKER/chain_new.sh

Supply your own genesis block with `-g`, and you don't get the error, and the blockchain appears to work.

--Tom

**Comment by zramsay** [comment]
Right, so `mintgen` was refactored & `--single` deprecated. Fails on OSX but not linux, though it should definitely fail on linux. Fix coming soon.

**Comment by zramsay** [comment]
ok this has been fixed with 372eb16. You'll have to `docker pull eris/erisdb:0.10` to get the latest image

**Comment by slowtokyo** [comment]
@zramsay, thanks for the help. I haven't had the time to look into it deeply, but wanted to note that the same error message as explained in #141 popped up again after pulling the new image.

**Comment by zramsay** [comment]
this will be updated in the next couple days - a handful of changes are in the pipeline
