### ISSUE TITLE
chains new upgrade

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#146]
chains new should offer some options for the genesis and config files it lays

Flags
-----
- [x] `-g`/`--genesis` - provide a genesis.json so `mintgen` need not be called
- [x] `-c`/`--config` - provide a config.toml so `mintconfig` need not be called, or provide a comma separated list of `<key>:<value>` pairs to be used in `mintconfig`
- [x] `--dir` - copy in the contents of a whole directory. 
- [x] `--csv` - pass a csv file to `mintgen`
- [ ] `-N` - create <N> data containers and get the output from mintgen into each of them
- [x] `--priv` - pass in a priv_validator.json. temporary until we can use eris-keys for signing

examples
`eris chains new chain_id` - simplest case. runs `mintgen random 1 chain_id`
`eris chains new -N <N> chain_id` - create <N> data containers, run `mintgen random <N> chain_id` with volumes from all of them such that the resulting directories go to the right places ...
`eris chains new chain_id --csv=mycsv.csv --priv=priv_validator.json --config="fast_sync:true,log_level=error"`

**Comment by compleatang** [comment]
:+1:

**Comment by ebuchman** [comment]
implemented in https://github.com/eris-ltd/eris-cli/pull/155 + erisdb:0.10.1
moving `-N` to its own issue (https://github.com/eris-ltd/eris-cli/issues/156) as its a bit more involved
