### ISSUE TITLE
base service for eris chains

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#147]
right now the base service for eris chains is hard coded in a variety of places in the cli. eg. the image version, the keys dependency. Might be better to use the `services/erisdb.toml` so users can have more control over the defaults. not sure if this default service def should go in services or blockchains, but we should have some command for writing/restoring the default version.

**Comment by compleatang** [comment]
I'm of two minds here. Let us assume that the two options would be having a def file in ~/.eris/blockchains/erisdb.toml *or* hardcoding.

Pros of def file:

* user flexibility
* DRYs up the code a bit

Pros of hardcoding (assuming we DRY it up)

* users don't hang themselves with too much rope. 

I'm hesitant to put the def file (if we go that route -- which i think sensible and would be my vote) in the services folder as I think it would get us back to the confusion we had internally as to "what's a service; what's a chain".

**Comment by ebuchman** [comment]
My view: we should hardcode the default and drop it in blockchains if its not there, and read from it if it is. We can `eris chains restore` or something to get it to drop the hardcoded default again

**Comment by compleatang** [comment]
Ok. Happy with that.

**Comment by compleatang** [comment]
i think it will be more illustrative to use `~/.eris/blockchains/default.toml` than `.../erisdb.toml`

**Comment by compleatang** [comment]
shipped with 0.10.1
