### ISSUE TITLE
eris chains install changes config file name

### ISSUE THREAD

**Issue by tom-seddon** [eris-ltd/eris-cli#148]
When using eris chains install with the -c option to specify a config.toml, file, it adds an extra . between name and extension, meaning the node can't find the file.

Files before running it:

    vagrant@vagrant-ubuntu-trusty-64:~$ find ~/.eris -type f
    /home/vagrant/.eris/blockchains/config/default/genesis.json
    /home/vagrant/.eris/blockchains/config/default/priv_validator.json
    /home/vagrant/.eris/blockchains/config/default/config.toml
    /home/vagrant/.eris/blockchains/config/default/server_conf.toml
    /home/vagrant/.eris/blockchains/HEAD
    /home/vagrant/.eris/eris.toml
    /home/vagrant/.eris/actions/do_not_use.toml
    /home/vagrant/.eris/services/keys.toml
    /home/vagrant/.eris/services/ipfs.toml

Running process:

    vagrant@vagrant-ubuntu-trusty-64:~$ eris chains install n4_test_chain -c /vagrant/main/config.toml --dir=/vagrant/dir
    Pulling image (eris/data) from repository. This could take a second.
    Pulling image (eris/erisdb:0.10) from repository. This could take a second.
    laying default config...
    Seed node: interblock.io:46657
    Host name: mint_user
    Running mint in /home/eris/.eris/blockchains/n4_test_chain
    --------------- (output removed) ---------------
    ^C

Files after running it:

    vagrant@vagrant-ubuntu-trusty-64:~find ~/.eris -type f
    /home/vagrant/.eris/blockchains/config/default/genesis.json
    /home/vagrant/.eris/blockchains/config/default/priv_validator.json
    /home/vagrant/.eris/blockchains/config/default/config.toml
    /home/vagrant/.eris/blockchains/config/default/server_conf.toml
    /home/vagrant/.eris/blockchains/n4_test_chain.toml
    /home/vagrant/.eris/blockchains/HEAD
    /home/vagrant/.eris/eris.toml
    /home/vagrant/.eris/actions/do_not_use.toml
    /home/vagrant/.eris/data/n4_test_chain/blockchains/n4_test_chain/config..toml
    /home/vagrant/.eris/data/n4_test_chain/blockchains/n4_test_chain/genesis.json
    /home/vagrant/.eris/services/keys.toml
    /home/vagrant/.eris/services/ipfs.toml

Note that the config file is called config..toml.

Thanks,

--Tom

**Comment by tom-seddon** [comment]
This can be worked around temporarily by stopping the container, renaming the offending file, then doing `eris data import XXX` and `eris chains start XXX`.

--Tom

**Comment by compleatang** [comment]
Thanks for the issue Tom. We've reworked this entirely so it should be a-OK now we have more complete testing around the chains new sequence to support. 

But if it returns then let us know. And feel free to reopen.
