### ISSUE TITLE
EnsureRunning should take an endpoint to ping until positive response

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#149]

**Comment by compleatang** [comment]
:+1:

**Comment by compleatang** [comment]
just need to use `net.Dial(endpoint)` on a loop (with a timeout)

**Comment by zramsay** [comment]
so we'll need to add an endpoint to each servDef file (i.e., the port to be ping-ed), or loop through all ports & try each?

**Comment by compleatang** [comment]
if you loop through the exposed ports there shouldn't be too many per container (btc has like 8 but everybody else seems to have 1-3 AFAIK).

**Comment by ebuchman** [comment]
great idea!

**Comment by ebuchman** [comment]
I have a new opinion on this matter: it's not a feature we can support in general. 
1) I'm not sure it can even work for udp (since who knows what you have to send to get data back)
2) I think the tcp connection is made right away to docker  listening on the bound port, not necessarily the server running in the container, so its a false positive.
3) the feature is only used for ipfs. we can just have EnsureIpfsRunning

It should be a clients duty to determine if the endpoint is up. eris-cli is only a client for ipfs, so we shouldn't burden ourselves by taking on this responsibility in general.

**Comment by compleatang** [comment]
yes. to confirm publicly, E is right. the empty POST was a bad idea. we're gonna stick with `net.Dial` for the exposed ports.
