### ISSUE TITLE
chains new -g should overwrite chain_id in genesis with do.ChainID

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#151]
few options here:
- string match the json and replace whatever is between quotes after "chain_id" (from setupChain)
- import tendermint/state/types and unmarshal/remarshal the whole json (from setupChain)
- install jq in erisdb and do it in the chains_new.sh shell script

**Comment by compleatang** [comment]
given how much we rely upon jq that would probably be the easiest option. although taking that route would move us away from being able to do "light" containers and would tie us to using the debian base image we have been using so far.

**Comment by ebuchman** [comment]
this is done in erisdb:0.10.1 but should add a test before https://github.com/eris-ltd/eris-cli/pull/155 is merged
