### ISSUE TITLE
cleanup/refactor eris files

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#160]
code is messy, especially with recent additions. maybe we export an ipfs library?

**Comment by zramsay** [comment]
we need to figure out what to do with ipfs code. as i'm building the toadserver, it seems like a repo for these ipfs wrappers is the best option and most modular (and we'd avoid things like https://github.com/eris-ltd/eris-cli/pull/168#discussion-diff-38011512R17)

**Comment by compleatang** [comment]
agree. let's put those in `common/go/ipfs`
