### ISSUE TITLE
fix services export and import

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#163]
can wait until the ipfs refactor is done.

**Comment by compleatang** [comment]
@zramsay when you get a chance could you look into this and add some tests for it. we weren't testing this under the previous regime because docker on circle weirdness. now that we have that cleaned up, we should add some tests cause I think this has been failing for a bit now.

**Comment by zramsay** [comment]
- [ ] check the formatting of import file

**Comment by compleatang** [comment]
:+1:
