### ISSUE TITLE
Can't install eris

### ISSUE THREAD

**Issue by iceinsidefire** [eris-ltd/eris-cli#164]
I have Docker version 1.8 and Go 1.4.2

When I type "go get github.com/eris-ltd/eris-cli/cmd/eris", it does nothing.
And after that, when I type "eris init", it gives error.
"No command 'eris' found"

What should i do?

**Comment by zramsay** [comment]
try `git clone github.com/eris-ltd/eris-cli` then
`cd eris-cli/` then
`go install ./cmd/eris`

**Comment by compleatang** [comment]
he confirmed on irc that this worked. closing.

**Comment by iceinsidefire** [comment]
Yes. This issue is resolved.

I had to make new directory and point $GOROOT towards it and set PATH=$PATH:$GOROOT\bin.
then i was able to install it.

Thank you.
