### ISSUE TITLE
services/chains exec 

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#171]

**Comment by compleatang** [comment]
bringing them back!

**Comment by zramsay** [comment]
#101

**Comment by ebuchman** [comment]
re the old discussion, the problem isn't so much that we need exec (exec on data alone is probably fine), but that we need to be able to run commands from the services - ie. the dockerfiles should be designed to use ENTRYPOINT so there is clear cli access, and we need to provide an interface to that. an example is running `eris-keys gen

**Comment by compleatang** [comment]
agree. been moving more of the dockerfiles to use entrypoint now that 1.8 docker is the standard (and we all have a better handling of the diff's).
