### ISSUE TITLE
"invalid endpoint" after `eris init`

### ISSUE THREAD

**Issue by taoeffect** [eris-ltd/eris-cli#173]
I followed the instructions in the quick start on the main docs page, but alas `eris init` failed with an obscure error.

```
-> % eris init
invalid endpoint
```

`docker-machine ls` shows a VM was created. The `eris chains` fails:

```
-> % docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM
eris            virtualbox   Running   tcp://192.168.99.100:2376
-> % eris chains new test_chain
open tcp:/192.168.99.100:2376
/cert.pem: no such file or directory
```

**Comment by taoeffect** [comment]
With `--debug`:

```
-> % eris init --debug
Querying the eris docker-machine's url.
Could not connect to the eris docker-machine.
Error:	Could not evaluate the env vars for the eris docker-machine.
Error:	exit status 1

Trying default docker-machine.
Querying the default docker-machine's url.
Could not connect to the default docker-machine.
Error:	Could not evaluate the env vars for the default docker-machine.
Error:	exit status 1

Trying to set up a new machine.
Querying the default docker-machine's url.
The marmots will create an eris machine.
Creating the eris docker-machine.
Eris docker-machine created.
Starting eris docker-machine.
Eris docker-machine started.
New docker machine created using virtualbox driver. Getting the proper environment variables.
Querying the eris docker-machine's url.
	URL =>			tcp://192.168.99.100:2376

Querying the eris docker-machine's certificate path.
	Certificate Path =>	/Users/greg/.docker/machine/certs
Querying whether the host and user have access to the right files for TLS connection to docker.
	Certs files look good.
Setting the environment variables for quick future development.
Finished getting machine details for =>	eris
Docker client connects correctly.
Connecting to the Docker Client via: tcp://192.168.99.100:2376

Docker Certificate Path: /Users/greg/.docker/machine/certs
invalid endpoint
```

**Comment by ebuchman** [comment]
does normal docker stuff work for you? eg `docker pull eris/keys` and `docker run -d eris/keys` ?

**Comment by compleatang** [comment]
I've added some more verbosity here. Can you rerun this command on develop and see if it throws.

**Comment by compleatang** [comment]
@taoeffect when you have a chance, could you confirm if this persists on current master (v0.10.1 release)

**Comment by tomtruitt** [comment]
I haven't tried those commands but I have tried to rm some Docker images and get an error saying ID doesn't exist

**Comment by tomtruitt** [comment]
Unrelated to this issue but your question to tao made me think of it

**Comment by compleatang** [comment]
Tom, did you check the images exist with `docker images`? By default eris only pulls the service definition files (which tell eris how to start docker containers). When a docker container is started, if the docker daemon does not have the base image available locally to create and run the container it will pull it from the docker hub (only at that point). Point being that you may not have the images available locally. 

Another factor to consider here is if you're using VMs via docker-machine to make sure you're talking to the proper backend VM.

**Comment by tomtruitt** [comment]
Yeah so the images I'm referring to are the old decerver and hello-world and some others that I have had locally and they show up with docker images. I don't even know what docker-machine is lol

**Comment by compleatang** [comment]
no problem (that means you're on linux :) ). try removing them via their hash.

**Comment by tomtruitt** [comment]
Oh right now I remember that's for windows. Yeah that's thing I have been using the hash. I'll send you a screen shot or copy and paste when I get a chance

**Comment by compleatang** [comment]
OK. Please make a separate issue for that. Also, we are not fully in a position to support all of docker's issues, but we'll try to look into it for you.

**Comment by tomtruitt** [comment]
Yeah I only mention it because I beleive it worked fine before installing eris 0.10 but I may be wrong as I recently created this machine and may be thinking of the last

**Comment by compleatang** [comment]
No worries.

**Comment by tomtruitt** [comment]
I'll treat it as a Docker issue unless it appears to be tied to eris somehow. It may have been the last machine where it worked fine and may in fact have never worked on this one. If it somehow seems tied to eris I'll bring it back up in new issue

**Comment by compleatang** [comment]
Thanks!

**Comment by taoeffect** [comment]
Sorry for the radio silence for a bit, had to take care of something.

I'm pleased to report that using the latest `develop` branch (c17d0a2) the `eris init` command now seems to be working (and outputting stuff! good!):

```
-> % eris init
The marmots could not find a docker-machine virtual machine they could connect to.
Our marmots recommend that you have a vm dedicated to eris dev-ing.
Would you like the marmots to create a machine for you? (Y/n): y
The marmots will create an eris machine.
Creating the eris docker-machine.
This will take some time, please feel free to go feed your marmot.
```

It then exits (should print a success message before doing that though).

There is a new `eris` docker image running (confirmed via `docker-machine ls`).

`eris chains new test_chain` returns immediately, does not say whether it succeeded or not (should probably create an issue for this, but I've gotta run right now or I'll be late to a doc appointment).

I'm assuming things are working, but I cannot be sure without some sort of indicator of success.

**Comment by compleatang** [comment]
That didn't work. Wondering if dm create taking too long....

**Comment by compleatang** [comment]
Looks like the subject of this issue is resolved so am going to close, we can deal with init issues here one by one as they arise.
