### ISSUE TITLE
refactor chain checkout to not start chain on service start if no $chain in serv def file

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#175]
```
***@ubuntu:~/.eris/services$ eris services start eth
Pulling image (eris/eth) from repository. This could take a second.
StartGroup. Err starting srv =>    test_chain:container already exists
```

**Comment by tomtruitt** [comment]
I have to check but I believe I had this same error upon 'eris chains start'

**Comment by tomtruitt** [comment]
No Nevermind

**Comment by compleatang** [comment]
Tom, it may have been intermittent. If you had a chain checked out then it may have fired.

**Comment by tomtruitt** [comment]
hi just curious: is there a workaround for this i could use to start a service?

**Comment by compleatang** [comment]
There are two. First if you just `eris chains checkout` without arguments that will uncheck out the chain and it shouldn't fail. Second, if you update to current develop @ebuchman pushed a fix for this last night.

**Comment by ebuchman** [comment]
services with no chain variable won't start a chain
