### ISSUE TITLE
env vars flags 

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#180]

**Comment by compleatang** [comment]
note to do this like docker does it we're gonna need to monkeypatch that pFlags lib we use to parse the flags. we could also do it differently than docker and just use a string slice and parse on the `=` so it would be like:

```
eris services start --env ASDF=qwer,FOO=bar serviceName
```

that would be the easiest way to do it and would not require monkeyPatching the lib.

**Comment by ebuchman** [comment]
yup that's what I was thinking to do

**Comment by compleatang** [comment]
completed. closing
