### ISSUE TITLE
finer grained control on linking and volumes-from for each dependency and chain

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#187]

**Comment by compleatang** [comment]
Outline what flags you're thinking needed? 

`--volumes-from 1234,asdf,qwer` (overrides service deps...?)
`--link 1234,asdf,qwer` (also)

alternatively we could pass flags like this:

`--services 1234:l,asdf:v,qwer:a, zxcv:n` (where `l` only links, `v` only mounts volumes, `a` (default) does both, and `n` does neither)

**Comment by ebuchman** [comment]
i like something more like your `--services` option

**Comment by ebuchman** [comment]
but also it'd be good to be able to specify from the service def.

eg. for mindy tinydns doesn't need to be linked to anything (only volumes-from its own container), while the mindy container needs volumes-from tinydns and link to tendermint (but not link to tinydns or volumes-from tendermint)

**Comment by compleatang** [comment]
Me too. Remember when is was building service deps this would come up and at the time it seemed a bit complex but most succinct and powerful.

**Comment by ebuchman** [comment]
also, maybe this isnt the place to put it, but im feeling more and more (at least for now) that chains should be stand alone units - ie. we dont link them to anything else

**Comment by ebuchman** [comment]
ya good to avoid too muhc omplexity but i thinkk eg like `dependencies = [ "tinydns:v" ] isnt so bad. Though it should probably be `[ "tinydns::v" ]` where we use two `:` because we need to be able to name it in container to (we dont want to name it `v` ...)

**Comment by compleatang** [comment]
Interesting. Because we can always graduate and that will be cleaner? Personally I go back and forth on this daily. Can definitely see a use case for keeping the chains flag at least. Like it you want to run Mindy against a specific etcb or something like that.

**Comment by ebuchman** [comment]
right so. take a look at the changes i made last night. a chain is a standalone unit because it must be started first so others can link to it and because it shouldn't need to depend on annything. any use case which wants it to depend on something can graduate it to a service or just build another service that uses the chain.

and the `$chain` option is bloody great

**Comment by compleatang** [comment]
Yes. I read them. Great changes. 

Note for any readers. It still needs some work but `$chain` will soon be able to just read the checked out chain, but for now only the flag will work.

**Comment by ebuchman** [comment]
control is left to the service definition (not sure there's a need for control from flags. if such a need arises, we can revisit). closing.
