### ISSUE TITLE
eris init returns non-zero exit code

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-cli#190]
There are no error messages but `eris init` returns an error code:

```shell
# ls -a ~
.  ..  .bashrc	.gnupg	.profile
# eris init; echo $?
1
# ls -a ~
.  ..  .bashrc	.eris  .gnupg  .profile
```

**Comment by NodeGuy** [comment]
Upon further investigation, the error code is correct because Docker wasn't running properly.  The problem is the lack of an error message.

**Comment by compleatang** [comment]
init should be quite chatty now. but that chattiness is pretty recent, what commit are you on?

**Comment by zramsay** [comment]
closing; #194 has better error handling

**Comment by NodeGuy** [comment]
I don't know the commit; it's from a `go get`.  The version number reported
is 0.10.1.
