### ISSUE TITLE
`eris version` outputs nothing

### ISSUE THREAD

**Issue by taoeffect** [eris-ltd/eris-cli#196]
This is using the latest stuff from c17d0a2.

When I first ran it, it gave:

```
-> % eris version
The marmots could not find a docker-machine virtual machine they could connect to.
Our marmots recommend that you have a vm dedicated to eris dev-ing.
Would you like the marmots to create a machine for you? (Y/n): Y
The marmots will create an eris machine.
Creating the eris docker-machine.
This will take some time, please feel free to go feed your marmot.
```
Then nothing, back to prompt.

Re-running gives no output.

**Comment by zramsay** [comment]
has to do with the OSX / docker-machine boot-up sequence. might be namespacing, might be the nuance between a `STATE: Running`, `ACTIVE (blank)` and `STATE: Running`, `ACTIVE *`

workaround: nail down the boot-up sequence & add to docs
fix: figure out how to properly boot-up a `docker-machine` under various `STATE` or `ACTIVE`

**Comment by taoeffect** [comment]
Turns out the problem was that I needed to run `eval "$(docker-machine env eris)"` prior to running the `eris` commands. That fixed it.

Well... `eris` should check to see if I need to run that and run it for me. :P

**Comment by zramsay** [comment]
`docker-machine` *should* prompt the running of that cmd on startup (but yeah, our plumbing should handle it)
