### ISSUE TITLE
To Do or Not To Do

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#202]

**Comment by compleatang** [comment]
continuation of this discussion: https://github.com/eris-ltd/eris-cli/pull/199#discussion_r38484103

**Comment by ebuchman** [comment]
Ok so I think we need to bust it up, hopefully not into one args type per function, but rather into a few categories of SubDo's. That is, we need to subdue Do into SubDo's.

**Comment by compleatang** [comment]
did you think of the pun and then write the comment after? :maple_leaf: :candy:

**Comment by ebuchman** [comment]
nope the comment begot the pun

**Comment by compleatang** [comment]
closing for now. we can revisit for 1.0 / 0.13....

**Comment by zramsay** [comment]
i'm fine with the way it is, especially since we won't be adding much more moving forward.
