### ISSUE TITLE
Long running commands should tell user what they're doing

### ISSUE THREAD

**Issue by taoeffect** [eris-ltd/eris-cli#205]
So we figured out the problem to #196 and now I can finally run `eris chains` and have it do something other than return immediately.

However:

- It sits there doing nothing for a very long time. Any time there's a long running command, it should give some indication of progress.
- From my magic sensors, I can tell it's downloading something massive. It should say that.
- According to @zramsay it's downloading the docker image for `erisdb`.

~~It also failed with some errors, but I'll open a separate issue for that.~~ Apparently this is a known issue according to Zach.

**Comment by zramsay** [comment]
this is generally (only?) anytime an image is being pulled (otherwise output is fairly verbose). add prog bar?

**Comment by taoeffect** [comment]
Most terminal commands take less than half a second to run.

If a command takes a second or more, it should output something about its progress.

If a command is about to do something that might be objectionable to the user for any reason (like download a 500MB image), it should first ask for the user's permission before doing so, and then show progress.

Finally, if a download was started but interrupted then `eris` needs to handle that appropriately by:

- Removing the unfinished file prior to exiting (unless it's possible to resume the download when the command is re-run).
- Check for any unfinished downloads from a previous session (for example, a crash) and take care of them appropriately (either by deleting them or resuming the download).

Downloads should show progress indicators of some sort (with a time estimate preferably).

**Comment by taoeffect** [comment]
> If a command is about to do something that might be objectionable to the user for any reason (like downloading a 500MB image), it should first ask for the user's permission before doing so, and then show progress.

Some nuance to this:

- It's possible to not ask for the user's permission if ^C properly cleans up the attempted download.
- If you do ask for the user's permission, then there needs to be a flag like `--yes` to skip the prompt and answer yes automatically (this is necessary for `eris` itself to be wrapped as part of some other script).

**Comment by zramsay** [comment]
@NodeGuy any comments here?, re: today's discussion

**Comment by NodeGuy** [comment]
I agree that we need a progress indicator.

I don't think we need to ask permission before downloading 500 MB and I don't think it's important to clean it up (except perhaps in an Eris uninstall script).  Hopefully Docker will resume the download automatically if it's interrupted.

**Comment by zramsay** [comment]
ok we've got both a prompt & progress indicator now. cleaning will eventually happen with `eris clean` (#209). closing b/c this issue has been addressed
