### ISSUE TITLE
image download prompt + prog bar

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#208]
- [x] prompt user to proceed; letting them know 1/2 gig is coming their way
- [x] prog bar
- #207 
- #205

**Comment by compleatang** [comment]
(good label!)

not sure if we can do a prog bar, but for the pull commands i'm pretty sure I kanked docker's display of progress, perhaps we just give that display a writer and use dockers rather than trying to figure out how to do that bit on our own.
