### ISSUE TITLE
add `--force` to services stop and chains stop

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#21]

**Comment by compleatang** [comment]
We're using DockerKill behind the scenes (after stopping gracefully if the service is running). There's a timeout feature on the API stop call, so that gives a chance for the container to shut down gracefully. 

Maybe that's not the desired behaviour, though.

**Comment by ebuchman** [comment]
so looks like we're using StopContainer, not KillContainer. I thiknk we should offer both. One for graceful shutdown (stop), one for "die now" (kill)

**Comment by compleatang** [comment]
Perf. and map that to `stop -f` or whatever.

**Comment by compleatang** [comment]
closed by a6c91bc
