### ISSUE TITLE
first POST on fresh container returns `connection reset by peer`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#212]
run it again and it works fine. always just the first attempt on a freshly booted container that returns this:
`Post http://0.0.0.0:8080/ipfs/: read tcp 127.0.0.1:8080: connection reset by peer`

bug has been identified by a few people, our fix always being "try again, it'll work". regardless, not a smooth UX

fix: check for that response and try again (hacky?). or is there something more fundamental that needs addressing?

**Comment by compleatang** [comment]
i wonder if we should do a POST when we ping on `EnsureRunning`; that should solve this...?

**Comment by zramsay** [comment]
an empty POST? yeah, that should work. it'll probably fix the failing tests i'm getting working on #149

**Comment by zramsay** [comment]
dealt with in #213
