### ISSUE TITLE
by default services stop should not stop dependent services

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#22]
add an `--all` flag for this behaviour. 

reason is this: many services will depend, e.g., on the keys service, and this will likely just want to be running continuously. stopping services which depend on keys could lead to weird results. of course other services will just start keys if its down, but this is probably unnecessary behaviour.

thoughts?

**Comment by ebuchman** [comment]
--all is good. I added support for stopping multiple at once so `ersi services stop mindy tinydns mint` but id rather `eris services stop -all mindy`

**Comment by compleatang** [comment]
cool.

this is mostly done. just need to verify a few things.

**Comment by compleatang** [comment]
closed by 972917a
