### ISSUE TITLE
Remove Ensure Running

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#220]
https://github.com/eris-ltd/eris-cli/commit/4ebec25f591daca9852848eb7587beddd02df292#diff-bedfcf59ccad778eca6631b2cd237ca9R41

is a mess

We cannot do this in general. We should have *only* `EnsureIPFSRunning` and it should *only* send an http post to the gateway port.

**Comment by compleatang** [comment]
Don't disagree with this necessarily. We may also want `EnsureKeysRunning` ....? 

@zramsay any thoughts?

**Comment by zramsay** [comment]
`EnsureRunning` should just check that the service is running and if not, prompt user to start the service, but not actually start it for them. (while starting it for them is kinda nice, it creates too much abstraction...e.g. if `eris files put someFile` *always* starts IPFS (as it currently does), one may never need to run `eris services start ipfs`. I think that's bad

**Comment by zramsay** [comment]
#229
