### ISSUE TITLE
command helpers & error messages

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#225]
This issue is ongoing and is used for suggesting clarifications/modifications to command helpers for `eris` and all its subcommands.

If a command is confusing, please ask for clarification here. Same goes for unclear error messages
- [ ] [zr] update error/debug messages when commands change. e.g. #231

**Comment by compleatang** [comment]
closing this in favor of more specific issues now that we have done almost a full audit of these.

**Comment by zramsay** [comment]
:+1:
