### ISSUE TITLE
change default logs from "all" to something sane (50 lines?)

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#226]
**Problem summary**: long running containers give *way* too much output by default.

**Problem Identification/Recreation**: leave a chain running for 5 minutes and then run `eris chains logs CHAINNAME`

**Solution** -- change current default on logs from "all" to something sane (20-100 should be sane, even higher OK with me, but 1000's of lines isn't ideal)

**Comment by zramsay** [comment]
what about a flag for numlines to be displayed (i.e, `-n` in `git --oneline -n5`), where the default is 100

**Comment by compleatang** [comment]
we have that already. its just hidden in the tail flag (-n being reserved for container number)

**Comment by compleatang** [comment]
so its just changing the default on that flag.

**Comment by zramsay** [comment]
#227
