### ISSUE TITLE
actions package management wishlist

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-cli#23]
For the eris cli I think having contract based package management for definition files and actions etc would be hugely benefitial.

We can start simple but please put any features you think would be nice below. Anything goes.

**Comment by dennismckinnon** [comment]
- Organizational structure for multi key access to records. (Much flexibility in how we would like to structure this)
- common name for package supplied. (So you can fetch what you want without having to know supplier)
- version tags.
- additional info for retrieval methods (commit hashes. Ipfs hashes. Servers. Etc)

**Comment by compleatang** [comment]
* whitelisted protocoling... `ipfs` `edb` `address` something with respect to locations (which will be return values out of contracts). goes with additional info.
* WRT common name, i'd suggest we adopt a docker-esque naming system. where `eris services install 1234` first checks an "eris" tier of approved packages like `docker pull nginx` goes to their approved (always works) nginx imageID. then you have more particularity, so `eris services install orga/1234` would run through a simple tree structure, point to `orga` then to `1234` or whatever. this would match roughly to `docker pull eris/decerver`. We can allow folks to change the chainID of the top level chain by simply changing one line in their `etcb` service definition file :)

**Comment by dennismckinnon** [comment]
Re: common names. maybe a map from the common names list to the org/package. I would like to strive to make our package manager as inclusive as possible. And not eris centric. So the common name entries can be by anyone. And we just have some rule for how to register under common. (Maybe they can purchase via bitcoin?)

- would be nice if allowed for multiple etcb chains. (Like apt-get repositories) would requirr standard interface. (Later iteration consideration)

**Comment by compleatang** [comment]
closing this for now. let's revisit later.
