### ISSUE TITLE
CLI offers default answer but does not accept it.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-cli#232]
```shell
# eris init
The marmots have connected to Docker successfully.
They will now will install a few default services and actions for your use.

Eris Root Directory (/home/eris/.eris) already exists.
Continuing may overwrite files in:
/home/eris/.eris/services
/home/eris/.eris/actions
Do you wish to continue? (Y/n): 

The marmots will not proceed without your permission to overwrite.
Please backup your files and try again.
```

The capital `Y` in `Do you wish to continue? (Y/n): ` implies and is the convention for the default answer when pressing `Enter`.  If we don't supply it as a default then the prompt should look like `(y/n)`.

**Comment by compleatang** [comment]
Did not know that that was convention when it was capital.

**Comment by NodeGuy** [comment]
Yup, so now that I think about it another way to write it would be `(y/N)` since `N` is the default, not to keep splitting hairs.
