### ISSUE TITLE
eris init warns about overwriting files in .eris when using base image

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-cli#233]
My Dockerfile begins with `FROM eris/base:latest` which creates `/home/eris/.eris`.  Running `eris init` then produces the following warning:

```
eris@b035071d1008:/usr/src/app$ ls -a ~/.eris/
.  ..
eris@b035071d1008:/usr/src/app$ eris init
The marmots have connected to Docker successfully.
They will now will install a few default services and actions for your use.

Eris Root Directory (/home/eris/.eris) already exists.
Continuing may overwrite files in:
/home/eris/.eris/services
/home/eris/.eris/actions
Do you wish to continue? (Y/n): 
```

It would be nicer if the warning wouldn't be generated or if the base image wouldn't create the `.eris` directory, thus triggering the warning.

**Comment by compleatang** [comment]
a lot of the containers depend on the `.eris` directory to be there. 

when you `eris init` during the dockerfile build just give it the `--yes` flag and it won't require the prompt. The warning will still display though. We could potentially add a `--quiet` flag if you need to have the warning off.

**Comment by NodeGuy** [comment]
Not a big deal to me and I can use the `--yes` flag in my scripts, thanks.
