### ISSUE TITLE
Instructions on how to create transactions using chains -- pointers to docs 

### ISSUE THREAD

**Issue by hvram1** [eris-ltd/eris-cli#236]
Hi
    Was able to "create a new chain" and start the same chain . Are there instructions to conduct transactions on chains . Can there be pointers to this

**Comment by ebuchman** [comment]
from the command line, best to use https://github.com/eris-ltd/mint-client
all those tools are also available in the container, so if you don't want to install locally you could do eg. `eris chains exec mychain mintinfo status` and you should see the status of your chain, or `eris chains exec mychain mintx send --to $SOME_ADDR --amt 10 --sign --broadcast`.

If you use the `--api` flag on `eris chains new` (or if you stop the chain and use that flag on `eris chains start`) then there's a nice javascript api. There's some notes on using it here: https://github.com/eris-ltd/mint-client/wiki/Tutorial:-Mintgen-&-Erisdb#play---erisdbjs-and-eris-contractsjs

See https://github.com/eris-ltd/eris-db.js and https://github.com/eris-ltd/eris-contracts.js for more details on the javascript.

With the 0.10.3 release, we will have better instruction pipeline for making transactions and building dapps.

**Comment by hvram1** [comment]
Thanks . Is there a build script for building natively . I have cloned the
mint-client repository but do not find a build instruction

--Hari

**Comment by ebuchman** [comment]
sorry, you can just run `go install ./...` from the repo to build all the tools. `./...` is the go tools way of saying "recursively in this directory"

**Comment by hvram1** [comment]
Hi
   This is what I get

vagrant@packer-virtualbox-iso-1441376200:~/mint-client$ go install ./...
go install: no install location for directory
/home/vagrant/mint-client/mintconfig outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintdump outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintgen outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintinfo outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintkey outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintperms outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintx outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintx/core outside GOPATH
go install: no install location for directory
/home/vagrant/mint-client/mintx/random outside GOPATH

vagrant@packer-virtualbox-iso-1441376200:~/mint-client$ echo $GOPATH
/home/vagrant/goApps

**Comment by ebuchman** [comment]
yep. I take it you just used `git clone` ?

go is very particular about directory structure. you must set your `$GOPATH` to be the location for all your go code. Then you can use `go get github.com/eris-ltd/mint-client/...` for example to git clone everything to the right location (ie. `$GOPATH/src/github.com/eris-ltd/mint-client`). If you want to use `git clone` directly you have to make sure it ends up in the right path or it won't build

**Comment by hvram1** [comment]
Hi
   I managed to get the local version of clients installed but found the
docker version helpful . This is the error I get

$ eris chains ls
  SERVICE NAME      CONTAINER NAME      TYPE    CONTAINER #
PORTS
 -------------- ---------------------- ------- -------------
--------------------------------
  install        eris_chain_install_1   chain   1             1337/tcp
46656/tcp 46657/tcp


$ eris chains exec install mintinfo status
Post http://pinkpenguin.chaintest.net:46657: dial tcp: i/o timeout

**Comment by compleatang** [comment]
What's the config.toml for this chain look like?

**Comment by hvram1** [comment]
I have not changed the default . 
I compiled using the native go and got native mint-client commands working . 
I used docker inspect to get the IP Address of the "container" running the chain . I tried
 mintinfo --node-addr "http://172.17.0.5:46657" status 
and am getting
invalid character '<' looking for beginning of value
The default toml looks like this
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

moniker = "defaulttester.com"
seeds = ""
fast_sync = false
db_backend = "leveldb"
log_level = "debug"
node_laddr = "0.0.0.0:46656"
rpc_laddr = "0.0.0.0:46657"

**Comment by ebuchman** [comment]
Try this `eris chains exec mychain "mintinfo --node-addr=localhost:46657 status"`

If you want to use natively, you need to have the ports exposed on the docker container (you need to start it with the `-p` flag)

**Comment by compleatang** [comment]
closing this issue, but @hvram1 please feel free to reopen if you are still having challenges.
