### ISSUE TITLE
"exec" can't handle args which require quotes if already in quotes

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#250]
didn't manage to get this working today eg
`eris chains exec mychain "mintx name --name=hi --data=\"some data\" --amt=1000 --fee=0 ... "`

**Comment by compleatang** [comment]
since @pietv is going to be working on the `exec`'s am gonna move this over to his bucket.

**Comment by compleatang** [comment]
I think that, actually, it is related to #246 and my suspicion is that fixing *that* issue will address *this* issue.
