### ISSUE TITLE
Does `eris update` need to create a VM?

### ISSUE THREAD

**Issue by taoeffect** [eris-ltd/eris-cli#252]
```
-> % eris update
The marmots could not find a docker-machine virtual machine they could connect to.
Our marmots recommend that you have a vm dedicated to eris dev-ing.
Would you like the marmots to create a machine for you? (Y/n): n
-> % 
```

**Comment by zramsay** [comment]
yes; it's an alias to `eris init` & we want to be checking the docker connection on that

**Comment by taoeffect** [comment]
... that's odd. Aren't `update` and `init` supposed to do two very different things? I thought `update` was for updating the `eris` tools, and that only?

**Comment by zramsay** [comment]
updating the tool involves everything `init` does plus grabbing latest master branch & running `go install ./cmd/eris`. wouldn't be much of an update if it didn't check for the latest definition files

**Comment by taoeffect** [comment]
@zramsay Why is that the case? When I asked last time I thought you said that `eris update` was equivalent to the following:

```
cd $GOPATH/src/github.com/eris-ltd/eris-cli
git checkout -b develop origin/develop
git pull
go install ./cmd/eris
```

But now it seems that's not the case?

**Comment by zramsay** [comment]
sorry, needs to the `--tool` flag to update the tool (default master branch, not develop)

**Comment by taoeffect** [comment]
Maybe `eris update` should then be an alias for `eris init --tool`? As it is right now, things are confusing and the behavior is unexpected:

1. `eris help update` returns the help documentation for `eris init`.
2. Conventions have been established by other CLI tools that say `update` and `init` do very different things. I can't think of any tool that makes them behave the same.

**Comment by zramsay** [comment]
fair point. tracking in #254

**Comment by compleatang** [comment]
The answer to the question in the answer is that users have the option to us an `eris` VM or the `default` VM but a VM is required. Closing for now and moving to #254 to track separation of init and update.
