### ISSUE TITLE
Build test coverage for `perform` package

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#257]

**Comment by compleatang** [comment]
@pietv your feeling ready to get your hands dirty with some test coverage? if not, just let me know and we can reassign....

**Comment by ebuchman** [comment]
Close?

**Comment by pietv** [comment]
I'll add a few more after the merge to `rc1`

**Comment by compleatang** [comment]
@pietv can we close this issue in favor of more specific issues?

**Comment by pietv** [comment]
@compleatang sure
