### ISSUE TITLE
Move from current container name parsing paradigm to using docker labels paradigm

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#258]
To track:

- `SWARM`
- `MACHINE`
- `USER` (we have from git info)
- `TYPE`
- `TESTS`
- `NAME`
- `SERVICE_ID`
- `DATA_CONTAINER_ID`

**Comment by compleatang** [comment]
relates to #231 #170

**Comment by pietv** [comment]
@compleatang @zramsay @ebuchman  a few quick questions:

* What information would the `TESTS` label hold? 

* Why both `SERVICE_ID` and `DATA_CONTAINER_ID` and not just `ID` and `TYPE`?

* After the schema change, the container names still need to be unique, does anyone oppose using timestamps alongside eris prefix (something like: `eris-20150930-194054`). The alternatives could be using the standard Docker naming convention (person name+adjective), random numbers, sequential numbers, unix epoch (seconds).

**Comment by compleatang** [comment]
> What information would the TESTS label hold?

We should use a `TEST` label which should just be `true` or `false`, along with a `TEST_ID` field which can be a UUID for a specific run of the test suite (which is not currently used, but moving in this direction would allow that to happen).

> Why both SERVICE_ID and DATA_CONTAINER_ID and not just ID and TYPE?

Excellent idea. 

> Unique container names

I'm easy. Not sure what @ebuchman thinks, but I'd be in favor of `ipfs-UUID` or `ipfs-TIMESTAMP` paradigm. We probably don't need the eris prefix necessarily, although it may help users who move between docker porcelain and eris plumbing to have an idea of which is which. 

One thing we should add to the labeling is a `CONTAINER_NUMBER` field. This will help Ethan in his testing of multiple chain containers on he same machine to be able to track those.

**Comment by pietv** [comment]
@compleatang thanks! I like the `ipfs-UUID` bertter than `ipfs-TIMESTAMP`. The UUID is much longer than the timestamp, but it can be truncated in `eris ls` (Not in `docker ps`, though, but that's not a big issue.)

Current labels:

- `SWARM`
- `MACHINE`
- `USER` (we have from git info)
- `ID`
- `NAME`
- `TYPE`
- `SERVICE`
- `CONTAINER_NUMBER`
- `TEST`
- `TEST_ID`

**Comment by compleatang** [comment]
With the Go UUID lib you can truncate in the `-` so it becomes like 6 or 8 chars or something.

And yes, for the `ls` functions we'll want to truncate that UUID totally (if we can).

**Comment by compleatang** [comment]
Oh. @pietv one thing we need to add to the list is:

**Comment by pietv** [comment]
Gotcha.
