### ISSUE TITLE
Should I be seeing some output after eris init?

### ISSUE THREAD

**Issue by ChinoMing** [eris-ltd/eris-cli#262]
Should I be seeing some output after eris init?

```
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$ eris init
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$ eris chains new test_chain
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$ eris ls
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$ eris config
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$ eris version
```

HOST_OS = UBUNTU 14.04
GO = 1.5
DOCKER = 1.8.2
ERIS = 0.10.2

**Comment by compleatang** [comment]
Indeed, you should be. Can your try rerunning init with the debug flag so we can see what is going on?

`eris init --debug`

**Comment by ChinoMing** [comment]
Unfortunately no debug output either

```
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$ eris init --debug
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/src/github.com/eris-ltd/eris-cli/cmd/eris$
```

**Comment by compleatang** [comment]
Is the `vagrant` user added to the Docker group?

You can check this with `groups vagrant`.

If you don't see `docker` in that output then *either*:

1. All eris commands should be run as sudo (this is usually not desired); **or**
2. Add the `vagrant` user to the docker group with: `(sudo) usermod -a -G docker vagrant1

**Comment by ChinoMing** [comment]
I've added user vagrant to the docker group, but still no output.  I tried running on sudo and got command not found.

```
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/bin$ groups vagrant
vagrant : vagrant docker
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/bin$ eris init
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/bin$ eris init --debug
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/bin$ sudo eris init
sudo: eris: command not found
vagrant@vagrant-ubuntu-trusty-64:/usr/local/go/bin$
```

**Comment by compleatang** [comment]
Try logging out and back in on the shell. That should make the groups change stick.

**Comment by ChinoMing** [comment]
Works.  Thank you.
