### ISSUE TITLE
deduplicate common flags

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#271]
does it make sense to do this? seems like it would help with standardization (of helpers) & less technical debt.

**Comment by compleatang** [comment]
example?

**Comment by zramsay** [comment]
for the listing functions; the flags in `eris chains ls` and `eris services ls` are identical. there are others, like `-f` which used throughout the tool (and more, just gotta dig 'em up). basically, any flag with a common function that is used by more than one command can be deduplicated. somewhat related to #202

**Comment by zramsay** [comment]
bumping this to the queue. useful for two related reasons: ease of updating flags & consistency in flag definitions

**Comment by compleatang** [comment]
+1

**Comment by zramsay** [comment]
oooo, this'll also help with clarifying what tests to write given a set of flags, followed by #202
