### ISSUE TITLE
Unable to load the chain's config 

### ISSUE THREAD

**Issue by abueesp** [eris-ltd/eris-cli#272]
user@user-P5QL-PRO:~$ eris chains new danewchain -d
>Checking The Linux Docker Socket =>	unix:///var/run/docker.sock
Connecting to the Docker Client via =>	unix:///var/run/docker.sock
Successfully connected to Docker daemon.
Starting Setup for ChnID =>	
Data container already exists for danewchain
Chain's Data Contain Built =>	danewchain
Container destination =>	blockchains/danewchain
Local destination =>		/home/user/.eris/data/danewchain/blockchains/danewchain
Copying chain files into the correct location.
	Copying files =>	/home/user/.eris/blockchains/default:/home/user/.eris/data/danewchain/blockchains/danewchain
Copying Files into DataCont =>	/home/user/.eris/data/danewchain/blockchains/danewchain:blockchains/danewchain
Found Data container =>		danewchain:danewchain and 1:1
Importing FROM =>		/home/user/.eris/data/danewchain
Importing TO =>			/home/eris/.eris
Error on setupChain =>		Could not import the data container.
Tried with docker --rm =>	exit status 1
Tried without docker --rm =>	exit status 1
Cleaning up...
Loading Chain Definition =>	danewchain:1
Chain Defaults Set. Image =>	eris/erisdb:0.10.3
Tragic! Our marmots encountered an error during setupChain for eris_chain_danewchain_1.
They also failed to cleanup after themselves (remove containers) due to another error.
First error =>			Could not import the data container.
Tried with docker --rm =>	exit status 1
Tried without docker --rm =>	exit status 1
Cleanup error =>		Unable to load the chain's config for danewchain in /home/user/.eris/blockchains.
Check your known chains with:
eris chains known
user@user-P5QL-PRO:~$ go env
> GOARCH="386"
GOBIN=""
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/gopath"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_386"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

I tried 
- Deleting .eris and then eris init
- Reinstall eris
- Reinstall go and docker
- Using root
but I got the same error.

update: it looks as if it wasn't 32 bits compatible by reason of lxc-docker is not.

**Comment by abueesp** [comment]
It looks as if it wasn't i386 compatible by reason of lxc-docker is not.

**Comment by compleatang** [comment]
Yes. That is correct. Docker will not run on 32bit architecture at this time. I will add this to the getting started instructions so that it is clear moving forward for other users.

**Comment by abueesp** [comment]
You can also run that problematic lxc-docker on 32bit architecture doing this

>sudo apt-get install linux-image-extra-'uname -r' linux-image-generic-lts-trusty aptitude apparmor
sudo reboot
sudo aptitude install lxc-docker

Please note the `uname -r`

After this, though docker daemon and functionalities looks they are running correctly on other tasks,  `eris chains new testchain -d` continues giving an error, but it is different on this case:
>Checking The Linux Docker Socket =>	unix:///var/run/docker.sock
Connecting to the Docker Client via =>	unix:///var/run/docker.sock`
Successfully connected to Docker daemon.
Starting Setup for ChnID =>	
Creating Data Container for =>	testchain
Parsing Containers =>		eris_data_testchain_1:true
ALL: true
	container: eris/data:latest [/eris_data_chaaaaain_1]
	container: eris/data:latest [/eris_data_danew_1]
	container: eris/data:latest [/eris_data_danewchain_1]
	container: eris/data:latest [/eris_data_mychain_1]
	container: eris/data:latest [/eris_data_test_chain_1]
No match =>			eris_data_testchain_1:[/eris_data_chaaaaain_1]
No match =>			eris_data_testchain_1:[/eris_data_danew_1]
No match =>			eris_data_testchain_1:[/eris_data_danewchain_1]
No match =>			eris_data_testchain_1:[/eris_data_mychain_1]
No match =>			eris_data_testchain_1:[/eris_data_test_chain_1]
Container Not Found =>		eris_data_testchain_1
Data Container ID =>		e5b9f65a83f951eb4ce84ce884cffb8fe0fea23f4024f90f7f751f67dc8cc37a
Chain's Data Contain Built =>	testchain
Container destination =>	blockchains/testchain
Local destination =>		/home/user/.eris/data/testchain/blockchains/testchain
Copying chain files into the correct location.
	Copying files =>	/home/user/.eris/blockchains/default:/home/user/.eris/data/testchain/blockchains/testchain
Copying Files into DataCont =>	/home/user/.eris/data/testchain/blockchains/testchain:blockchains/testchain
Found Data container =>		testchain:testchain and 1:1
Importing FROM =>		/home/user/.eris/data/testchain
Importing TO =>			/home/eris/.eris
Error on setupChain =>		Could not import the data container.
Tried with docker --rm =>	exit status 1
Tried without docker --rm =>	exit status 1
Cleaning up...
Loading Chain Definition =>	testchain:1
Chain Defaults Set. Image =>	eris/erisdb:0.10.3
Tragic! Our marmots encountered an error during setupChain for eris_chain_testchain_1.
They also failed to cleanup after themselves (remove containers) due to another error.
First error =>			Could not import the data container.
Tried with docker --rm =>	exit status 1
Tried without docker --rm =>	exit status 1
Cleanup error =>		Unable to load the chain's config for testchain in /home/user/.eris/blockchains.'

Any ideas?
Cheers.

**Comment by compleatang** [comment]
@abueesp Zach is running around just now but we will try to have an answer tonight.

**Comment by ebuchman** [comment]
@abueesp, can we see the output of `docker version` please?
