### ISSUE TITLE
`--machine` flag not properly routing to remote machine if local machine in scope via env vars

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#280]
**expected behaviour** -- the flag should override env vars.

**explanation of problem** -- on osx and windows users will generally have the `eris` machine in scope which will be local to their machine. the most likely use here of the `--machine` flag is when they want to perform an action against a remote machine, ala `eris chains new idiaminchain --machine iniaminchain-val0` and only for that action connect into the remote machine, otherwise remaining to use the local machine.

**Comment by compleatang** [comment]
@zramsay since you're working on the init tests and this functionality is related (and since you have a mac) I'm gonna assign this to you. Let me know if you don't have bandwidth. I'm pretty sure the sequencing in docker_client.go just needs to be tweaked accordingly.

**Comment by zramsay** [comment]
may just need to run `eval $(docker-machine env my_machine)` in background. related to #204

**Comment by compleatang** [comment]
different issues. let me clarify a bit. for the purposes of the explanation, let's assume User is on Linux box.

let's say that the user has done `eval $(docker-machine env machine_1)` so that the shell has populated the proper env vars for `machine_1`. that would put that machine "in scope" (my terminology). 

since the proper env vars are populated then in PreRun, eris will connect to docker via [here](https://github.com/eris-ltd/eris-cli/blob/develop/util/docker_client.go#L48) then [here](https://github.com/eris-ltd/eris-cli/blob/develop/util/docker_client.go#L165) then [here](https://github.com/eris-ltd/eris-cli/blob/develop/util/docker_client.go#L168). In that sequence (which was built for speed) the env vars will be the only thing used and it will never try to connect into the named machine. 

What I think we need to do is add a small check around that return in L168 to not return if the `machName != "eris" || machName != "default"` which would then go through the remainder of the `getMachineDeets` function for the named machine instead of simply returning because the env vars have been populated. Am adding that `||` because the way that the docker toolbox install works it makes that default box which we can connect into if osx/windows users do not want to create an eris box during the `eris init` sequence.
