### ISSUE TITLE
eris update should be able to migrate deprecated ~/.eris paths

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#281]
**NOTICE** -- change in default directories.

```
~/.eris/dapps -> ~/.eris/apps
~/.eris/blockchains -> ~/.eris/chains
```

Simplify cognitive load for onboarding && harmonize naming scheme.

This is getting pushed as part of the contractsTest branch. 

- [x] We also need a way to add a deprecated dirs constant string slice that both init and update can read. [zr] This is handled with updates to `/common`. Branch for this issue (`migrate_dirs`) has updated godeps that tracks branch of same name in `/common`.

Making this issue here as for notification, more importantly we need to have `eris update` migrate these directories without asking should they exist. 

- [x] Init on the other hand needs to give users an option to migrate should they exist. [zr] `--prompt=true`

This will ease things when we migrate paths within the ~/.eris domain.

**NOTE** -- this is going to break quite a few scripts so we need to be careful about doing this.
- [x] [zr] write a test
- [x] [zr] rename `BlockchainsPath` -> `ChainsPath` etc

**Comment by zramsay** [comment]
blocking on tests failing non-deterministically (about 1/8 tries). godeps track branch `migrate_dirs` in `/common` where things are done slightly differently than recent merges for this migration.
