### ISSUE TITLE
chain_id can't have period

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#289]
also, allow containers to be named differently than the chain id

**Comment by ebuchman** [comment]
problem seems to be the chain's root directory doesnt get created since its named the same as the chain id and the period somehow throws it off. maybe we should just call the directory "chain" since so far we have no use case for multiple chain dirs in a single data container so theres no reason to name it the chain id

**Comment by ebuchman** [comment]
ok I'm totally off here because `tendermint_testnet_11.c` doesn't work but `tendermint_testnet_11.d` does. yay

**Comment by ebuchman** [comment]
ok. this isn't an issue. but I'll tell you what is. things sticking around in `~/.eris/data` and making me think things like this are an issue because I forgot to clear that data dir.

**Comment by compleatang** [comment]
:)
