### ISSUE TITLE
expose eris-keys functions as `eris keys` 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#294]
- [x] gen
- [ ] lock
- [ ] unlock
- [ ] name
- [ ] ls (note this doesn't currently exist in eris-keys)
- [x] pub (what does this do....?) [zr] take --addr/name & returns pubkey
- [ ] import
- [x] export
- [x] [zr] `mintkey mint` -> `eris keys convert` or something

**Comment by zramsay** [comment]
that's a lot of functions to expose - maybe limit it to just a few basic ones to begin with

**Comment by compleatang** [comment]
agree. that was just meant as the exhaustive list of available commands. please do curate.

**Comment by ebuchman** [comment]
Close?

**Comment by zramsay** [comment]
ye
