### ISSUE TITLE
chains|services exec --publish

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#300]
**Problem** -- chains|services exec have (by default) turned their HostConfig exposed ports off. This is a fine default, but it should be overwritten by `--publish`. We need to randomize these ports as exec containers inherit the ports of the service container. 

**Solution** -- export --publish logic from start, etc. to exec.

Relates to flag deduplication.

**Comment by pietv** [comment]
Does the current `--publish` logic allows randomization of ports for `eris chain` and `eris service`?

Tried starting a service:

```
$ eris services start -p eth

$ docker port eris_service_eth_1
8545/tcp -> 0.0.0.0:8545
30303/tcp -> 0.0.0.0:30303

$ grep ports ~/.eris/services/eth.toml 
ports = [ "8545:8545/tcp", "30303:30303/tcp" ]
```
And then another service (fail):

```
$ eris services start -p eth -n 2
API error (500): Cannot start container be53ffb8b5dba3d48136204998109922ad61a8310b1737b8074ebcfbd8ee5af1: Bind for 0.0.0.0:30303 failed: port is already allocated
```

I'd like making a small amendment to the`perform.configureServiceContainer()` function, something like:

```
if ops.PublishAllPorts {
   // Do nothing.
}
```

This makes Docker do the randomization:

```
$ eris services start -p eth
$ docker port eris_service_eth_1
30303/tcp -> 0.0.0.0:32784
8545/tcp -> 0.0.0.0:32785
$ eris services stop eth

$ eris services start -p eth
$ docker port eris_service_eth_1
30303/tcp -> 0.0.0.0:32786
8545/tcp -> 0.0.0.0:32787

$ eris services start -p tinydns
$ docker port eris_service_tinydns_1
53/tcp -> 0.0.0.0:32792
53/udp -> 0.0.0.0:32772
```

But that will change the behaviour of `chain|service start` as well as `chain|service exec` commands.

**Comment by ebuchman** [comment]
looks like you're right, the logic in configureServiceContainer is wrong in that it fails to randomize if the bindings are specified in the service definition file. I suppose the --publish flag should work regardless and override any specification in the service definition file

**Comment by compleatang** [comment]
++ generally speaking flags should always override defFiles. 

I'd agree with you both that the default behaviour of `--publish` (for both `start` and `exec`) should be to:

* export ports
* randomize exported ports

Should users not want to have randomized ports (essentially for any blockchain they want to be able to sync with the network) then they will have to *not* use `--publish` and then "manually" export the ports via the service|chain definition file.

Otherwise these two (exported and/or `publish`ed ports) will conflict as Peter has noted.

**Comment by pietv** [comment]
@ebuchman, @compleatang thanks! this makes perfect sense now.

**Comment by compleatang** [comment]
:+1:
