### ISSUE TITLE
write test for genesis file being copied into container

### ISSUE THREAD

**Issue by crainbf** [eris-ltd/eris-cli#311]
mintgen -> makes genesis file
eris chains plop chainName genesis -> matches rpc
cat ~/.eris/blockchains/chainName/genesis.json -> doesn't match

Has something to do with copying genesis file into container.

**Comment by zramsay** [comment]
func `resolveGenesisfile()` exists but isn't actually used methink is the problem

**Comment by compleatang** [comment]
have observed this occasionally on 0.10.3 but not on 0.10.4.

@zramsay best way to control for this is to add a test into `chains/chains_test.go`

**Comment by ebuchman** [comment]
I can't replicate this on 0.10.3/master or on latest 0.10.4/contractsTest

**Comment by compleatang** [comment]
we have numerous tests for this already. going to close this for now.
