### ISSUE TITLE
adopt host environment flag for services new and chains new

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#33]
this will simplify the process for some DNS type stuff and other platform level configuration requirements.

**Comment by compleatang** [comment]
`--use-host-env` flag to be added to `chains new`

**Comment by ebuchman** [comment]
so what does this do? copy in some config files form the host?

**Comment by compleatang** [comment]
no, it would use, e.g., `TM_ROOT` if set in the host environment... 

the issue is mostly about addressing quick remote establishment and chain spinup.

**Comment by compleatang** [comment]
it may be better for quick chain establishment to just pull chainDef out of IPFS and roll but anyway... we need a better handle on remotes before really worrying about this issue.

**Comment by compleatang** [comment]
this is a dumb idea.
