### ISSUE TITLE
`eris chains make name type` -> a better wrapper for mintgen lib 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#332]
- [ ] `type`'s
  - known (give it two csv files from the host; `--accounts` `--validators` as separate, required flags; or give it a dir)
  - random
  - manual (walk thru)
- [ ] remove `--csv` flags from new
- [ ] remove the csv stuff (and all chain creation logic) from ecm

`manual type`:

* root group; how many?
* participant group; how many?
* admins group: how many?
* validators group: how many?
* make your own group; how many?
* another?

**Comment by zramsay** [comment]
close? `eris-chainmaker`
