### ISSUE TITLE
`publish` -> `randomize-ports` for chains exec|start

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#338]
Now that we have moved to publishing the ports by default for chains, we should consider renaming this flag to random (at least as far as user facing interaction) to reduce cognitive load for users who may not understand all of the vagaries of ports.

Thoughts @eris-ltd/team-platform ..?

**Comment by zramsay** [comment]
good idea. agree that it's confusing. will mull over it

**Comment by NodeGuy** [comment]
I don't understand the purpose of renaming it to `random`.  What does that mean?

**Comment by compleatang** [comment]
Could also be `random-ports` if we wanted to be more verbose about it.

**Comment by pietv** [comment]
`publish` came from Docker which some users may be familiar about:

```
$  docker run --help|grep -i publish
  -P, --publish-all=false         Publish all exposed ports to random ports
  -p, --publish=[]                Publish a container's port(s) to the host
```

I like it more verbose too, like `--random-ports` or `--randomize-ports`. I agree with @NodeGuy, `random` sounds no clearer than `publish`.

**Comment by zramsay** [comment]
`--randomize-ports` has my vote

**Comment by NodeGuy** [comment]
What's the use case for randomizing ports?

**Comment by compleatang** [comment]
starting more than one chain is the most obvious.

**Comment by compleatang** [comment]
Let's stick with docker conventions here. We can just be more effective in our communication. Closing for now.
