### ISSUE TITLE
eris services ports bug and improvement

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#342]
* Fix the issue with the ports command panic when displaying an exposed port: 

```
$ eris services ports keys 4767

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/eris-ltd/eris-cli/util.PrintPortMappings(0xc820246900, 0x40, 0xc82013c230, 0x1, 0x1, 0x0, 0x0)
	/Users/peter/src/github.com/eris-ltd/eris-cli/util/container_stats.go:128 +0x480
...
```

* Make `eris services ports NAME` and `eris chains ports NAME` display all ports (an alias to `eris services inspect NAME NetworkSettings.Ports`).

**Comment by compleatang** [comment]
:+1:

**Comment by compleatang** [comment]
is this related to... https://github.com/fsouza/go-dockerclient/commit/923cb3a7bbeff92e840e6a7d41228cdfedb1e9b5 (which is not currently included in our godep-ed version ... which is at commit: ef41029 )

**Comment by pietv** [comment]
no, this is just a `if {} else {}` bug. won't be necessary to update godeps.
