### ISSUE TITLE
check that docker version >= 1.8

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#347]
because things are wonky otherwise...will prevent a lot of user frustration
- add a check in `PersistentPreRun` in `/command/eris.go`

**Comment by compleatang** [comment]
You mean 1.8? This is going to be a moving target for a while as docker continues to develop rapidly. We probably need a way to parameterize this and dump that parameter into our docs as well as into that check in PreRun (which is a good idea).

**Comment by zramsay** [comment]
clearly needed now... @ceehart

**Comment by compleatang** [comment]
Let's try to get this into 0.11 - official

**Comment by zramsay** [comment]
closed by #385
