### ISSUE TITLE
additional features for keys

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#356]
see #294

**Comment by zramsay** [comment]
we might want to deprecate some of the keys commands now that we have `chains make`. need to mull on it

**Comment by vallard** [comment]
perhaps a way to export all keys in a chain instead of having to cycle through them individually

**Comment by compleatang** [comment]
Nice one-liner :) (always love a bit of bash-ing). But yes this is a great idea!

**Comment by zramsay** [comment]
closing for now. we can re-visit individual commands as the need arises

**Comment by zramsay** [comment]
btw @vallard `--all` has been implemented for `eris keys import/export`

**Comment by rguikers** [comment]
Maybe a possibility to import a private key in the container?. currently using : 
eris services exec keys "eris-keys import <privkey> --no-pass"
Using this for testing against a genesis.json with fixed accounts.
