### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#361]
This is a proposal to use the  `github.com/Sirupsen/logrus` logging library in place of the current standard `log` library.

The reason of this is it will allow to get rid of many tab and newline characters from our current log messages and it is also fit for current logging Eris style (log message + highlighted argument).

I've tried these logging libraries: `github.com/golang/glog`, `github.com/cihub/seelog`,
and `code.google.com/p/log4go` and preferred `logrus` because it is more mature and flexible.

These are the benefits of using `logrus`:

* It allows for a custom formatter which could be written from scratch. So it allows for absolute control.
* It allows for highlighting specific arguments (or a bunch of arguments). The most typical Eris log message looks like this (a log message and a highlighted argument) for which `logrus` is well suited:

  ```
     logger.Infoln("Building the Services Group =>\t%v\n", do.Operations.Args)
  ```

* It's already within our Godeps. No need to update.

* It looks more mature than the close competitors.

This snippet below is a faithful copy of `eris service start tinydns` debug output and how it will look like with the `logrus` library. The snippet is runnable:

https://gist.github.com/pietv/caca08e83c1100925512

![logrus output](http://i.imgur.com/97KGyF2.jpg)

Please @compleatang, @zramsay, @ebuchman guys tell what do you think?

**Comment by compleatang** [comment]
:+1:

**Comment by zramsay** [comment]
nice. are the pretty colours the logger or your shell? ... if the former, that would tackle #44

**Comment by pietv** [comment]
great! :smile: the yellow is actually the bold attribute; the dark grey is the colour. (could be colours or attributes, doesn't matter.)

**Comment by compleatang** [comment]
can't wait for this :)
