### ISSUE TITLE
add logsrotate service as chains dependency to deal with long log output

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#365]
have https://github.com/tutumcloud/logrotate as a dependency? or write to papertrail? we should also clarify to users what's going on there ... I had a 20G droplet filled up in a ~day. maybe we should also turn down the log level on the default `config.toml`

**Comment by compleatang** [comment]
I like the idea of logrotate as a dependency because it is super helpful. Users could change to dump to papertrail if they really wanted to.

**Comment by compleatang** [comment]
For eris:paas we actually start logrotate service before we deploy the chains to hedge against droplet overload. This would be a good practice until we close this issue.

**Comment by zramsay** [comment]
dependency it is. this'll be a time saver for sure.

**Comment by zramsay** [comment]
decided against a default dependency because i think there'll be a lot of variation in preference...and it's also an extra container => cognitive overload
