### ISSUE TITLE
add --status flag to listing func to check if images need to be pulled

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#37]

**Comment by compleatang** [comment]
will require some direct interaction with docker hub probably

**Comment by compleatang** [comment]
perhaps using something like [watchtower](https://labs.ctl.io/watchtower-automatic-updates-for-docker-containers/) could do this for us.

**Comment by compleatang** [comment]
At this time there is no actual way to do this without pulling the images. `update` will, by default, pull images and is the hack to get at this until we can pull imageIDs from a docker hub API and compare those against the imageIDs available locally (the only real way to do this status). Am gonna close this for now and when the functionality is added to the docker hub API then we can revisit another time.
