### ISSUE TITLE
listing functions should loop through all the docker-machines

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#371]
probably with a flag. this'll block on having a stable docker-machine API but will be a useful feature in the future

**Comment by compleatang** [comment]
related to #258  (as the current naming scheme doesn't fully utilize the swarm / machine feature set). see also #237 (which is deprecated in favor of 258).

**Comment by zramsay** [comment]
using https://godoc.org/github.com/docker/machine/libmachine/host

**Comment by zramsay** [comment]
closing in favour of #376
