### ISSUE TITLE
godeps => go vendor experiment

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#374]
for all repos incl this one:
- /common
- /eris-keys
- /mint-client
- /eris-pm
- /eris-db
- /mindy
- /toadserver
- /eth-client

**Comment by zramsay** [comment]
alternatively:
https://github.com/whyrusleeping/gx

**Comment by compleatang** [comment]
:+1: I'd love to support gx.

**Comment by compleatang** [comment]
glide for the win!
