### ISSUE TITLE
services/chains update should compare local vs. latest image & prompt pull if latest is newer

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#375]
since pulling the latest image from quay by default is being turned off as part of #271

**Comment by zramsay** [comment]
this could help with ensuring the right versioned images are used for tests too

**Comment by compleatang** [comment]
for the record, we'd have to build our own API access to quay.io to query the current docker image ID (which may or may not be portable to other docker hubs and may or may not actually be exposed by their API). in general the only way to do this using the standard docker hub API (v. 2) is to actually pull the image. 

think the better way here is just to have the `--pull` flag on services|chains update and to leave it at that.

**Comment by zramsay** [comment]
:+1:
