### ISSUE TITLE
unexpected crash

### ISSUE THREAD

**Issue by panislepickova** [eris-ltd/eris-cli#379]
I went through all the processes described on erisindustries.com, and yet when Eris starts, it only pulls in recent changes to .eris/services and .eris/actions, then crashes unexpectedly.
I am running Windows 8.1 on amd64 architecture, and using PeaZip instead of BsdTar, which is incompatible with Windows 8 & newer.

![image](https://cloud.githubusercontent.com/assets/16142327/11665454/cfb2abe2-9de7-11e5-995b-a36ff7ee787d.png)

**Comment by zramsay** [comment]
looks like it hangs rather than crashing. what's your `docker version` ?

**Comment by zramsay** [comment]
@panislepickova also, did you install eris via binary or with go? `eris init` requires `git` to be installed and if it isn't, the `--skip-pull` flag is required

**Comment by panislepickova** [comment]
1.9.1
And the command line window closes immediately after printing "The marmots have everything se up for you...", so it is not a hang. I took the screenshot in fraction of a second. :-D
Eris did not even write any log which would make it easier to diagnose the problem. :-/

**Comment by zramsay** [comment]
you can run `eris init -d` to get debug log output

**Comment by compleatang** [comment]
Panis, we don't write a log, but you can always pipe output to a file with the debug flag on as Zach mentioned. Well, I think you can do that on Windows.

**Comment by panislepickova** [comment]
Yes, I have Git installed.
When I try to pipe output, the resulting text file is empty, so here is a printscreen: 
![image](https://cloud.githubusercontent.com/assets/16142327/11667899/b24045f8-9df4-11e5-8cc1-6bdec8a2dc0a.png)I wonder if there is anybody able to run Eris on Windows to advise me.

**Comment by compleatang** [comment]
Great. That is all the expected output for `eris init`. Are you able to see the help screen by typing `eris` ...?

**Comment by panislepickova** [comment]
I am not able to see anything because it always crashes right after saying "...nothing to migrate"

**Comment by compleatang** [comment]
Does it not return you to the command line prompt? That is all that should be happening when running the eris command line tool using the init functionality; so we're a bit confused what you mean by "crashes" in this instance. We do have some Windows users and are happy to help through this, just trying to understand the issues here is all.

**Comment by panislepickova** [comment]
The command line (cmd.exe) crashes, falls, the window just closes. Maybe some mistake has been made during an installation, but it seems weird to me that Eris starts running normally (I would expect it to not run at all or not performing any of the first steps if it was not installed properly).

What tar tool for Windows are the other users using?

**Comment by zramsay** [comment]
Have you installed docker via the toolbox? Was the terminal launched by clicking on the `Docker Quickstart Terminal` icon?
![screen shot 2015-09-08 at 12 58 39 pm](https://cloud.githubusercontent.com/assets/8304391/11668819/2cf83b9e-9dc7-11e5-8409-2e1d143c63f7.png)

**Comment by zramsay** [comment]
the tar tool should not matter for the latest version. was `eris` installed via go or the binary?

**Comment by panislepickova** [comment]
Yes and yes. Eris was installed via go.

**Comment by panislepickova** [comment]
Problem solved! :-)
If you are using Windows 8.1 x64 & newer, you need to use ``/k`` when starting Eris for the first time.

**Comment by zramsay** [comment]
:+1: thanks for the bug report and solution :)
