### ISSUE TITLE
eris chains start thinks chain is already started

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-cli#397]
Hi,

Following sequence to reproduce :

```
eris chains new test
```
Provides a running chain :
```
eris chains ls
  CHAINS NAME   TYPE    RUNNING    CONTAINER NAME     CONTAINER #                                     PORTS
 ------------- ------- --------- ------------------- ------------- ----------------------------------------------------------------------------
  test          chain   Yes       eris_chain_test_1   1             0.0.0.0:1337->1337/tcp 0.0.0.0:46656->46656/tcp 0.0.0.0:46657->46657/tcp
  default               No                            0
```
Stopping the chain:
```
eris chains stop test
eris chains ls
  CHAINS NAME   TYPE    RUNNING    CONTAINER NAME     CONTAINER #   PORTS
 ------------- ------- --------- ------------------- ------------- -------
  test          chain   No        eris_chain_test_1   1
  default               No                            0
  test                  No                            0
```
Now again starting the chain (with debug) results in (last few lines in log):
```
eris chains start test -d

Starting Service =>		test
Parsing Containers =>		eris_chain_test_1:false
Container Found =>		eris_chain_test_1
Service already Started. Skipping.
	Service Name=>		test

```
Log says it is starting a service (although it is a chain, but that's not an issue), but thinks that service is already running.
Starting the chain with ```docker start test``` is starting the chain as expected.

**Comment by pietv** [comment]
Hi Rob, thanks for reporting this. 

I can confirm this is reproducible on latest `develop` branch on Mac, Docker v1.9.1. `eris chains start` has a bug.

The log saying it starts a service is a misnomer, not an issue. Probably worth renaming.

I'll update you on this. For now, can you do away with `docker start eris_chain_test_1` and similar?

**Comment by rguikers** [comment]
Sure, using the alternative for now. Thanks for the update..

**Comment by pietv** [comment]
Hi Rob, the fix for this issue is now merged in the `develop` branch.

Please, feel free to update and try it whenever you feel like it. Thanks.

**Comment by compleatang** [comment]
to use a specific branch with eris update, use `eris update --branch develop` or whatever branch you like. **N.B.** this requires git/go to be installed on your machine.

**Comment by rguikers** [comment]
Great, thanks!
