### ISSUE TITLE
Move away from using `~/.eris/data`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#400]
**Problem** -- `~/.eris/data` is a potential source of confusion to users.

**Proposed Fix 1** -- the scratch directory is pretty self-explanatory and already is used by other eris tools as a centralized cache point. eris-cli follow this paradigm, which would have the added benefit of removing a possible source of confusion. Proposal 1 would change the ~/.eris/data to ~/.eris/scratch/data-containers (or something along those lines, am not married to `data-containers`). This fix (versus Fix 2) has the benefit of being much more simple and would keep to the current paradigm.

**Proposed Fix 2** -- do away with a caching directory at all. This would be a much larger change as we will need to make sure we *require* a source flag to be sent with any data operation. There is also some funkiness that happens when we *dump* an ~/.eris directory to the host machine because there is a bunch of latent folders which get pulled in. We currently use a temp directory to handle most of this, but there is still some challenges here because we could end up dumping a whole bunch of empty directories into the destination on data export.

Between the two, my vote is to utilize `Fix 1` in the short term and perhaps move to `Fix 2` later.

**Comment by compleatang** [comment]
have added this to 0.11, but that should only happen if we have consensus around using `Fix 1`. If consensus points to `Fix 2` then we should recategorize to 0.12.

**Comment by zramsay** [comment]
my vote is Fix 2. The `data import/export` commands have already been refactored to allow both src/dest on each cmd (but this feature is currently commented out). Would just need to add the check for those flags. I never been a huge fan of the opiniated-ness of data import/export & this would free it up.

**Comment by compleatang** [comment]
k. that fix seems easier than i had imagined. @pietv @ebuchman thoughts?

**Comment by pietv** [comment]
I like the Fix 2 better too. No need to have extra concepts to remember, etc.

**Comment by zramsay** [comment]
Solution (after playing a bit), does all these things: 1) use `~/.eris/scratch/data-containers` for copying in and out of data containers under the hood, 2) abolish the use `~/.eris/data/` completely (there's no need for it), 3) require both `--src` and `--dest` flags on each `data import/export`

**Comment by zramsay** [comment]
closed by #412
