### ISSUE TITLE
Fast track `eris keys ls`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#401]
**Problem** -- with the increased usage of eris keys (which is great and needed), users need to be able to have an understanding of what keys are actually inside their keys data container. I find myself more frequently needing this command than any of the current `eris keys` commands.

**Proposed Fix** -- add `eris keys ls` which maps to `eris services exec keys "ls /home/eris/.eris/keys/data"`

**Comment by zramsay** [comment]
we have `eris actions do keys list` which works out of the box

**Comment by zramsay** [comment]
tracking in #376

**Comment by compleatang** [comment]
perfect. forgot about that!
