### ISSUE TITLE
Allow default docker-machine created to be on a different backend

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#402]
virtualbox does not work on Travis due to some way they do their virtualization of OSX boxes. 

we should expose the driver so we can say `eris init --yes --pull --driver amazonec2` and be all set up if the env vars are set.

for now we don't need to do an env var check, but we will need to clear this up.

https://github.com/eris-ltd/eris-cli/blob/develop/util/docker_client.go#L106

**Comment by zramsay** [comment]
related to #372

**Comment by compleatang** [comment]
this is purely handled by env vars. closing.
