### ISSUE TITLE
Eris chains should only handle permissioned chains 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#41]
Proposal. Chains should get more opinionated. 

As in only work with permissioned mint either via the mint container (built to expose the core mint RPC, useful for cli interaction) or the erisdb container (heavier,  includes etcb, and exposes andreas' rest and stream apis, useful for running apps). 

As the persistence layer is the same, for both the erisdb and mint images, it's really just swapping out data containers to have a different "interface" to the same data, when we're talking eris:db/raw, permissioned mint... 

Why more opinionated? The new and fetch functions are very particular to our method of a multiplicity of chains.

What this means is that eth, etcb, btc, would be ran as services rather than chains. Service definition files for the various testnets can be built easier than trying to shove pub chains into the complex, opinionated infrastructure we're building to support permissioned chains.

**Comment by ebuchman** [comment]
done.
