### ISSUE TITLE
when package.json contains a space replace with underscore for contracts service/data container name

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#410]
**Problem** -- a package.json name field which is `idis app` (valid in node/npm land) is not usable out of the box with eris. It will yield the following error:

```
Error creating data container API error (500): Invalid container name (eris_data_idis app_tmp_deploy_1), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```

**Solution** -- add a simple filter to the `AppName` to replace any spaces with underscores.

**Comment by zramsay** [comment]
note: this is also true for `docker-machine`
