### ISSUE TITLE
Error executing 'eris actions do keys list' on Windows

### ISSUE THREAD

**Issue by alexandrev** [eris-ltd/eris-cli#416]
I'm getting this error when I try to execute the key list on Windows

```
PS C:\Users\alexa\.eris\apps> eris actions do keys list
error running command (exit status 1): Unable to load the service's config for keys in C:\/.eris/services.
Check your known services with:
eris services known
```

Version:
```
PS C:\Users\alexa\.eris\apps> eris version
Eris CLI Version: 0.11.0
```

**Comment by compleatang** [comment]
Does

```
eris services start keys
```

work ok?

**Comment by alexandrev** [comment]
Yeah, that command works as expected.

```
PS C:\Users\alexa\.eris\apps\idi> eris services start keys
PS C:\Users\alexa\.eris\apps\idi> eris services ls
  SERVICES NAME    TYPE     RUNNING     CONTAINER NAME      CONTAINER #     PORTS
 --------------- --------- --------- --------------------- ------------- ------------
  keys            service   Yes       eris_service_keys_1   1             4767/tcp
  btcd                      No                              0
  do_not_use                No                              0
  eth                       No                              0
  ipfs                      No                              0
  mindy                     No                              0
  mint                      No                              0
  openbazaar                No                              0
  tinydns                   No                              0
  toadserver                No                              0
```

**Comment by compleatang** [comment]
OK. The actions tests now pass on windows (there are still some failing tests on windows, but actions are now passing). Let me know if it doesn't work. Actions are pretty assumptive but I hope we can get them to work.

**Comment by alexandrev** [comment]
I'm getting the same error:

```
PS C:\Users\alexa> eris actions do keys list
error running command (exit status 1): Unable to load the service's config for keys in C:\/.eris/services.
Check your known services with:
eris services known
```

**Comment by compleatang** [comment]
what commit are you on?

**Comment by alexandrev** [comment]
Same branch as before:

```
eris update --branch winConFix 
```

**Comment by compleatang** [comment]
I realized when I was vetting all these paths that on the commit which you originally installed that update command won't work. You'll probably need to cd into the eris-cli directory, `git pull develop` and `go install ./cmd/eris`. We've merged in a bunch of fixes for windows stuff today, including what should fix that update command going forward.

**Comment by alexandrev** [comment]
Same error as well

```
PS D:\Projects\GitHub\eris-cli> eris version
Eris CLI Version: 0.11.0
PS D:\Projects\GitHub\eris-cli> eris actions do keys list
error running command (exit status 1): Unable to load the service's config for keys in C:\/.eris/services.
Check your known services with:
eris services known

PS D:\Projects\GitHub\eris-cli> eris actions do keys list --debug
Connecting to the Docker Client via =>  tcp://192.168.99.100:2376:C:\Users\alexa\.docker\machine\machines\default
Checking Details via Docker-Machine =>  eris
Connecting to the Docker Client via =>  tcp://192.168.99.100:2376:C:\Users\alexa\.docker\machine\machines\default
Connecting to the Docker Client via TLS.
        URL =>                  tcp://192.168.99.100:2376
        Docker Cert Path =>     C:\Users\alexa\.docker\machine\machines\default
Connected over TLS.
Successfully connected to Docker daemon.
Setting IPFS Host
Set ERIS_IPFS_HOST to =>        http://192.168.99.100
Performing Action =>            [keys list]
CLI Chain to turn on =>
CLI Services to turn on =>      []
Reading action def file =>      keys_list
Pulling out the named variables passed to the command line.
Args culled =>                  []
Args not culled =>              [keys list]
Successfully parsed the named variables passed to the command line.
Read action definition file =>  keys_list
Args to add to the steps =>     map[]
Action definition file successfully read.
Services to start =>            [keys list]
No services to start.
No chain to start.
Performing Action =>            keys list.
Directory for action =>         D:\Projects\GitHub\eris-cli
Performing Step 1 =>            sh -c eris services exec keys ls /home/eris/.eris/keys/data
error running command (exit status 1): Unable to load the service's config for keys in C:\/.eris/services.
Check your known services with:
eris services known

PS D:\Projects\GitHub\eris-cli>
```

**Comment by zramsay** [comment]
try `eris update --branch develop` it should have the fix

**Comment by alexandrev** [comment]
As you can see I see no change:

```
PS D:\Projects\GitHub\eris-cli> eris update --branch develop
The marmots have updated eris successfully.
Eris CLI Version: 0.11.0

PS D:\Projects\GitHub\eris-cli> eris actions do keys list --debug
Getting connection details from environment
                                    cert path=C:\Users\alexa\.docker\machine\machines\default
                                         host=tcp://192.168.99.100:2376
Getting connection details from Docker Machine
                                      machine=eris
                                    cert path=C:\Users\alexa\.docker\machine\machines\default
                                         host=tcp://192.168.99.100:2376
Connecting to Docker via TLS        cert path=C:\Users\alexa\.docker\machine\machines\default
                                         host=tcp://192.168.99.100:2376
Connected via TLS
Successfully connected to Docker daemon
Setting ERIS_IPFS_HOST                    url=http://192.168.99.100
Performing action                       chain=
                                     services=[]
Reading action definition file           file=keys_list
Pulling out named variables
Successfully parsed named variables
                                       culled=[]
                                   not culled=[keys list]
Preparing to read action definition file
                                         file=keys_list
                                         drop=map[]
Successfully read action definition file
Services to start                        args=[keys list]
No services to start
No chain to start
Performing action                      action=keys list
                                    directory=D:\Projects\GitHub\eris-cli
Performing step 1                             sh -c eris services exec keys ls /home/eris/.eris/keys/data
error running command (exit status 1): Unable to load the service's config for keys in C:\.eris\services.
Check your known services with:
eris services ls --known

PS D:\Projects\GitHub\eris-cli>
```

**Comment by zramsay** [comment]
were you able to `eris services start keys`? it looks so, which is weird, because that means the tool is finding the definition file in `~/.eris/services` (for windows its `C:\.eris\services` though perhaps the issue is that it should be `C:\Users\alexa\.eris\services`)

**Comment by alexandrev** [comment]
As you said I could run ```eris services start keys``` without any problem but you are wrong about ```~/.eris/services```. On Windows ```~/.eris/services``` resolve to ```C:\Users\alexa\.eris\services``` as you can see here:

```
PS D:\Projects\GitHub\eris-cli> cd ~/.eris/services
PS C:\Users\alexa\.eris\services>
```

**Comment by zramsay** [comment]
ah, k. that clarifies things a bit. i'm not on a windows machine, @pietv, thoughts?

**Comment by pietv** [comment]
@alexandrev thanks for reporting the issue, I was able to reproduce it on Windows and yes, this is a bug. It's related to the other paths issue you found, but only tangentially. I or one of my colleagues will let you know when the fix is ready.

As a temporary measure, to save time, would you be able to run this command instead:
```
eris services exec keys ls /home/eris/.eris/keys/data 
```

The `eris actions do keys list` is a macro for the above command, source for which is in `~/.eris/actions/keys_list.toml` path.


@zramsay yeah, it does fail on Windows. Apparently we run actions through `sh -c` on Windows as well. To prove it, replacing the `sh` with `cmd` did the trick (`actions/perform.go`):

```
-               cmd := exec.Command("sh", "-c", step)
+               cmd := exec.Command("cmd", "/c", step)
```

**Comment by alexandrev** [comment]
maybe we should add some flag to do different execution if the host is Windows. I've been seeing this solution on different projects like docker-client or kitematic. If you want this approach I could work on a PR.

If you like it, please let me know it!

**Comment by pietv** [comment]
I like it better when it's automated, but thanks for the idea. Will take a note and investigate it.

**Comment by alexandrev** [comment]
@pietv maybe I explained myself badl. I'm talking about a flag inside the code and something simialr like

```
if(isWindows()){
 cmd := exec.Command("cmd", "/c", step)
}
else{
 cmd := exec.Command("sh", "-c", step)
}
```

I was not talking about a command flag that you set when you run the command

Sorry, If I explain my in a bad way

Thx again for the quick responses :)

**Comment by pietv** [comment]
@alexandrev oh, as a matter of fact i did think you were talking about a command line argument. Sure, in that case, please go ahead and make a PR if you feel like it! We will be able to test it on Linux and OSX, and you would know it works on Windows. Thanks vm! :)

**Comment by alexandrev** [comment]
I'm facing problems trying to test my changes. It seems like my changes are not right when I build it from source. To do a dummy change I change the version number from 0.11 to 0.12 to see when I type "eris version" but nothing changes.

The steps I'm following are:

1.- Change the VERSION constant in the version.go 
2.- run go build -a ./cmd/main
3.- run ./eris version

I also try with go install -a /cmd/main but nothing works. What am I doing wrong? Thx!

**Comment by zramsay** [comment]
try `go install ./cmd/eris`
to run tests: `./tests/test_tool.sh local` Tests should be run with no eris containers on host. run `eris clean` to remove them all.

**Comment by alexandrev** [comment]
But if I run this command you told me or the test.sh local, I'm running the coded tests but I have no way to check if my changes are applied or not. How can I run eris-cli on local with the local changes I've made?

**Comment by compleatang** [comment]
go install command Peter gave you will do that. Build only compiles the binary but does not save to gopath/bin. Install does both.

**Comment by compleatang** [comment]
Sorry. That Zach gave...  Just catching up after a day away.

**Comment by alexandrev** [comment]
I already tried that but it is not working.

First, I changed the version.go as you can see here:

![image](https://cloud.githubusercontent.com/assets/947041/12278252/56e88826-b980-11e5-80aa-94c1ed2a9f45.png)

Then I execute: 

```
PS D:\Projects\GitHub\eris-cli> go install -a .\cmd\eris\
PS D:\Projects\GitHub\eris-cli> eris version
Eris CLI Version: 0.11.0
PS D:\Projects\GitHub\eris-cli>
```

So, my local change has no effect when I compile it and run it! :(

**Comment by compleatang** [comment]
There is something funky going on then. Check your GOPATH and also the equiv on Windows of `which eris` to make sure that go install is copying correctly into GOPATh/bin. If you installed the binary version of eris and that is referenced in your path over gopath/bin then that would explain this behavior.

**Comment by compleatang** [comment]
Also adding -v -x to the go install command should make it more verbose and may ferret out what the issue is.

**Comment by alexandrev** [comment]
You nail the problem. I have to reinstall golang but everything is working now.  I can start with this promised PR :)

**Comment by compleatang** [comment]
Whew. it was getting worrying there for a moment! Glad it is getting sorted now. Looking forward to the PR and thanks for the help.

**Comment by alexandrev** [comment]
Ok, I've done the PR but the circleCI failed trying to start the docker service. So, please if anyone on your time could take a look I'd be thankful. If I did something wrong in the procedure please let me know to fix it for another time :)

**Comment by alexandrev** [comment]
After the PR https://github.com/eris-ltd/eris-cli/issues/424 has been merged, I close the issue.
