### ISSUE TITLE
[Q] Is it possible to have all eris platform inside a docker machine?

### ISSUE THREAD

**Issue by alexandrev** [eris-ltd/eris-cli#439]
I've seen you have a lot of docker usage so I'm going to throw you the question after I'm trying to do it myself without any luck. For some requirements, I've been trying to create a docker container that has eris-cli, so you don't have to have go installed or so. But that implies to have docker inside docker, and that's not an easy thing.

I've been looking at docker-dind but nothing worked out.

Do you have something build to try eris-cli this way? 

Thx!

**Comment by compleatang** [comment]
Yup. We produce docker images for eris. 

docker pull quay.io/eris/eris 

When you run the image you need to give it access to the docker port on a non Linux system or a volume with the unix socket on Linux. 

To see an example of this look at the docker run command in tests/test_linux.sh

**Comment by alexandrev** [comment]
Thank you very much for your help and support. The answer is accurate as usual :+1:

**Comment by compleatang** [comment]
Great. If there are any challenges with eris-in-docker let us know.
