### ISSUE TITLE
make it pretty with colors

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#44]
non-exhaustive list of things to be colorized:
- [ ] `services/chains cat`
- [ ] a bunch of stdout ...

**Comment by compleatang** [comment]
https://github.com/mgutz/ansi

**Comment by ebuchman** [comment]
force the newbie to take on an easy external lib

**Comment by compleatang** [comment]
hahaha. this is for 0.11 :smile:

**Comment by ebuchman** [comment]
ya. still a good lesson in `get cozy with an open source go project you never seen before` using godoc.org

**Comment by zramsay** [comment]
also add colorizer for #43

**Comment by compleatang** [comment]
:+1:

**Comment by zramsay** [comment]
note to self: go see how tendermint does it

**Comment by compleatang** [comment]
bumping to 0.12. so far so good.

**Comment by compleatang** [comment]
gonna close this for now. we will need to revisit eris logger lib anyway.
