### ISSUE TITLE
integrate stack tests with tests from docs site

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#441]

**Comment by compleatang** [comment]
Almost two months since this issue was opened. Where are we on getting this done @NodeGuy ?

**Comment by NodeGuy** [comment]
It's visible on my list and I've been consciously making it low priority compared to working on customer issues/eris-db.js integration tests and the lab.  Would you like me to prioritize it?

**Comment by compleatang** [comment]
That's great. Stay where you are. Will reassign the issue.

**Comment by NodeGuy** [comment]
I'm working on this now as I'm writing up the REST tutorial.

In my notes I wrote that you wanted me to add the tutorial tests to the Eris CLI tests after the EPM tests.  Does that mean they should be added as one of the fixtures in https://github.com/eris-ltd/eris-pm/tree/master/tests/fixtures?  Does it mean they should run as a separate shell file after the eris-pm tests instead?  Or should they be in the eris-cli repository somewhere?

**Comment by compleatang** [comment]
> Does that mean they should be added as one of the fixtures in https://github.com/eris-ltd/eris-pm/tree/master/tests/fixtures? 

no. see below

> Does it mean they should run as a separate shell file after the eris-pm tests instead?

yes. i think the best way forward is:

- [ ] add a tests/test.sh in docs.erisindustries.com which fully contains the tests (including installing any tools or dependencies) (should also be added to docs.erisindustries.com 's circle.yml). 
- [ ] then add a section that clones the repo and runs that shell script to the test_stack.sh script in cli's repo. the section should mirror this section https://github.com/eris-ltd/eris-cli/blob/master/tests/test_stack.sh#L96-L118 only with the appropriate settings to run that bash script.

cc @NodeGuy

**Comment by compleatang** [comment]
closing this issue for now. we'll revisit once we have finished the building sequences for both the docs site and the general repo build schema.
