### ISSUE TITLE
add `--restart` option for services spec

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#444]
I want to be able to specify in the servDef file the equivalent of `docker run --restart always`
https://github.com/eris-ltd/eris-cli/blob/master/definitions/operation.go#L11

**Comment by compleatang** [comment]
Some of the docker run commands were moved to the ops struct from the services struct very early. Probably should consider moving some of them back. I moved them to ops (which users don't have control of) mostly as a safety mechanism. But agree restart likely should be in the services struct.

**Comment by zramsay** [comment]
I'm wondering if we want certain containers to have this option turned on by default

**Comment by zramsay** [comment]
closed by #463
