### ISSUE TITLE
eris keys ls --container does not do what tutorial says it should.

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-cli#445]
Following the main tutorial path I came to the backing up your keys section.

https://docs.erisindustries.com/tutorials/tool-specific/keyexporting/

Under generate a key (which I have already done) the tutorial says:

```
Since the key is in the keys data container, you’ll need to export it to host. See it in the container with:

$ eris keys ls --container
```

but running that command gives me the following output.

```
dennis@Juzo:~$ eris keys ls --container
Usage:
  eris keys [flags]
  eris keys [command]

Available Commands:
  gen         Generates an unsafe key using the keys container.
  pub         Returns a machine readable pubkey given an address.
  export      Export a key from container to host.
  import      Import a key to container from host.
  convert     Convert and eris-keys key to tendermint key

Global Flags:
  -d, --debug[=false]: debug level output
  -m, --machine="eris": machine name for docker-machine that is running VM
  -n, --num=1: container number
  -v, --verbose[=false]: verbose output

Use "eris keys [command] --help" for more information about a command.

Error: unknown flag: --container
```

not sure if this is a docs error or a cli error. I'm assuming that this command is supposed to work.

**Comment by zramsay** [comment]
requires latest develop: `eris update --branch develop`. Tut includes the alternative command that works `eris actions do keys list`. This is my attempt at future proofing tutorials; maybe it's the wrong approach. Might be better to either a) release minor versions quickly or b) add a note in tuts to `eris update --branch develop`. If we do (a) then note in tuts would just be "run `eris update` to ensure you have the latest version".

**Comment by compleatang** [comment]
this should be in docs.
