### ISSUE TITLE
machine commands

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#446]
- [ ] create | new
- [ ] use
- [ ] start
- [ ] stop
- [ ] rm

**Comment by zramsay** [comment]
I don't see the value in a wrapper for handling single machines. Most actions (as I've conceived it anyways) will be geared towards >1 machine (what I'm calling a remote) where something like `eris remotes do NAME ACTION` will perform that action on each machine within the remote NAME. Instead, users can create a remote with a single machine and control it through remotes like that, or drop down to porcelain `dm` (or use `--machine`). moving discussion to #447
