### ISSUE TITLE
remove `eris chains plop` and merge with `eris chains cat`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#452]
these are currently redundant commands. also `plop` isn't really well known. propose the following structure:

* `eris chains cat simplechain` -> displays the chain definition file
* `eris chains cat simplechain genesis` -> displays the genesis.json from inside the container
* `eris chains cat simplechain config` -> displays the config.toml from inside the container
... (as needed)

**Comment by zramsay** [comment]
could be an alias to `cat` rather than deprecating :)

**Comment by pietv** [comment]
excellent idea! will have it as an alias!
