### ISSUE TITLE
`eris chains rm` error is confusing

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#453]
When attempting to remove a running chain, it fails with the error:
```
$ eris chains new simplechain
$ eris chains rm simplechain
API error (409): Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
```

The `use -f` bit is from a Docker error message; attempting it with `eris` will not work.

Suggestion: implement the `rm -f` command as **forced remove** and rename the current `-f` flag to `--file`?

**Comment by compleatang** [comment]
:+1: I was actually thinking that the `-f` flag for `file` is non standard and will likely confuse people. `--file` is short enough and will be much less confusing.

**Comment by zramsay** [comment]
similar to #345. It *used* to throw the error and also kill/force rm the container...though now it doesn't do the latter (not sure what changed). There's a nuance in behaviour between `stop` and `rm` that can be confusing as well. Removing a container/service/chain implies stopping it while `stop` has all the flags to remove it (other than `--file`). Seems redundant. Maybe we add that flag to `stop`, and deprecate `rm` (or, alias it).

**Comment by pietv** [comment]
Yeah, the `stop` command looks a bit overdone in comparison to Docker. But since it's useful, no point of reworking it?

I have a problem with making it as an alias, since it will lead to command like `eris rm CHAINNAME` which doesn't remove but stops the container, and monsters like `eris rm --rm CHAINNAME``; and having `if`s depending on which alias is used is kind of ugly and defies the purpose of aliases?

I'd prefer to just make an amendment to `eris services rm` and `eris chains rm` without touching the `stop` command.

**Comment by zramsay** [comment]
ah yeah. good point. is there a better way we can deduplicate the functionality of `stop` and `rm` ? Note: they suffer (for chains and services) from the same error originally opened for this issue.
