### ISSUE TITLE
images should be variables located in one place only

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#458]
images we use are littered throughout the code. they should be in one place.

ERISDB_IMAGE = ....
ERISPM_IMAGE = ...
ERISCM_IMAGE = ...

etc.

**Comment by zramsay** [comment]
`version/version.go` ? Makes it easy to flip them over to docker hub too.

**Comment by compleatang** [comment]
`version/images.go` ? we do weird string parsing on that version.go file generally to get the version info into bash scripts.

**Comment by compleatang** [comment]
account for failover to dockerHub (or corporate dockerHub) when there is firewall issues

**Comment by zramsay** [comment]
we could also have `version/files.go` or something for default action/chain/service def files...right now they're in two (sometimes three) places.

**Comment by compleatang** [comment]
++ `version/files.go`

**Comment by zramsay** [comment]
closed by #466
