### ISSUE TITLE
add `build` to service definition

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#46]
build should refer to an ipfs hash. 

so the sequence for pure p2p pleasure would be:

get sent IPFSHASH of a service definition file:

`eris services import NAME ipfs:IPFSHASH`
`eris services start NAME`

behind the scenes, instead of an `image` filed the service definition file would have:

```toml
build = "IPFSHASHOFDOCKERFILE"
```

on service start, if the container is not built then the dockerfile would be pulled, placed into scratch at the HASH location (for subsequent checking), then the container would be built according to that.

*note* this would require docker file builders to *not* use the `COPY` or `ADD` features...

**Comment by ebuchman** [comment]
instead of `build = "IPFSHASHOFDOCKERFILE"` we should do `build = "IPFSHASHOFDOCKERREPO"` and then `COPY` and `ADD` should work fine

**Comment by compleatang** [comment]
sure.

we should also add a `--dir` flag to `eris files put`

**Comment by compleatang** [comment]
this is blocking until that ipfs --dir patch gets merged.

**Comment by compleatang** [comment]
closing this for now. we can revisit when its actually needed.
