### ISSUE TITLE
Board for Unfriendly Error messages (ongoing issue)

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#469]
What error messages are confusing to users and should be captured and friendly-fied before returning or displaying?

**Comment by compleatang** [comment]
- [ ] when eris cannot connect to docker we tell users that the dockerVersion is 0. this is a weird and misleading effort. within the error catch and return on the `! >= dockerMinVer` we should check if the reported dockerVer is 0 and if it is redo the error message so that users know they need to debug their ers<->docker connection first.

**Comment by dennismckinnon** [comment]
[ ] - When a service that is required is not running you get an ugly raw message talking about unable to access a port. Would be nice to (somehow magically) be told the likely culprit. Though this might be unreasonably hard... maybe part of the definition file that tells you what services you need tell you what ports they run on or some such thing and that can be used to look up the name of the missing service?

**Comment by zramsay** [comment]
AFAICT, this issue boils down to consistency in how we deal with errors. Some errors we silence completely (e.g. viper marshalling), others lack consistency (e.g. docker errors) => silenced/custom err msg/only docker err msg. As well, it can be unclear *where* the error comes from (cli or vendored lib). 

So, my proposed solution is that ~~every~~ most errors we throw should display: 1) a custom cli err msg (e.g. "Error starting service"), 2) the actual error ("some docker API error") and 3) what to do about it. The only tricky part may be pinning down (3) if we don't know (2) ahead of time although that might for thinking about better err handling.

**Comment by compleatang** [comment]
That's great. I like that a lot. (the 1.2.3.)

**Comment by zramsay** [comment]
we can start locking these down after a first pass at #468 (that'll _really_ identify the errors that need help)

**Comment by compleatang** [comment]
:+1:

**Comment by pietv** [comment]
:+1: I like very much the idea of standardizing our error messages and this 1.2.3 scheme in particular! I'm all for it!

I'd like to add one bit about those Docker API errors which are especially ugly: they don't even feel like error messages, rather as if something completely f'd up.

Luckily, they're all coming from `go-dockerclient` package calls which are concentrated in two CLI packages: `perform` and `util`: it won't be hard to write a small wrapper for those errors which will strip the first bit from the likes `API error (500): Cannot start container eris_chain_cd_1: failed to create endpoint eris_chain_cd_1 on network bridge`.

As a better solution, I suggest to fork the `go-dockerclient` library as `eris-dockerclient` (for example) and add the handlers for our most common errors with "what to do" bits proper to our own use.

Unfortunately, `go-dockerclient` doesn't structurize the API errors, it just retransmits the Docker error text, so repurposing them on our side (without forking that is) would literally require parsing error messages:

The library literally doesn't do anything about them:
```
   ...
   if resp.StatusCode != http.StatusOK {
      return newError(resp)
   }
   ...

func newError(resp *http.Response) *Error {
	...
	return &Error{Status: resp.StatusCode, Message: string(data)}
}

func (e *Error) Error() string {
	return fmt.Sprintf("API error (%d): %s", e.Status, e.Message)
}
```
https://github.com/fsouza/go-dockerclient/blob/master/client.go#L348-L350
https://github.com/fsouza/go-dockerclient/blob/master/client.go#L825-L836

Also, Docker API docs don't provide with a list of all possible API errors (at least I couldn't find one and which is understandable — they don't want to maintain that), so this will require adding status code handlers on case by case basis, but this shouldn't be a big drawback. 

A good thing about the `go-dockerclient` library is that all error related modifications will go to one file `client.go`, so it should be a big problem to rebase this fork if any important changes will come up.

**Comment by pietv** [comment]
Another bit I like about 1.2.3 scheme is that it shouldn't be too difficult to implement in one place as an `errors` package since most our error handling look like this:

```
func StartService(do *definitions.Do) (err error) {
	return err
}

func StartService(cmd *cobra.Command, args []string) {
   IfExit(srv.StartService(do))
}
```

standardizing them would require just adding a wrapper:

```
func StartService(do *definitions.Do) (err error) {
  return fuff.New("Error starting service")
  return fuff.New("Error starting service", "Marmots suggest you to leave the building")
  return fuff.New("Error starting service", err)  // For handling sub-errors.
  return fuff.New("Error starting service", err, "Marmots suggest you to leave the building")
  return fuff.New("Error starting service", "Marmots suggest you to leave the building", err)
}

func StartService(cmd *cobra.Command, args []string) {
   IfExit(srv.StartService(do))
}
```

`fuff` (or whatever the sound marmots make when they're annoyed) is in order not to reuse useful `errors` name.

**Comment by pietv** [comment]
Btw, as an aside note, this pull image ugliness is also waiting to be fixed with the `go-dockerclient`:

```
Downloading [=============>                                     ]  14.1 MB/51.36 MB
Downloading [====================>                              ]  23.2 MB/56.87 MB
Downloading [===============================================>   ] 40.47 MB/42.34 MB
Downloading [====================================>              ] 25.95 MB/35.42 MB
Downloading [==================================>                ] 12.83 MB/18.54 MB
Downloading [==============>                                    ] 14.62 MB/51.36 MB
Downloading [====================>                              ] 23.74 MB/56.87 MB
Downloading [================================================>  ] 40.91 MB/42.34 MB
Downloading [=====================================>             ] 26.32 MB/35.42 MB
Downloading [============>                                      ] 20.51 MB/79.29 MB
Downloading [===================================>               ] 13.02 MB/18.54 MB
Downloading [=====================>                             ] 24.28 MB/56.87 MB
Downloading [==============>                                    ] 15.14 MB/51.36 MB
```

**Comment by pietv** [comment]
I turned out that taking status code out of the `go-dockerclient` Error is pretty easy. Missed that.
```
err.(*docker.Error).Status
err.(*docker.Error).Message
```

**Comment by compleatang** [comment]
```
API error (500): Could not get container for eris_service_keys_1

**Comment by compleatang** [comment]
Closing in favor of #468
