### ISSUE TITLE
some love for `clean`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#479]
mostly the user friendliness & better prompting & tests

**Comment by compleatang** [comment]
via #295 -> `eris clean --uninstall` & remove orphaned volumes

**Comment by compleatang** [comment]
ensure users know that `--all` is going to delete a bunch of images they're going to have to redownload.

`--all` does not appear to be removing erisDir.

clean not currently capturing all eris containers (some data containers are left hanging)

**Comment by zramsay** [comment]
closed by #573
