### ISSUE TITLE
if no ~/.eris/chains/default directory exists, then init should run `chains make --chains-type simple`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#490]
via do structs rather than os.Exec but anyway. 

We should keep including the config files as we currently do it, but we should make a unique key and genesis.json for folks on init if these files do not currently exist.

**Comment by zramsay** [comment]
oh, but init will make that default dir regardless (with a default key ... which we're moving away from anyways)

**Comment by zramsay** [comment]
this requires a running keys container...one that ought to be left running (unless we export the key...then later ask user to import it). I'm undecided at to what init should do. Doesn't seem like the best idea for init to start _and leave running_ a keys container (but maybe it is if we're verbose & explain to users what's going on). The other option doesn't leave much to be desired for either. There's a tricky balance to strike here & I'm not sure what it is.

**Comment by zramsay** [comment]
In discussion with E; neither of these options are preferable. More importantly, it's very _not_ unix-y. This should be handled by the `eris tour` feature anyway. We might even consider axing the default dir (although i think it's used for testing)
