### ISSUE TITLE
eris keys ls is not a valid command in 0.11

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-cli#494]
The tutorial https://docs.erisindustries.com/tutorials/tool-specific/keyexporting/ mentions `eris keys ls`, but this is not a valid command (even though eris-keys is a running service).

```
pvkooten@host:~$ eris keys ls
Usage: eris keys COMMAND [FLAG...]

The keys subcommand is an opiniated wrapper around
eris-keys and requires a keys container to be running.

It is for development only. Advanced functionality is available via
the [eris services exec keys "eris-keys CMD"] command.

See https://docs.erisindustries.com/documentation/eris-keys/ for more info.

Available Commands:
  gen         Generates an unsafe key using the keys container.
  pub         Returns a machine readable pubkey given an address.
  export      Export a key from container to host.
  import      Import a key to container from host.
  convert     Convert and eris-keys key to tendermint key

Global Flags:
  -d, --debug[=false]: debug level output
  -m, --machine="eris": machine name for docker-machine that is running VM
  -n, --num=1: container number
  -v, --verbose[=false]: verbose output
```

**Comment by kootenpv** [comment]
The tutorial is for 0.11.1

**Comment by compleatang** [comment]
Seems like you haven't upgraded to 0.11.1. Once you do that `eris keys ls` will become there. 

For your version of eris you can use `eris actions do keys list` as well.

**Comment by kootenpv** [comment]
@compleatang I noticed the command (as it was mention in the tutorial). Is there a simple way to upgrade to 0.11.1?

**Comment by kootenpv** [comment]
Stupid question, if I wouldn't have used the binary there is simply `eris update`. I'll uninstall binary and reinstall 0.11.1

**Comment by compleatang** [comment]
From 0.11.1 forward we have the capacity to upgrade binary installs as well as builds. `eris update` should work for both going forward.

**Comment by kootenpv** [comment]
Side issue: 

    eris keys ls
    panic: runtime error: index out of range

When no keys.

**Comment by zramsay** [comment]
Hi @kootenpv, the last issue you found has been fixed [here](https://github.com/eris-ltd/eris-cli/pull/492). You'll need to `eris update branch --develop` to get that fix since it hasn't made into a release yet.

**Comment by kootenpv** [comment]
@compleatang I'm now running 0.11.1 and I want to upgrade (to test the new IPFS).

When I run `eris update` (using the binary) I get:

    Ensure you have Go installed.

Shouldn't that not be neccessary?

**Comment by compleatang** [comment]
Yes. That *should* have been fixed in 0.11.1 release. If you haven't upgraded can you dump the debug output for us as that would be a bug.

**Comment by compleatang** [comment]
Also, that change is in master now (was integrated into 0.11.2 release) so no need as of Friday to use `--branch develop` ....

**Comment by kootenpv** [comment]
```
pvkooten@prftrd:~$ eris version
Eris CLI Version: 0.11.1
pvkooten@prftrd:~$ eris update
Ensure you have Go installed.         version=
You do not have $GOPATH set. Please make sure this is set and rerun the command.
```

**Comment by compleatang** [comment]
Hmm. You're very right. Just reviewed, and there are some logical errors in how `UpdateEris()` is currently working. 

If you just pull the binary from our releases it will be the updated 0.11.2 version. We'll rework this logic for the next release because it currently won't work. 

I'll make a new issue for that.

**Comment by compleatang** [comment]
OK. That identifies a different issue (although the one above still needs to be fixed). 

Can you check `/usr/bin/eris_0.11.2....` to see if the tarball is there.

**Comment by kootenpv** [comment]
Unfortunately I did an `apt-get remove eris` followed by an `apt-get install eris` to get at 0.11.2, so I do not know the status of that before.

However, doing a `find . | grep eris` in the `/usr` folder did not point to anything related to eris_0.11.2 nor to a tarball, afterwards.

**Comment by compleatang** [comment]
Cool. We'll fix the logic but pleased you're already upgraded.
