### ISSUE TITLE
expose machine readability for the output of some commands (--quiet)

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#495]
useful mostly for bash scripting. might not actually be needed but sometimes it would be nice. the solution is less than ideal: `if !do.Quiet { log.Warn("bleh") }`, unless there's a better way.

**Comment by compleatang** [comment]
What commands?

**Comment by zramsay** [comment]
`eris keys ls`, `eris files put` => see `test.sh` in toadserver repo

**Comment by zramsay** [comment]
maybe it could it a global flag that suppresses any `log.Warn/Info/Debug` and the only output is `do.Result`

**Comment by compleatang** [comment]
hmm. not sure we want a global flag, but don't have super strong opinions on that.

**Comment by zramsay** [comment]
including in #668
