### ISSUE TITLE
add ports flags to chains start

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#50]

**Comment by ebuchman** [comment]
to really do this we need support for multiple flags of the same name.

**Comment by compleatang** [comment]
what we have to do is built a custom pFlag() parser.

I _think_ it would be based on something like this: https://github.com/spf13/pflag#mutating-or-normalizing-flag-names

**Comment by compleatang** [comment]
https://github.com/docker/docker/blob/master/pkg/mflag/flag.go#L313

That's Docker's SliceFlag struct and the requisite functions. Now to figure out how to integrate that into the parser...

**Comment by compleatang** [comment]
@ebuchman the easiest way to do this now (it appears) is to use the pFlag libraries, comma separated stringSlice population....

See the *Value* interface here:

https://github.com/spf13/pflag/commit/29224ee030bd4e687e95d1d8df55303269b49337

From pFlag's readme:

```
Or you can create custom flags that satisfy the Value interface (with pointer receivers) and couple them to flag parsing by

flag.Var(&flagVal, "name", "help message for flagname")
For such flags, the default value is just the initial value of the variable.

After all flags are defined, call

flag.Parse()
to parse the command line into the defined flags.
```

the key line we'd have to change is here (i think) -> https://github.com/spf13/pflag/blob/master/string_slice.go#L43

**Comment by compleatang** [comment]
OK. This isn't going to happen on a per port basis unless we wanna write a custom pFlag parser (which I don't think is gonna really help us now). The `-p` flag will publish all ports easily for folks and the service definition files can/should be used to add more specificity. The publish flag is working as of b42f3bf ....
