### ISSUE TITLE
data import should mkdir in the container if it doesn't exit

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#501]
I'm on the fence. Would be ++ convenient but seems very non-unixy

**Comment by compleatang** [comment]
its hard to reap that error too....

**Comment by pietv** [comment]
I like it. You won't need to think about that thing. Very convenient.

**Comment by compleatang** [comment]
i guess on import we could (1) create the data container; (2) mkdir (without reaping the inevitable `directory exists` error); and (3) copy into the container.

this would make the reworked eris contracts import sequence a heck of a lot cleaner. right now i'm doing this manually for all of the importing it has to do and its quite ugly.

**Comment by zramsay** [comment]
closed by #583 
cc @ebuchman & @compleatang please test for your respective use cases
