### ISSUE TITLE
0.11.3 (dev): `eris chains make` freezes

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#510]
I am running on 0.11.3 from the dev branch. `eris chains make toRemoveLater` is getting some docker images and eventually stalls at:
```
Pull complete
Digest: sha256:1f1447e567a7e9cafb2afbf11b8ea0235bef4fbd9b0f44e23e4d2389e03e5e40
Status: Downloaded newer image for quay.io/eris/eris-cm:0.11.3
```
I tried making another one with `-d`:
```
cd /root/work/src/github.com/eris-ltd/eris-cli
[doing lots of stuff]
Waiting for container to exit                 eris_interactive_eris_service_toRemoveLater2_1
```

**Comment by dennismckinnon** [comment]
I can confirm this behaviour

**Comment by pietv** [comment]
I can confirm this behaviour too. Luckily it's unrelated to #507. 

Thanks for finding it early, you're very helpful!

Will update you when the fix is merged with the #develop or #master.

**Comment by pietv** [comment]
@SCBuergel please try the #develop branch when you have time for this if the fix is working for you. This time the `eris update --branch=develop` command may work for you. Many thanks!

**Comment by SCBuergel** [comment]
Yes, seems fixed, was successully going through the `make` wizzard. Thanks!
