### ISSUE TITLE
Handling the (suddenly) missing Eris home directory

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#512]
When running any Eris CLI command except for the `init` command; if the ERIS home directory is missing:
* If `ERIS` environment variable is not set, suggest to point it to the proper Eris home directory.
* If any Eris containers are running, suggest to remove them with the `eris clean` command.
* Don't show the `open /Users/peter/.eris/eris.toml: no such file or directory` error.

**Comment by compleatang** [comment]
++ that is a bit annoying.
