### ISSUE TITLE
Show a useful error when running `eris update` with the binary installation

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#513]
When running `eris update` command with the binary installation, show the instruction how to pull and the binary manually instead of the error `Error changing directory: %!v(MISSING)`.

Related to #507.

**Comment by kootenpv** [comment]
Looking for the solution to this (I assume it's in the latest but I'm coming from 0.11.2.

**Comment by pietv** [comment]
Hi @kootenpv, this ticket is closed in favour of the issue #516 which solves the same problem in a different way, and it's currently a WIP. We'll keep you updated on the issue. Thanks.
