### ISSUE TITLE
Loosen coupling with wrapped images 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#515]
**Problem** -- upgrades are too hard. Version releases need hotfixes. 

**Solution** -- loosen the coupling with wrapped images which, by default, should move to using major.minor instead of major.minor.patch (current strategy)

**Comment by compleatang** [comment]
We don't really need this until we go to 1.0. For now while the stack is in a bit more flux let's keep the coupling tight and a good release checklist so things are more certain to work well version by version.

**Comment by compleatang** [comment]
For the record another way to handle this would be for tooling image versions (eris-pm, eris-cm predominantly) to be selectable in the ~/.eris/eris.toml Global config file rather than being hard coded as is the current paradigm. eris:db isn't really an issue cause chain definition files can always select.

**Comment by zramsay** [comment]
++ for the `~/.eris/eris.toml` global config rather than in `version/images.go`. agree it can wait.

**Comment by zramsay** [comment]
(this functionality would've been epic with the alpine switch)

**Comment by zramsay** [comment]
closed by #779
