### ISSUE TITLE
`eris update` on binaries logic not currently working

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#516]
**Problem** -- when updating from a binary installation, `eris update` still tries to install via go. The [current code](https://github.com/eris-ltd/eris-cli/blob/v0.11.1/util/update_tool.go#L96-L102) which controls a binary install will pull the binary OK, but it will still try to check the go path (there is no return in that `if` statement, so the func will just continue down to the "install via go" [section here](https://github.com/eris-ltd/eris-cli/blob/v0.11.1/util/update_tool.go#L117-L126).

**Solution** -- refactor the if statement such that it: downloads binary to proper location; runs migrate; runs `version()` and notifies user of successful installation; then it should exit rather than continue with the `UpdateEris()` function as currently structured.

**Comment by compleatang** [comment]
Note [this message](https://github.com/eris-ltd/eris-cli/blob/v0.11.1/util/update_tool.go#L138) and the git message a few lines after should be clearer since we should be fully supporting binary only installations.

**Comment by compleatang** [comment]
Another update issue is the [tarball extraction](https://github.com/eris-ltd/eris-cli/blob/v0.11.1/util/update_tool.go#L79-L87) logic is currently failing (I think because of the `bin/sh` reference).

We need better tests for this.

**Comment by zramsay** [comment]
closed by #617
