### ISSUE TITLE
Finding past transactions on blockchain

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-cli#518]
Not sure where to ask, but I'm wondering how / using which component it is possible to find _past transactions_ on the blockchain?

I was sifting through the json from e.g. `http://localhost:46657/blockchain?minHeight=1000\&maxHeight=2600`, and I could find `"num_txs":1`, but the only difference is that it contains a `data_hash`. Is there no way to find out more information on the blockchain?

**Comment by compleatang** [comment]
Sure. The RPC has a range of information available. If something specific is lacking from the RPC let us know here -> https://github.com/eris-ltd/eris-db and we'll see if it is possible to add. 

Note, though, that the RPC is getting overhauled during our 0.12 push toward increased modularization of the main chain component pieces so any current functionality needed let us know and we'll add it if we can.

In general, with EVM style chains we rarely find lots of utility in log parsing, but if it is helpful to you and we're not currently supporting please let us know in eris-db repo. Closing this here mostly for book keeping reasons...
