### ISSUE TITLE
Dependencies `$chain` variable not resolving in `services start`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#524]

**Comment by zramsay** [comment]
reproduction? both the mindy and toadserver tests use `services start --chain` and they're green...

**Comment by compleatang** [comment]
do you hardcode the chain in the service definition file or use the `$chain` variable?

**Comment by compleatang** [comment]
moving over to zach.

**Comment by zramsay** [comment]
this resolves with `eris services start toadserver --chain=whatever` so long as whatever is a running chain:
```
name = "toadserver"
chain = "$chain:toad:l"

[service]
name = "toadserver"
image = "quay.io/eris/toadserver"
ports = [ "11113:11113" ]
volumes = [  ]
environment = [
	"MINTX_NODE_ADDR=http://toad:46657/",
]
```
(ignoring the other details)

**Comment by zramsay** [comment]
I've tested various combinations of a definition file & no bugs found. The above works, as does commenting out the requirement for `--chain` and setting:
```
[dependencies]
chains = [ "somechain" ]
```
Using `$chain` directly in strings (e.g., env vars) also works.
