### ISSUE TITLE
Eris chains make - 404

### ISSUE THREAD

**Issue by 18dew** [eris-ltd/eris-cli#526]
Error while creating new chain using eris chains make 

API error (404): lstat /var/lib/docker/aufs/mnt/633c9e6d3724f46e1e3974ac233a077408e1ac62e384667293e4fd8762484147/home/eris/.eris/chains/account-types: no such file or directory

**Comment by 18dew** [comment]
Note I am using AWS AMI of eris and did eris update

**Comment by compleatang** [comment]
No problem. `eris clean --dir` && `eris init` will get you set back up.

**Comment by compleatang** [comment]
Closing this issue now. Feel free to reopen if the error isn't solved by the above instructions.
