### ISSUE TITLE
Solc version in Erisdb. 

### ISSUE THREAD

**Issue by 18dew** [eris-ltd/eris-cli#527]
How do we check the solidity (solc) version installed in Erisdb and is there any mechanics to change the solc version .

**Comment by compleatang** [comment]
solc is not installed in erisdb. 

We use a compilers image by default for compiling. It automatically tracks ethereum ppa releases. EPM is setup to use the hosted compilers by default but you can run your own and change it with a flag in eris pkgs do or in epm itself depending on how you're running it.
