### ISSUE TITLE
remove do.ContainerNumber

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#531]
does anyone actually use this? ever?

**Comment by pietv** [comment]
excellent idea! both the code and the debug log will be so much cleaner!  you can always create a 'simplechain-2' or ' testchain-3' instance. this probably up to another voting session.

**Comment by compleatang** [comment]
I don't have strong opinions here. It was originally put in case we needed to add something like docker compose's scale function (Tutum has a similar feature). 

Once labels were added (which we should probably moving parsing to use rather than names anyway) as, I think @pietv 's first issue it sort of became irrelevant.

**Comment by pietv** [comment]
Great! That makes sense: labels will make it more flexible. I have a question though how the labels will make the containers numbers irrelevant automatically? 

With labels, the functions such as `util.ContainersName(name, type, number)` will create container labels with a number in them, and later the other functions like `util.FindContainer(name, type, number)` will search for a container with particular labels, again with a container number in them. The signatures of these functions have to be changed anyway to get rid of container numbers, so it doesn't matter whether this is done before or after the labels are used for searching.

Yes, will rebase and merge that container search part of that issue, it's hanging around for some time.

**Comment by compleatang** [comment]
++

**Comment by zramsay** [comment]
P, I'm not sure I understand your question. This change has a few `perform` tests failing (those that used `number` for example. Can we just do away with numbering altogether? Does it even neeed to be re-wired into the labels...?

**Comment by pietv** [comment]
Zach, great! That was exactly my point with the question: we can do away with numbering independently from labels. Can be done before or after (better not simultaneously, though, to avoid merge conflicts).

And about `perform` tests: they test container numbering as well, so getting rid of numbering will require amending and removing some tests, certainly.

**Comment by zramsay** [comment]
closed by #552
