### ISSUE TITLE
fix exec and restarts

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#532]
**Problem** -- currently when a service has a restart policy which is not none execs cannot work because they cannot remove the container.

**Solution** -- two possible fixes: (a) forcibly remove the container if its an exec (not ideal); (b) catch the restart policy on the way towards perform so that perform doesn't need to make any changes (my preferred option).

**Comment by compleatang** [comment]
Short term solution here is to not really use restart policieis fully yet.

**Comment by pietv** [comment]
`configureInteractiveContainer()` may just explicitly set the RestartPolicy to `NeverRestart()`. this should fix the issue.

**Comment by compleatang** [comment]
++ closing since #533 is merged :)
