### ISSUE TITLE
Speed up eris pkgs do

### ISSUE THREAD

**Issue by kootenpv** [eris-ltd/eris-cli#537]
A contract with a few calls takes a long time in 0.11.3.

    time eris pkgs do --chain simplechain --address $addr
    
    real	0m53.185s
    user	0m0.060s
    sys		0m0.060s

**Comment by compleatang** [comment]
There are three relevant levels which will be necessary to understand in order to speed this up.

1. eris->docker daemon (if remote time increases based on network latency between local and remote machines).
2. eris-pm execution 
3. reporting / display of writers

**Comment by compleatang** [comment]
Big lag between:

```
Container already running. Skipping           simplechain-ba2ac18e-b2c0-48d9-b035-07205cdb354a
Defaulting to service                 service=commons-collections_tmp
```

**Comment by compleatang** [comment]
closing this issue. we'll need to get more precise, but there are number of things we can fix... particularly #539
