### ISSUE TITLE
Ongoing Board for Not Useful `debug` output

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#538]
Where debug isn't helping but is just polluting our output we should discuss here.

**Comment by compleatang** [comment]
```
Performing action. This can sometimes take a wee while
...
entrypoint...
```

entrypoint redisplayed in the executing interactive container (perform package level) and is irrelevant as the pkgs pkgs level.

**Comment by zramsay** [comment]
related to #483

**Comment by compleatang** [comment]
closing for non use and also #483 (which is about to be merged and closed anyway)
