### ISSUE TITLE
[Pkgs] control a bit more closely the eris-pm artifacts which are put back onto the host

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#539]
https://github.com/eris-ltd/eris-pm/issues/69

**Comment by compleatang** [comment]
this is annoying when you're in an editor and it forces a reindexing of your filesystem.

**Comment by zramsay** [comment]
++ just starting experiencing this

**Comment by zramsay** [comment]
the original issue is gone. not clear what the problem is.

**Comment by compleatang** [comment]
the refactoring out of docker will fix this.
