### ISSUE TITLE
chains install should be able to work with a pre-existing data container

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#54]

**Comment by ebuchman** [comment]
nvm - this is not really a valid use case

**Comment by compleatang** [comment]
@ebuchman actually i think it is. 

possible use case -> 

* manually compose a genesis, config, priv_val, etc. in `~/.eris/data/NAME`
* `eris data import NAME` 
* `eris data exec -i NAME`
*  ... do stuff, test, tinker, repeat above steps ... 
* `eris chain new NAME`

It would only require that we not override. our normal flow should be sufficient but eris shouldn't flame out of the data container already exists... If you agree we can reopen. The above is an edge case for sure so not really of strong opinions here.

**Comment by ebuchman** [comment]
ya this should totally be allowed because otherwise its annoying

**Comment by ebuchman** [comment]
@zramsay test

**Comment by compleatang** [comment]
this is closed by #69
