### ISSUE TITLE
eris chains new should *not* respect the data dir

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#540]
lots of times stuff gets "stuck" in that directory and even advanced users (i.e., me) forget to check that.

new should mean new and we should forcibly overwrite the scratch dir (or, better, not use and just use the new data dest|src paradigm).

**Comment by compleatang** [comment]
I guess the easiest fix here is to change the `--force` flag from being false to being true. If folks *don't* want to override on `new` they can use the `--force` flag, but I am unsure the use case for that...

**Comment by zramsay** [comment]
hm https://github.com/eris-ltd/eris-cli/blob/master/cmd/chains.go#L416

**Comment by zramsay** [comment]
maybe we just eliminate the `--force` flag and overwrite by default...

**Comment by compleatang** [comment]
I'm in favor of removing the force flag and overwriting by default. There is no `other` use case where users would not want that to be the result that I can think of. Otherwise they should be using `start`...

**Comment by zramsay** [comment]
++
note: since the default was `--force=true`, is it possible the bug was coming from somewhere else ?

**Comment by compleatang** [comment]
The problem is that bool defaults which are true don't actually get marshalled as true. there some weird thing where technically we're supposed to do a marshalling on bools to see if they changed (although I cannot remember the exact cobra function). 

Usually when we have a bool flag which defaults to true then in any `if` statements we actually need to negate them. Summary, this https://github.com/eris-ltd/eris-cli/blob/master/chains/operate.go#L31 will never be true unless it is actually false in which case it won't do what we want it to do.

Either way we should lose it because the behaviour we desire is to just overwrite that data dir in scratch.

**Comment by zramsay** [comment]
closed by #557
