### ISSUE TITLE
Chain won't start due to height mismatch

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris-cli#545]
My PC suffered a mains power failure. On restarting the VM I can't start a chain. ``` eris chains start simplechain``` returns no error but examining the logs shows the error as 
```
panic: Paniced on a Sanity Check: state (712533) and store (712528) height mismatch
```
The full log output is [error.txt](https://github.com/eris-ltd/eris-cli/files/157294/error.txt)

Is there a way to recover the chain?

**Comment by zramsay** [comment]
@ebuchman can you take a look?

**Comment by ebuchman** [comment]
Hi,

This is indeed a bug - thanks for reporting, we'll need to make sure this doesn't happen. As for recovering your chain, I'm afraid the best we can do is revert your state to the same height as the block store (712528). We do not currently have a tool for this but I can whip one up tonight if that works

**Comment by rlaveycal** [comment]
No need for a fix - it was just a test chain.

**Comment by compleatang** [comment]
Closing this for now. This happens at times if the chain is not shut down gracefully.
