### ISSUE TITLE
Can't update to fix bug #546.

### ISSUE THREAD

**Issue by NodeGuy** [eris-ltd/eris-cli#548]
```
$ eris update
Eris requires docker version >= 1.8
The marmots have detected docker version: 1.1
Come back after you have upgraded and the marmots will be happy to service your blockchain management needs
```

**Comment by pietv** [comment]
`eris update` doesn't work for binary installations.

**Comment by NodeGuy** [comment]
This isn't a binary installation.

**Comment by pietv** [comment]
https://github.com/eris-ltd/eris-cli/issues/516

**Comment by NodeGuy** [comment]
I installed from source, see #546.

**Comment by pietv** [comment]
That's irrelevant.

**Comment by NodeGuy** [comment]
I don't understand what you're saying.  #516 explains `Problem -- when updating from a binary installation, eris update still tries to install via go.`

I'm not updating from a binary installation.  Why do you keep talking about binary installations?

**Comment by pietv** [comment]
ok, in that case it can't install because it checks the first of the Docker first. you might need to replace the `eris` binary the different way, by, for example downloading it from Releases: `wget https://github.com/eris-ltd/eris-cli/releases/download/v0.11.2/eris_0.11.2_linux_amd64.tar.gz`

**Comment by NodeGuy** [comment]
That solved my problem, thank you.
