### ISSUE TITLE
add docker 1.9.1 install notes getting-started

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#549]
For now I am required to rely on the [temporary hack](https://docs.erisindustries.com/tutorials/getting-started/) of running docker 1.9.1. This step one of getting started is tough:

- The link to the docker site that you post will install the latest version of docker
- The link to install 1.9 on the docker site is unfortunately broken (https://docs.docker.com/v1.9/ -> docker engine -> ubuntu links to https://docs.docker.com/v1.9/installation/ubuntulinux/)
- In the `temporary hack` section you write `It is very easy to downgrade your docker version to 1.9.1 though.` It might be obvious to most, but since this is step 1 of getting started with Eris it would be great to explain how this works (also see previous point).

**Comment by compleatang** [comment]
Thanks for the report. We've fixed the bug which was prohibiting eris to connect into 1.9 and I have removed that entire temporary hack from the site. My apologies for the confusion.

The docs will be refreshed/vetted this week as we prepare for 0.11.3 release.
