### ISSUE TITLE
standardize the Raw interfaces

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-cli#55]
all raw interfaces should take
  - name
  - ops (*def.ServiceOperation), which includes ContainerNumber and other things that may be specified at cli
  - flags for that particular functionality

**Comment by compleatang** [comment]
agree. and in that order with the following nuance. 

* servName string
* ops *def.ServiceOperation
* args
* flags

ServiceByServices should adopt a similar structure:

* srv *def.Service
* ops *def.ServiceOperation
* args
* flags

**Comment by compleatang** [comment]
E, imma gonna move this over to you for now cause I think you'll be in this area helping zach with the container numbers stuff. It's pretty low priority though. Just if you're in there.

**Comment by compleatang** [comment]
This is closed by #81
