### ISSUE TITLE
chain making tutorial breaks when running it right after getting started guide

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#550]
Following your [chain making tutorial](https://docs.erisindustries.com/tutorials/chainmaking/) on Ubuntu 14.04 I run into the following issue at the beginning of [Step 3. Instantiate the Blockchain](https://docs.erisindustries.com/tutorials/chainmaking/#tocAnchor-1-6)

```
eris chains new simplechain --dir $chain_dir_this
API error (500): failed to create endpoint eris_chain_simplechain_1 on network bridge: Bind for 0.0.0.0:46657 failed: port is already allocated
```

I tried to find out what breaks it and if it and found that when skipping the beginning of the [getting started tutorial](https://docs.erisindustries.com/tutorials/getting-started/) it works. In that case this is the entire list of commands right after installing eris:
```
eris init
eris services start keys
eris keys gen
eris keys export 09C1EC4F054D04E50996F902FBCBD9D3CBEE88DE
chain_dir=$HOME/.eris/chains/simplechain
chain_dir_this=$chain_dir/simplechain_full_000
eris chains make --account-types=Root:2,Full:1 simplechain
eris chains new simplechain --dir $chain_dir_this
eris chains ls
eris chains logs simplechain
```

The above procedure breaks due to
```
eris chains new test_chain
```

Since you note that `To continue this getting started tour please see our next tutorial in this series on Making Your Own Permissioned Chain.` it should work seamlessly to do the [getting started](https://docs.erisindustries.com/tutorials/getting-started/) and then right after continue with the [chain making tutorial](https://docs.erisindustries.com/tutorials/chainmaking/).

**Comment by SCBuergel** [comment]
I would suggest adding `eris chains stop test_chain` at the end of the [getting started](https://docs.erisindustries.com/tutorials/getting-started/) with a note that this is required to continue with the next tutorial.

**Comment by compleatang** [comment]
Great feedback! Have added to tutorial.

**Comment by cbruguera** [comment]
What if I want to run another chain simultaneously? Can't I bind it to another port? I tried starting with the `--ports` flag (and specifying a different port) but the same error message is still displayed. I can't run more than one chain at the same time.

**Comment by zramsay** [comment]
@cbruguera you'll need to use the `--publish` flag to randomize the ports. the `--ports` flag takes arguments if you want to set specific ports.
