### ISSUE TITLE
eris pkgs do reports  /home/eris/.eris/apps/idis_app/abi: is a directory when deployment fails

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris-cli#562]
eris 0.11.2

I have a chain with 2 validators defined in the genesis block but only 1 node is running.

Deploying a package to the chain with ``` eris pkgs do --chain X --address A ``` fails with error

```
ERROR =>
open /home/eris/.eris/apps/idis_app/abi: is a directory
Container eris_interactive_eris_service_idis_app_tmp_deploy_1 exited with status 1
```

I'm assuming that this is because the contract cannot be validated by 2/3+1 of the defined validators as only 1 node is running (50%). However the error message is confusing.

**Comment by compleatang** [comment]
Indeed the source of the error is correctly identified. 

We've updated that error message to be much more explicit in 0.11.3:

https://github.com/eris-ltd/eris-pm/blob/develop/util/errors.go#L71-L104

(if that text doesn't help let us know as happy to improve these)

**Comment by rlaveycal** [comment]
great.

Maybe amend ``` * ensure that your contracts successfully deployed ```

to ``` * ensure that your contracts successfully deployed (do you have enough validators running?) ```

**Comment by compleatang** [comment]
:+1:
