### ISSUE TITLE
check that `docker-machine version` is a minimum

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#565]
as we do with `docker version`. just upgraded from 0.5.6 to 0.6.0 & it solved a lot of problems. should also match what we're testing in circle

**Comment by compleatang** [comment]
wondering if dm needs to be a requirement. either way we need to document it in getting-started

**Comment by zramsay** [comment]
probably not but we should encourage it for the time being. the check can pass if `dm` isn't installed

**Comment by compleatang** [comment]
++

**Comment by zramsay** [comment]
closed by #581
