### ISSUE TITLE
Move hosting YUM and APT repositories to Amazon S3; Improve Release Script

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#586]
A couple of suggestions to simplify the `eris-cli` release process:

#### We could use two dedicated Docker containers (themselves buildable at the time of release) to build .rpm and .deb packages respectively:

$ docker run quay.io/eris/build_apt
$ docker run quay.io/eris/build_apt master
$ docker run quay.io/eris/build_apt develop (or any other branch)

$ docker run quay.io/eris/build_yum
$ docker run quay.io/eris/build_yum master
$ docker run quay.io/eris/build_yum develop (or any other branch)

which will

1. Pull the specified branch from Github.
2. Build and sign the respective packages (signing without asking for a password).
3. Push the packages (and update the repo indexes if the branch is master) to the dedicated Amazon S3 bucket.
4. Test pulling the packages.
5. If successful and the branch is #master, output on the console the repo configuration file.
6. If successful and the branch is not #master, output on the console a copy-pastable link to the file on S3 (to be able to quickly build a package and send the link to a user).

The benefits of this method are
* No need to copy over Docker Machine definition files since the build containers will build and push the Linux packages from a local machine.
* No need to keep a running virtual machine on DO.
* No need to rely on `goxc` to build .deb packages.
* Easily buildable packages for #develop or other branches (without rebuilding and messing up the master repo).

#### Modify the release script to build Linux packages first, then
1. Build binaries for various platforms without `goxc` (and without the `.tar.gz` suffix).
```
$ GOOS=linux GOARCH=386     go build -o eris_<version>_linux_386
$ GOOS=linux GOARCH=amd64   go build -o eris_<version>_linux_amd64
$ GOOS=darwin GOARCH=386    go build -o eris_<version>_darwin_386
$ GOOS=darwin GOARCH=amd64  go build -o eris_<version>_darwin_amd64
$ GOOS=windows GOARCH=386   go build -o eris_<version>_windows_386
$ GOOS=windows GOARCH=amd64 go build -o eris_<version>_windows_amd64
```
2. Pull the Linux packages from Amazon S3 hosted repos.
3. Publish the bundle with the `github-release`.

**Comment by compleatang** [comment]
++ agree with all those. no reason really with go packages that we would do that taring and ziping. the S3 system is exactly how docker does it too...

**Comment by compleatang** [comment]
@pietv at the end of that build process we should add them to ipfs and publish the hashes on the release announcement.

**Comment by pietv** [comment]
:+1: for IPFS and hashes.

**Comment by AFDudley** [comment]
the IPFS node can just mount the S3 bucket.

**Comment by pietv** [comment]
:+1:

**Comment by AFDudley** [comment]
Just a head's up, my plan right now is to run the release script from jenkins which should simplify this whole process.

**Comment by pietv** [comment]
The S3 bucket names:

```
AWS_S3_RPM_REPO=eris-rpm
AWS_S3_RPM_PACKAGES=eris-rpm-files
AWS_S3_DEB_REPO=eris-deb
AWS_S3_DEB_PACKAGES=eris-deb-files
```
