### ISSUE TITLE
eris pkgs do fails when failing to remove intermediate container

### ISSUE THREAD

**Issue by Latrasis** [eris-ltd/eris-cli#587]
When running `eris pkgs do ..` the build step fails when docker fails to call `rm` on an intermediate container.

This situation arises when using a CI tool, specifically CircleCi, where `docker rm` is not allowed:
https://discuss.circleci.com/t/docker-error-removing-intermediate-container/70

Eris should simply give an warning on this instead of failing assuming that this does not affect the deployment of a contract. Without this check, running tests on eris instances would require having a custom CI setup, which is painful.

**Comment by compleatang** [comment]
We have a flag for this scenario. Just use the `--rm` flag on your packages do. You can even alias for your setup if you so desire.

**Comment by compleatang** [comment]
For an example, eris-pm's [test harness](https://github.com/eris-ltd/eris-pm/blob/master/tests/test.sh#L134-L145) handles both issues by just adding that flag when on `btrfs` type setups.

**Comment by compleatang** [comment]
The reason that it fails rather than fails silently is a design choice. However, if you feel it is tripping you up, even with the additional flag, let us know as we're happy to give it a think.

**Comment by Latrasis** [comment]
Hi @compleatang! Thank you for the followup! It works now!  It would be nice to add this in the documentation, or else set this as a warning instead.

**Comment by compleatang** [comment]
Super! So currently it is [documented here](https://docs.erisindustries.com/documentation/eris-cli/0.11.3/eris_pkgs_do/). But if you have any ideas for how to help users know this more easily let us know.

**Comment by Latrasis** [comment]
Maybe add this in https://docs.erisindustries.com/tutorials/contractsdeploying/ ?

**Comment by compleatang** [comment]
:+1:
