### ISSUE TITLE
There is no documentation for installing from source

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/eris-cli#595]
The `go get` line doesn't work for non-master branches?

**Comment by pietv** [comment]
@AFDudley , `go get ...` is the command for installing Eris CLI from source and yes, it uses the master branch.

installing branches other than master is used to test new features or fixed bugs and advised to users in issue tickets and email threads. the useful command for this is `eris update --branch develop` or the usual sequence of `git fetch / git checkout`

**Comment by compleatang** [comment]
https://docs.erisindustries.com/tutorials/install-source/
