### ISSUE TITLE
Agent should return the epm.json result of the deployment

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#600]
Since the agent currently executes whatever was specified in the epm.yaml inside the contract bundle, it would make sense to return the epm.json as the response body to the caller.
This way the client can get easy access to things like addresses where contracts were deployed.

**Comment by zramsay** [comment]
closed by ^. @j-h-scheufen close if you are satisfied with that solution.

**Comment by j-h-scheufen** [comment]
Tested manually with implementation of https://github.com/eris-ltd/eris-contracts-library/issues/45. Closing ticket.
