### ISSUE TITLE
`eris` installed to non-standard location

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/eris-cli#608]
installing `eris` in ~/go/bin/eris makes all sorts of assumptions about deployment. if it's a service it should be installed as a service. Not a blocker for me, but I thought it should be logged someplace, since it did confuse me.

**Comment by AFDudley** [comment]
The solution here is to install distro packages where ever possible and not use go installs in scripting/testing. This is partially being addressed with #516

**Comment by pietv** [comment]
Installing the package binary with the source goes into the path specified by the `GOBIN` environment variable. If that path is not specified the binary is installed to the path specified by the `GOROOT/bin`. If that variable is not specified either, the binary is installed in the GOROOT path defined at Go languange build time (can be checked with the `go env` command), so this is how the installation from source behaves, not a bug.

**Comment by AFDudley** [comment]
Oops, I was using a non-standard install method.
