### ISSUE TITLE
Eris using /root/.eris instead of $HOME/.eris

### ISSUE THREAD

**Issue by Latrasis** [eris-ltd/eris-cli#609]
Running with Ubuntu `14.04`, installed with `apt-get`, when running the eris command:
`eris chains new --dir simplechain/simplechain_validator_001 simplechain` 

I get an error:
`stat /root/.eris/chains/simplechain/simplechain_validator_001: no such file or directory`

I'm guessing the reason might be `dir.DataContainersPath` is being set incorrectly?

**Comment by compleatang** [comment]
hmm. there appears to be a mismatch in those commands. is one a typo? (`..._val_001` v. `..._val_000`). also can you confirm whether you are running this from the root user or from another user?

**Comment by Latrasis** [comment]
Ah sorry, that was a type yes. I do run as root.

**Comment by compleatang** [comment]
Cool. No worries. Can you paste or pastebin the debug output from the new command? (just add `--debug` to the end). That will give us more visibility on where the error is.

**Comment by Latrasis** [comment]
Here is the output:
```
account: validator index: 0 node: 192.168.50.20
simplechain/simplechain_validator_000
Checking Linux Docker socket                  unix:///var/run/docker.sock
Connecting to Docker                          unix:///var/run/docker.sock
Successfully connected to Docker daemon
Setting up chain                              simplechain
Path does not exist or not a directory
                                         path=simplechain/simplechain_validator_000
Trying                                   path=$HOME/.eris/chains/simplechain/simplechain_validator_000
Path does not exist or not a diretory         /root/.eris/chains/simplechain/simplechain_validator_000
stat /root/.eris/chains/simplechain/simplechain_validator_000: no such file or directory
```

**Comment by Latrasis** [comment]
Apologies, I realized this was on my end.

**Comment by compleatang** [comment]
Cool...! Hope things back to working for you!
