### ISSUE TITLE
reap the notorious `--tlsverify` error in CI tests

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#616]
e.g.: `The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Get https://IP:2376/v1.21/version: remote error: bad certificate`

Tests shouldn't fail when encountering this error but rather should kill what's currently in process & start over.

**Comment by compleatang** [comment]
So they actually already take this error (the first time it throws) into account. That is what will trigger a regenerate certs call. The second time it occurs though is when it will fail out. We may want to increase those tries but usually it means that there has been a bad provisioning. At least it did in earlier versions of dm. Now that dm is making leaps and bounds towards maturation probably important to revisit.

**Comment by zramsay** [comment]
we should use `dm provision` which really means re-provision, which does more than simple regenerate-certs IIRC. @pietv any ideas here? & is this blocking #650?

**Comment by pietv** [comment]
@zramsay #650 is not related to --tlsverify error, it turned out.

**Comment by pietv** [comment]
Should be fixed now. The error was due to multiple backends testing on Linux has issues (the fix will be in a separate ticket).
