### ISSUE TITLE
Provide 'download only' command in eris agent

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#620]
The agent's command set should be extended with a "download" POST command which can be invoked with just the IPFS bundle hash as parameter. This command should cover the same functionality of the "install" command when it comes to downloading and unpacking the bundle in ~/.eris/bundles/, but it would not perform the EPM procedure to compile and deploy.
This command should make it easier for clients to only download contract bundles with the intention of building on top of them (i.e. importing into their custom contracts) instead of installing into a chain. This is useful for our "commons" bundles that provide basic building blocks.

**Comment by zramsay** [comment]
if the end point is **only** going to take an IPFS hash as argument (as described above), then it'll go in `~/.eris/bunchles/HASH/HASH.tar`, otherwise, it needs the args to sort path, in which case it takes **all* the same arguments **except** chain and address

**Comment by j-h-scheufen** [comment]
@zramsay Regarding your last comment: you're absolutely right! I assume you implemented it this way that the groupId, bundleId, version are still used for download?

**Comment by zramsay** [comment]
yup
