### ISSUE TITLE
Use HTTP status codes to express errors in agent

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#621]
Before finalizing the agent to be included in the next release, there's one thing I think we should tackle: producing more reliable errors. Currently an error in the agent's procedure is returned as HTTP 200 (OK) but with a string in the body instead of a JSON object. This makes it hard to do efficient error handling on the client side. Solution: HTTP status codes
## Requirements (to be reviewed)
Return the following HTTP codes for matching situations. The error string produced by Eris should still be in the body.
- HTTP 401 (Bad Request) -> If the URL is not correct, e.g. when a required parameter for the command is missing.
- HTTP 403 (Forbidden) -> For authorization problems, e.g. when the provided account key does not exist
- HTTP 404 (Not Found) -> When the specified chain cannot be found. (does not exist or is not running)
- HTTP 500 -> For everything else

**Comment by zramsay** [comment]
from the go http package: `StatusBadRequest = 400` (401 is Unauthorized)

**Comment by zramsay** [comment]
done. to be vetted on PR from `agent` to `develop`
