### ISSUE TITLE
`eris chains restart` 

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#622]
**Problem** -- `eris chains update --pull` isn't the most user-friendly way to do a simple restart of a chain and `eris chains stop name && eris chains start name` is longer than it needs to be.

**Solution** -- add `eris chains restart` which would provide the same functionality as `eris chains update --pull` only in a more concise and user-friendly manner.

**Comment by pietv** [comment]
The `--pull` flag also makes the image to be pulled from Docker hub, the value's not inverted.

Should a simple restart also pull the image?

**Comment by compleatang** [comment]
oh. i thought the default was yes so the flag would be no, but in any event restart should not pull.

**Comment by pietv** [comment]
Roger.
