### ISSUE TITLE
[Chains] Status command

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-cli#623]
It would be good to have a verbose return of analytical parameters regarding the health of your chains for maintenance reasons without having to ssh into each cloud box and run a bunch of diagnostics over and over. I would want to know things like: 
- Last block created (in human readable time) for network.
- Latest block on each chain.
- Bonded status of all validators.
- Quorum status.
- History of nodes connected. (node x last seen when).
- ...

**Comment by AFDudley** [comment]
I agree with this. One of the issues to keep in mind is that in production, this tool can only show 'public' information.

**Comment by pietv** [comment]
Maybe worthwhile to merge with the #571.

**Comment by AFDudley** [comment]
Yeah, it's the same feature basically, I think they should be merged.

**Comment by compleatang** [comment]
Merging with #571:

Should display (ideas):

* currently connected nodes (with validators ID'ed)
* average blocktime

**Comment by zramsay** [comment]
replaced by #1011
