### ISSUE TITLE
Agent thread stops on hard errors

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#624]
Some lower level errors when executing a request in the agent can cause the agent thread to stop.
This needs to be more resilient, so that the agent can keep servicing requests even when a single request fails.
Issue #625 is an example of an error that stops the agent.

**Comment by zramsay** [comment]
this *may* have been fixed since a ton of robustness was added to the error handling in the past couple weeks. advise if still an issue.

**Comment by zramsay** [comment]
@j-h-scheufen reopen if issue appears again.
