### ISSUE TITLE
API error in docker when executing 'agent install' 

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-cli#625]
The following error currently appears when executing an install command
```
Receiving request to install contract bundle
File extension detected, assuming file.
GETing file from IPFS. Hash =>	QmR8DRwVP8ir9Gp3fdyP3S6tnCEp3u57nrTKXGNKpJgWT7:/Users/jan/.eris/bundles/com/erisindustries/commons-financial/0.0.1/QmR8DRwVP8ir9Gp3fdyP3S6tnCEp3u57nrTKXGNKpJgWT7.tar.gz
Downloading http://192.168.99.100:8080/ipfs/QmR8DRwVP8ir9Gp3fdyP3S6tnCEp3u57nrTKXGNKpJgWT7 to /Users/jan/.eris/bundles/com/erisindustries/commons-financial/0.0.1/QmR8DRwVP8ir9Gp3fdyP3S6tnCEp3u57nrTKXGNKpJgWT7.tar.gz
The marmots could not read that package.json. Will use defaults.
API error (404): lstat /mnt/sda1/var/lib/docker/aufs/mnt/43f26e01153320f2fe22b55f72a8c657fd80bf8502348562b63d1f5d71b0fc04/home/eris/.eris/apps/0.0.1: no such file or directory
```
Please investigate

**Comment by zramsay** [comment]
unable to replicate on a fresh ubuntu install. tests that failed yesterday (locally) pass on a DO box. let's prioritize the integration test currently on an old branch in the previous repo; i suspect it'll expose the issue

**Comment by zramsay** [comment]
it's possible the error relates to `aufs`, which can be potentially resolved with `apt-get install linux-image-extra-$(uname -r)` if your installation was on Ubuntu. See the docs [here](https://docs.docker.com/engine/installation/linux/ubuntulinux/) on why that package will allows use of the `aufs` driver

**Comment by zramsay** [comment]
re-open if it comes up again
