### ISSUE TITLE
Improve error message for missing parameter '-c' in pkgs do

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#627]
When running an epm script with 'eris pkgs do' and not specifying the chain parameter '-c' the user is presented with a confusing error:
Error moving keys: API error (500): Cannot link to a non running container: /eris_chain_contracts_de1ce4ac_1 AS /eris_interactive_eris_chain_contracts_de1ce4ac_1/chain

-c or --chain is a mandatory parameter and leaving it out should result in immediate "usage" error.

this is a continuation of this closed issue: https://github.com/eris-ltd/eris-pm/issues/81

**Comment by zramsay** [comment]
onit - it's like 2-3 lines...

**Comment by zramsay** [comment]
closed by #629 & includes `--address` check as well
