### ISSUE TITLE
"hard code" the default service definition which `chains` is using

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#63]
Instead of reading from the `erisdb` service definition file, we'd be better to just set defaults (using Viper's set defaults feature) in the chains package and just let the chain definition file overwrite.

Downsides:

* loose a bit of user customizeability (cause its compiled in)

Upsides:

* less confusion as to what that erisdb service definition is even doing there (cause we don't really want folks just `eris services start erisdb`, it clutters up the services listings too)
* marginally increased performance (as in one file read instead of two... marginal)
* allows us to expunge all of that ugly (mergeChainsAndServices) code
* allows us to fine tune how the chains will be started, installed, etc. with a bit more precision -- this will reduce techDebt with respect to (please `eris services cat erisdb` so that we can debug a problem or whatever). 

Thoughts?

**Comment by compleatang** [comment]
the foundation for this is laed by #69 ... still needs more work though.

**Comment by compleatang** [comment]
closed by #81. 

@ebuchman note we no longer need to maintain an erisdb service per se.... these are built into the tool now and managed by DefaultChain() and Graduate function (can't remember its name now, but I moved it to Loaders).

**Comment by ebuchman** [comment]
Love it.
