### ISSUE TITLE
remove --api flag from chains new|start

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#630]
It's unnecessary and just getting in the way.

**Comment by pietv** [comment]
Removing the `--api` flag makes the Eris PM `app13` test fail. Should the test (and further tests) be modified or delay the change?

**Comment by pietv** [comment]
@VoR0220 could you have a look please why this particular test (`app13`) might fail if the flag `--api` flag is removed from the `chains new` and `chains start` commands?

**Comment by VoR0220** [comment]
@pietv I can take a look on a later day. There are a couple of other tasks that need to take a bit of precedence, but I will get to that during the week.

**Comment by pietv** [comment]
@VoR0220 no rush at all. Thanks!
