### ISSUE TITLE
[Core] Wrapping docker container ssh command into eris cli

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-cli#658]
Feature request to go along with chain maintenance tools: would possibly be good to have an `eris remotes ssh —machine xxxxx` command to wrap `docker exec -it -u 0 [container id] bash`

**Comment by zramsay** [comment]
@slowtokyo would this still be useful to your workflow?

**Comment by slowtokyo** [comment]
Hmm, I think it's not really that important frankly. I think that it just feels omitted and that it would be part of the Eris stack since you want to bundle the useful bits of different services. However day2day, don't see it being a big part of the stack and you guys are trying to simplify the CLI anyway. I would lean towards closing.

**Comment by zramsay** [comment]
Thanks for the reply. We can revisit in the future if need be.
