### ISSUE TITLE
auto eris clean daemon?

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-cli#662]
One of the most irritating things in testing is the error for eris being unable to move to a non running container. Would it be possible to create a daemon that sets Eris to auto clean its boards whenever its scratch data whenever its near full?

**Comment by compleatang** [comment]
This could lead to weird side effects. Am not sure this is a good idea. @VoR0220 can you explain your thinking here a bit more.

**Comment by VoR0220** [comment]
it's a tad of selfish reasoning. Call it developer mode...set it to clean blocks automatically every time the chain reaches the outer parameters of the docker container in size, and then you have less moving key errors going forward and more time spent testing.

**Comment by AFDudley** [comment]
This is not a product feature, just write a script that does this.

**Comment by VoR0220** [comment]
fair
