### ISSUE TITLE
[Core] cleaner/more consistent way of handling `--all` && `--quiet`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#668]
most commands are lacking this flag, which would be useful in a few cases. Also, when it is used (e.g. clean), it's not very portable. I'm thinking something like:
```
if do.All {
   // make a map with some info on all the flags to be set to true
   // and their logs messages
   bools := util.SetAllToTrue(map) // which would also prompt the (y/n)
  // then set all the do.Flags from bools
}
```

**Comment by zramsay** [comment]
`eris chains/services ls -q` would be fantastical (see #766)

**Comment by pietv** [comment]
@zramsay `eris services/chains ls -q` commands are implemented. `eris ls -q` doesn't, because it wouldn't be able to differentiate types.

**Comment by zramsay** [comment]
epic. totally missed that :)

**Comment by compleatang** [comment]
is this still a live issue?

**Comment by zramsay** [comment]
no. can close for now & revisit later if need be.
