### ISSUE TITLE
build container number automagician to find a new free containerNumber

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#67]
will require some massaging of the container naming regex

**Comment by compleatang** [comment]
the foundation for names and containerNumber should be all set. 

two things need to happen:

* need to add a bit of autoMagic to the containerNumbers (as in if no containerNumber is given, find the first free container number)
* need to hook up from the Flag parsing step to the Load/Mock step

... then we should be good.

@zramsay I think this will be a good one for you. see also my comments on #69 (first bullet point in chains i think).

**Comment by compleatang** [comment]
There are a couple of ways to do this. We probably want to build this automagician to run during the Ops overwrite functionality when the operations struct which is assembled by the CLI level is used to override any default operations populated during the loading process:

https://github.com/eris-ltd/eris-cli/blob/develop/services/services_test.go#L106

The function should check to see if ContainerNumber is 0||nil and if it is, it should set it to 1 for now. We may want to add in a bool that will tell the function whether it should be unique (this is a new service container) or whether it should use the highest number found (for when we need to find an existing container, like for stopping and such)

**Comment by zramsay** [comment]
TODO
https://github.com/eris-ltd/eris-cli/blob/develop/commands/services.go#L325
 (still not sure if mod to BuildServicesGroup is legit).

**Comment by zramsay** [comment]
^nvm, already taken care of.
