### ISSUE TITLE
Additions to the release workflow

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/eris-cli#696]
Problem:
The images we provide in the AWS and Azure Marketplaces are manually created and any tests we run on them are ad-hoc.

Solution:
Add packer based image creation  and image testing to our release process. Packer natively supports the clouds we currently target (AWS, Azure, Digital Ocean) and has support for others.

Discussion:
Here is my suggestion for order of events during a release. (We tag development because we are not using release branches as suggested here: http://nvie.com/posts/a-successful-git-branching-model/)

Tag commit with release number in develop.
Test.
Pass tests.
Apply PR to master.
Test again.
Build packages (windows, linux distros, osx)
Build and push docker image
Build and push cloud images (AWS, DO, Azure)

I am open to suggestion about how to best go about this work. I will be working on the image creation scripts in my fork.

**Comment by compleatang** [comment]
relates to #586.

**Comment by compleatang** [comment]
this issue is fully covered in many various operations issues. closing here as it isn't really an repo concern, rather an ops concern.
