### ISSUE TITLE
[Pkgs] remove `--rm-data` from pkgs do flags

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#705]
or fix it. since the move away from using data directories it no longer does what it says on the tin.

**Comment by zramsay** [comment]
@VoR0220 this looks like this closes it?
https://github.com/eris-ltd/eris-cli/commit/0722f6a0f4edf4170bed799389ee4c6fa6413396

**Comment by VoR0220** [comment]
Did that branch get merged? I'm unaware. But yes it does look like this closes it.

**Comment by zramsay** [comment]
removed in #1083
