### ISSUE TITLE
eris chains new exits with status 1, complains it can't find quay.io/eris/data:latest

### ISSUE THREAD

**Issue by edmundedgar** [eris-ltd/eris-cli#732]
I'm setting up a chain on MS Azure, broadly following the instructions here 
https://docs.erisindustries.com/tutorials/advanced/chain-maintaining/

I can deploy a machine with:
docker-machine create "$machine_base-$i" --driver "$driver" --azure-subscription-id "$mysubscriptionid" --azure-resource-group "$myrg" --azure-location "japaneast" --azure-vnet "$mynetwork" --azure-subnet "$mysubnet" --azure-subnet-prefix "mysubnetrange" --azure-image "Canonical:ubuntuserver:16.04.0-LTS:16.04.201605161" --azure-no-public-ip

When I get to this part:
eris chains new --dir $chain_name/"$chain_name"_validator_00"$i" --machine "$machine_base-$i" $chain_name
...it exits with status 1 trying to pull erisdb.

Looking at the syslog of the VM I see:
Handler for POST /containers/create returned error: No such image: quay.io/eris/data:latest

I found I can work around this by running eris init on the VM first, eg
docker-machine eris init --machine my-machine-0

After that, I can rerun the eris chains new command and it completes successfully, and I can get the chain running and making blocks.

---
eris version: Eris CLI Version: 0.11.4
docker -v: Docker version 1.11.1, build 5604cbe

**Comment by zramsay** [comment]
hi @edmundedgar. Can you try `docker pull quay.io/eris/data:latest`? then re-run the command. This _could_ fix the issue, although I suspect it may be related to the move to alpine as base, which *just* occured.

**Comment by zramsay** [comment]
My suggestion probably won't fix your issue, however, I've identified the problem and will have a fix in < hour.

**Comment by edmundedgar** [comment]
@zramsay Thanks, I'm assuming I'm supposed to run docker pull quay.io/eris/data:latest on the machine I'm running the command from, rather than SSHing into the VM I'm deploying and running it there. 

Tried it, no difference:

The Docker image is not found locally
                                        image=quay.io/eris/data
The marmots are approved to pull it from the repository on your behalf
This could take a few minutes
The Docker image is not found locally
                                        image=quay.io/eris/base
The marmots are approved to pull it from the repository on your behalf
This could take a few minutes
Container interactive-d06f787b-bc2a-44b0-8136-2448603f77f0 exited with status 1


...then on the VM I'm trying to deploy I see:

grep eris syslog 
Jun  3 00:23:20 ubuntu docker[5131]: time="2016-06-03T00:23:20.998884837Z" level=error msg="Handler for POST /containers/create returned error: No such image: quay.io/eris/data:latest"
Jun  3 00:23:45 ubuntu docker[5131]: time="2016-06-03T00:23:45.555765125Z" level=error msg="Handler for POST /containers/create returned error: No such image: quay.io/eris/base:latest"

**Comment by zramsay** [comment]
after creating your remote machine on azure, did you run `eris init --machine=$machine_base-$i` ?
you'll either need to use the machine flag or run `eval "$(docker-machine env $machine_base-$i)"` to put that machine's docker-client in scope.

**Comment by edmundedgar** [comment]
Like I say if I run
> eris init --machine=$machine_base-$i
before running eris chains new that fixes the problem: Having done that I can run 
> eris chains new --dir $chain_name/"$chain_name"_validator_00"$i" --machine "$machine_base-$i" $chain_name
...and it completes without error and life is wonderful.

**Comment by zramsay** [comment]
:+1: that's exactly how it should work. eris needs to be initialized before doing anything

**Comment by edmundedgar** [comment]
OK, I'm not seeing the eris init step run for each vm in here:
https://docs.erisindustries.com/tutorials/advanced/chain-maintaining/
...so maybe it's a document bug?

**Comment by zramsay** [comment]
could be. however, the line `export ERIS_PULL_APPROVE="true"` should actually pull the images if necessary in which case that's a bug in eris-cli. It could also be an issue with the images themselves as there was some instability today with the transition to alpine (on develop). I'll investigate further but in the meantime you can run with init.

**Comment by edmundedgar** [comment]
Makes sense, thanks.

**Comment by zramsay** [comment]
this should be fixed now, especially since the data image is properly sorted. re-open if issue is encountered again.
