### ISSUE TITLE
Account addresses missing from genesis block when querying the chain

### ISSUE THREAD

**Issue by stevebakh** [eris-ltd/eris-cli#734]
Hi there,

I've just started playing with Eris and ran into a small problem. I followed the basic tutorial to create a chain with 3 users (2 root users and 1 full to validate), however, when I ran an EPM file which attempted to set a custom role on an account, it complained that the account was unknown. The address definitely exists in the `~/.eris/chains/<name>/accounts.json` and `~/.eris/chains/<name>/addresses.csv` files. It can even be found in the `~/.eris/chains/throwaway/throwaway_full_000/genesis.json` file. Sadly, checking the genesis block _in_ the chain returns different results.

The investigation led me to believe there's some kind of bug. 

### Steps to reproduce
1. `eris services start keys`
2. `eris chains make --account-types=Root:2,Full:1 throwaway`
3. `eris chains new throwaway`
4. Running `eris chains cat throwaway genesis` shows 5 (?) accounts, and only the full account address looks like a real address (although it isn't the correct account), with other account addresses comprising all 0s with one digit difference at the end. See example:

```
$ eris chains cat throwaway genesis
{
  "chain_id": "throwaway",
  "accounts": [
    {
      "address": "0000000000000000000000000000000000000001",
      "amount": 690000000000
    },
    {
      "address": "0000000000000000000000000000000000000002",
      "amount": 565000000000
    },
    {
      "address": "0000000000000000000000000000000000000003",
      "amount": 525000000000
    },
    {
      "address": "0000000000000000000000000000000000000004",
      "amount": 110000000000
    },
    {
      "address": "37236DF251AB70022B1DA351F08A20FB52443E37",
      "amount": 999999999999
    }
  ],
  "validators": [
    {
      "pub_key": [
        1,
        "CB3688B7561D488A2A4834E1AEE9398BEF94844D8BDBBCA980C11E3654A45906"
      ],
      "amount": 5000000000,
      "unbond_to": [
        {
          "address": "37236DF251AB70022B1DA351F08A20FB52443E37",
          "amount": 5000000000
        }
      ]
    }
  ]
}
```

### Versions
* docker 1.11.1
* docker-machine 0.7.0
* eris 0.11.4
* OS: OSX 10.11.5 (el cap)

**Comment by stevebakh** [comment]
I just ran a few more experiments and it seems I may have jumped the gun! Running `eris chains new <name>` will just use the default genesis by default. Silly mistake on my part.

**Comment by zramsay** [comment]
@stevebakh this part is admittedly a tad confusing. We'll be adding a check that the `--dir` flag has been passed on `eris chains new` in an upcoming release since the feature of assuming the named directory really only works for single validator chains.
