### ISSUE TITLE
Unable to run eris pkgs do passing a specific EPM file

### ISSUE THREAD

**Issue by stevebakh** [eris-ltd/eris-cli#735]
I am unable to run an EPM file other than the default "./epm.yaml". When attempting to pass the `--file` flag, I get the following error: 

```
Sorry, the marmots were unable to load the eris-pm jobs file. Please check your path.
ERROR =>			Unsupported Config Type ""
```

I'm guessing the underlying command allows one to define the config type (json, yaml, etc) but there doesn't appear to be a flag to do this when calling `eris pkgs do ...` and it doesn't seem to default to yaml.

### Steps to reproduce
1. Create a basic EPM with a filename `init.yaml`. Make sure there is no `epm.yaml` in the same directory.
2. `eris pkgs do --file "./init.yaml" --chain testchain --address $ADDR`
3. See error output.

Renaming the file to `epm.yaml` and running the command again without the `--file` flag will run the file as expected.

**Note:** I've tried using both relative and absolute file paths.

### Versions
* docker 1.11.1
* docker-machine 0.7.0
* eris 0.11.4
* OS: OSX 10.11.5 (el cap)

**Comment by pietv** [comment]
@stevebakh thank you for reporting the issue and for excellent explanation. 

This is a known bug currently being fixed (#120), please follow that. I will close this issue in preference for that one, since it is a duplication.
