### ISSUE TITLE
Created AWS EC2 instances are not properly cleaned

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#738]
See Travis build 1151 https://travis-ci.org/eris-ltd/eris-cli/builds/135295416

The AWS EC2 instances should be cleaned automatically, regardless of whether tests passed or failed.

**Comment by pietv** [comment]
```
Launching instance... Error creating machine: Error in driver during machine creation: Error launching instance: InstanceLimitExceeded: Your quota allows for 0 more running instance(s). You requested at least 1
```

**Comment by AFDudley** [comment]
https://travis-ci.org/eris-ltd/eris-cli/jobs/135295417#L187

I don't think the issue is in from this repo, since this is the one I fixed and tested. I'm pretty sure it's in another repo. The maintainers of those repos should be blamed for their tests not properly cleaning up, but we need to see what instances are left over to do that.

**Comment by pietv** [comment]
I don't want to think which repo that is, I'd like the infrastructure to clean up after any repo whether it's failed or succeded.

**Comment by AFDudley** [comment]
We have had this discussion on slack before.

How will "the infrastructure" know what can be safely removed? The scripts have all the information required to clean up after themselves, and to my knowledge the scripts in this repo actually do that, if you can prove to me that they don't, which this ticket fails to do, I will happily fix the existing scripts.

**Comment by pietv** [comment]
That was your assignment to clean the AWS in the first place. You can guess (and your script currently use that information) which machine is being created by the current test. So, fix this by inserting your script in the places it will run every time, bug or not.

**Comment by AFDudley** [comment]
In the example you provide the scripts runs, here is the line where it shows it ran:
https://travis-ci.org/eris-ltd/eris-cli/jobs/135295417#L187

**Comment by pietv** [comment]
I don't care whether it has run. I don't want to see this message: "Error creating machine: Error in driver during machine creation: Error launching instance: InstanceLimitExceeded: Your quota allows for 0 more running instance(s). You requested at least 1"

**Comment by compleatang** [comment]
handled via new CI system. the ec2 instances when i checked had been reaped...

**Comment by pietv** [comment]
There's no functional Ci system yet. The EC2 instances are not reaped in case of test or connectivity failures.

**Comment by compleatang** [comment]
Fair to keep open until new CI system implemented. But let's just reap these by hand if it overflows again; it takes five minutes. Not worth the resources to automate unless CI system drastically delayed.

**Comment by pietv** [comment]
:+1:
