### ISSUE TITLE
`eris pkgs do` compiler error of 0.12.0 version compier

### ISSUE THREAD

**Issue by shuangjj** [eris-ltd/eris-cli#751]
Error log: `encoding/hex: odd length hex string`
Related to the workaround https://github.com/eris-ltd/eris-cli/pull/719/files as in cmd/pkgs_arm.go

**Comment by VoR0220** [comment]
fixed in rc2

**Comment by zramsay** [comment]
@VoR0220 link to what commit/PR fixed this?

**Comment by VoR0220** [comment]
https://github.com/eris-ltd/eris-compilers/pull/63
