### ISSUE TITLE
Eris tutorial exception: Maintaining your Permissioned Chain, Maintenance Task 1: Adding Actors

### ISSUE THREAD

**Issue by zephyrDK** [eris-ltd/eris-cli#758]
Please include in your bug report:

see below:

blockchain1@ubuntu:~/.eris/keys/data$ eris chains exec xchain -- mintx permission set_base $new_addr call true --addr $root_addr --sign-addr=172.17.0.2:4767 --node-addr=172.17.0.3:46657 --chainID xchain --wait --broadcast --debug
Sending request body (http://172.17.0.2:4767/pub): {"addr":"ECAB9F4C7C6690E8A9A43D914DD69103A6CC37F4"}
encoding/hex: odd length hex string
Container interactive-aa4bed81-6d83-44f5-aa05-25bdf8ff6682 exited with status 1

- [Client/Server: 1.11.1] `docker version`
- [Eris CLI Version: 0.11.4 ] `eris version`
- [go version go1.5.4 linux/amd64 ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [ubuntu 14.04 trusty ] operating system details (osx/windows/linux)
- [ ] what you expected to happen
- [ ] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by pietv** [comment]
@zephyrDK thank you for reporting the issue! I'll try to reproduce the issue and will come up with a fix or an advise: right now the command from the tutorial returns 
```
Sending request body (http://keys:4767/pub): {"addr":"4337AB9957F2634A34C3E2CD76819E55E928D018"}
unknown account 4337AB9957F2634A34C3E2CD76819E55E928D018
```
but I'll try to figure out what's missing.

I have to questions for you regarding that error:
1. The `encoding/hex: odd length hex string` error means that the key string length is not divisible by 2. Can you please check that both `$root_addr` and `$new_addr` have the length 40, like this:
```
$ echo $new_addr|fold -w1|wc -l
$ echo $root_addr|fold -w1|wc -l
```

2. The tutorial command uses hosts aliases (`--sign-addr=keys:4767`) and you in the above sample used IPs (`--sign-addr=172.17.0.2:4767`). Why? Did aliases didn't work for you or the command behaves differently? If so, how?

Thank you!

**Comment by zephyrDK** [comment]
thank you for your prompt reply! 
for the question 1: 
i execute the command, and the results are as below:
blockchain1@ubuntu:~/.eris/keys/data$ echo $new_addr
349840DF2111EF6AD2F426E2D0ABFBF56DBF0619
blockchain1@ubuntu:~/.eris/keys/data$ echo $root_addr
ECAB9F4C7C6690E8A9A43D914DD69103A6CC37F4
blockchain1@ubuntu:~/.eris/keys/data$ echo $new_addr |fold -w1|wc -l
40
blockchain1@ubuntu:~/.eris/keys/data$ echo $root_addr|fold -w1|wc -l
40

for the question 2, my keys service is deployed on the docker container, as below:
blockchain1@ubuntu:~/.eris/keys/data$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                          NAMES
4967fc61ae82        quay.io/eris/erisdb:0.11.4   "erisdb-wrapper new"     5 days ago          Up 2 days           0.0.0.0:1337->1337/tcp, 0.0.0.0:46656-46657->46656-46657/tcp   xchain-4a276b4f-f437-4d3f-bee2-ac8d3ac8779c
2a0ed5a1e544        quay.io/eris/keys            "eris-keys server --h"   5 weeks ago         Up 2 days           4767/tcp                                                       keys-98ab6f09-6e0a-4c03-a673-c541e3d51905
blockchain1@ubuntu:~/.eris/keys/data$ docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2a0ed5a1e544
172.17.0.2
the IP addr (172.17.0.2) could access the keys service, so I didn't add this addr to  the hosts aliases config file.

**Comment by pietv** [comment]
@zephyrDK thank you for your answers and for the feedback. yes, indeed, editing and running actions is essentially read-only operations, so couldn't affect the `exec mintx` command. It could have been a typing or copy-pasting issue.
