### ISSUE TITLE
eris init is stuck on OS X (EI Capitan) while downloading docker image

### ISSUE THREAD

**Issue by praveennagpal** [eris-ltd/eris-cli#761]
Please include in your bug report:

- [ ] `docker version`
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

- [ ] `eris version`
Eris CLI Version: 0.11.4

- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [ ] operating system details (osx/windows/linux)
osx
- [ ] what you expected to happen
all docker images should get downloaded to my local vm
- [ ] what actually happened
i had a power failure (network disconnection) when it was downloading first time. Now, even after network connectivity, i am trying to do iris init, the downloader is stuck at the same position and is not downloading. i restarted with the docker toolbox but still stuck.

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/



~ praveennagpal$ eris init
Eris root directory                      path=/Users/praveennagpal/.eris
Continuing may overwrite files in
                                 actions path=/Users/praveennagpal/.eris/actions
                                  chains path=/Users/praveennagpal/.eris/chains
                                services path=/Users/praveennagpal/.eris/services
Do you wish to continue? (y/n): y

WARNING: Approximately 1 gigabyte of Docker images are about to be pulled
onto your host machine. Please ensure that you have sufficient bandwidth to
handle the download. For a remote Docker server this should only take a few
minutes but can sometimes take 10 or more. These times can double or triple
on local host machines. If you already have the images, they'll be updated.

Skip confirmation with      ERIS_PULL_APPROVE=true

Do you wish to continue? (y/n): y

Pulling default Docker images from quay.io
Pulling image 1 out of 7                image=quay.io/eris/base
latest: Pulling from eris/base

fdd5d7827f33: Downloading [=============================>                     ] 30.81 MB/51.37 MB
a3ed95caeb02: Download complete 
0f35d0fe50cc: Download complete 
7b40647e93b7: Downloading [=============================>                     ] 24.81 MB/42.5 MB
ef089453c5ae: Downloading [====>                                              ] 5.935 MB/61.96 MB
9d2ddf3bfeaa: Waiting 
4dab041c7a7c: Waiting 
d68f93c79fed: Waiting 
0d82a1645bac: Waiting 
9eedcd03db3d: Waiting 
1c8a6ceb63e8: Waiting 


- [ ] steps to reproduction
mentioned above

If issue is a feature request, tell us why this feature is useful.

**Comment by pietv** [comment]
Hi, @praveennagpal! Thank you for reporting the issue! Please, could you try running `eris init` again? The likely cause of the issue is that the image has been updated while you were pulling it, and that's why it's stuck (We've been releasing a release candidate this evening).

**Comment by praveennagpal** [comment]
I have tried again but still stuck at the same point.

Eris root directory                      path=/Users/praveennagpal/.eris
Continuing may overwrite files in
                                 actions path=/Users/praveennagpal/.eris/actions
                                  chains path=/Users/praveennagpal/.eris/chains
                                services path=/Users/praveennagpal/.eris/services
Do you wish to continue? (y/n): y

WARNING: Approximately 1 gigabyte of Docker images are about to be pulled
onto your host machine. Please ensure that you have sufficient bandwidth to
handle the download. For a remote Docker server this should only take a few
minutes but can sometimes take 10 or more. These times can double or triple
on local host machines. If you already have the images, they'll be updated.

Skip confirmation with      ERIS_PULL_APPROVE=true

Do you wish to continue? (y/n): y

Pulling default Docker images from quay.io
Pulling image 1 out of 7                image=quay.io/eris/base
latest: Pulling from eris/base
fdd5d7827f33: Downloading [=============================>                     ] 30.81 MB/51.37 MB
a3ed95caeb02: Download complete 
0f35d0fe50cc: Download complete 
7b40647e93b7: Downloading [=============================>                     ] 24.81 MB/42.5 MB
ef089453c5ae: Downloading [====>                                              ] 5.935 MB/61.96 MB
9d2ddf3bfeaa: Waiting 
4dab041c7a7c: Waiting 
d68f93c79fed: Waiting 
0d82a1645bac: Waiting 
9eedcd03db3d: Waiting 
1c8a6ceb63e8: Waiting 
^[[A

**Comment by pietv** [comment]
@praveennagpal  I see. can you try to remove that eris image manually with the `docker rmi -f quay.io/eris/base:latest` command or better yet, remove all images you downloaded (in case you only use Docker right now for eris) with `docker rmi -f $(docker images -q)`? 

As an alternative, you can try to download the latest release binary from here and work with that: https://github.com/eris-ltd/eris-cli/releases/download/v0.12.0-rc1/eris_0.12.0_darwin_amd64

```
wget https://github.com/eris-ltd/eris-cli/releases/download/v0.12.0-rc1/eris_0.12.0_darwin_amd64
mv eris_0.12.0_darwin_amd64 eris
chmod +x eris
```

(I've just used the version 0.11.4 to pull all of the images from scratch, it worked as expected. It can be a regional quay.io glitches.)

**Comment by praveennagpal** [comment]
There is no docker image left.

Praveens-MacBook-Pro:bin praveennagpal$ docker images -q
Praveens-MacBook-Pro:bin praveennagpal$ 
But still the same issue persists.

I did use homebrew commands earlier on Mac below which ran successfully.
brew update
brew install iris 

Do I still need to install the binary on github now?
https://github.com/eris-ltd/eris-cli/releases/download/v0.12.0-rc1/eris_0.12.0_darwin_amd64

Apologies, as I am a bit confused with the steps involved. What is eris init actually doing and when do we need to run it?

**Comment by pietv** [comment]
Thank you for trying this! Yes, `eris init` initializes files (default blockchains setting and a selection of services you'll be able to run) in your `$HOME/.eris` directory and pulls a few Docker images necessary to run blockchains on your machine.

Yes, please try running the binary from that link instead of the one pulled with `brew install`.

Not, at all. Thank you for letting us know you have issues.

**Comment by praveennagpal** [comment]
I have installed the new binary from the link but still getting stuck. This time, at a different image.

Praveens-MacBook-Pro:~ praveennagpal$ eris init
Eris root directory                      path=/Users/praveennagpal/.eris
Continuing may overwrite files in
                                 actions path=/Users/praveennagpal/.eris/actions
                                  chains path=/Users/praveennagpal/.eris/chains
                                services path=/Users/praveennagpal/.eris/services
Do you wish to continue? (y/n): y

WARNING: Approximately 1 gigabyte of Docker images are about to be pulled
onto your host machine. Please ensure that you have sufficient bandwidth to
handle the download. For a remote Docker server this should only take a few
minutes but can sometimes take 10 or more. These times can double or triple
on local host machines. If you already have the images, they'll be updated.

Skip confirmation with      ERIS_PULL_APPROVE=true

Do you wish to continue? (y/n): y

Pulling default Docker images from quay.io
Pulling image 1 out of 6                image=quay.io/eris/data
0.12.0: Pulling from eris/data
0f4cd5c119fc: Waiting 
4e45e9290acd: Waiting 
c6f6c496e7c7: Waiting 
4fcab26aaa4b: Waiting 
3403eec742e6: Waiting 
10bc7cbdf6ea: Waiting 
a3ed95caeb02: Waiting

**Comment by pietv** [comment]
Hi @praveennagpal, yes this is unfortunate. Sorry you're experiencing this. `quay.io` server likely have issues on its own, but it makes sense to repeat the operation after some time.

I suggest you pull all 6 images manually (and see if they stuck for you as well):
```
$ docker pull quay.io/eris/data:0.12.0
$ docker pull quay.io/eris/keys:0.12.0
$ docker pull quay.io/eris/erisdb:0.12.0
$ docker pull quay.io/eris/quay.io/eris/epm:0.12.0
$ docker pull quay.io/eris/eris-cm:0.12.0
$ docker pull quay.io/eris/ipfs
```

Please, can you tell how much time do you usually allow before deciding it is stuck? You should allow ~5 minutes on average. Thanks.

**Comment by praveennagpal** [comment]
The only thing I did was to restart the Virtual Box VM and this time the eris.init worked and I was able to download all 6 images. Thanks for your help.

**Comment by pietv** [comment]
Thank you for the update. That means this isn't a `quay.io` issue after all, thanks.
