### ISSUE TITLE
Automated version bump PRs to Homebrew on Jenkins

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#765]
Automate Homebrew formula update, testing, and pushing on merge to #master in Jenkins.

**Comment by compleatang** [comment]
moving to operations.

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/operations #46](https://github.com/eris-ltd/operations/issues/46) via [**ZenHub**](https://www.zenhub.com/)
