### ISSUE TITLE
[Core] One click shutdown/startup for dev machines

### ISSUE THREAD

**Issue by slowtokyo** [eris-ltd/eris-cli#766]
Can we have a one click roll up/down? Like `eris startup` `eris shutdown`? It would be handy for dev machines where you want to end a marmoty day of dev and gracefully shutdown everything and return the next day in the same state. I think that it would just wrap `eris services stop xxxxx` and `eris chains stop xxxx` and vice-versa against all running containers.

**Comment by zramsay** [comment]
This could be useful and is something to consider. Note that docker is rolling out a bunch of new features (see `docker service`in the rc) while slowly deprecating some others, so what we do here may be a moving target for some time. Not sure what we're doing with the planned `remotes` either, which is also related to starting up/shutting down. In the meantime, how about:
```bash
eris services stop $(eris services ls -f '{{.ShortName}}')
eris chains stop $(eris chains ls -f '{{.ShortName}}')
```
in the evening and `s/stop/start` in the morning?

**Comment by zramsay** [comment]
`-q`  is in a fact available, so 
```
eris services stop $(eris services ls -q)
eris chains stop $(eris chains ls -q)

**Comment by zramsay** [comment]
since @slowtokyo will be working on a PR for this feature, we need to settle on some command names. my two cents is `eris start | stop` for harmony with sub-commands. unless there is dissent, let's go with that

**Comment by slowtokyo** [comment]
WIP. Two fixes needed before issue is complete (will try to get around to fixing it in the next week):

- There is still an error when `eris startup --chain [chainName]` that doesn't start up logspout even though it is possible to start it regularly with `eris services start logspout`. 

- There is an error in `eris shutdown` where the chain names are found but are not passed properly into the `KillChain` function.

**Comment by slowtokyo** [comment]
Finished this and ready to do PR. Can't seem to find the branch on eris's eris-cli any longer. Mine is available at: https://github.com/slowtokyo/eris-cli/tree/eris-start-stop-766. 

NB: there is a known issue where logspout does not start as expected even if a previous container already exists. All other services I have tested start fine though.

**Comment by zramsay** [comment]
closing per last comment in #911
