### ISSUE TITLE
Test Eris packages installations on virtual machines with various OSs

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#768]
Test `apt-get install eris`, `yum install eris-cli`, and `brew install eris`:
* install `eris`, `docker`, and `docker-machine` binaries, set `docker` user groups
* able to create a virtual machine in VirtualBox on Linux and Mac
* able to connect to Docker (with and without VirtualBox set up on Linux)

For a selection of operating systems:
* Ubuntu 15.04
* Ubuntu 14.04
* Debian jessie
* Debian stretch
* Centos 7
* Centos 6
* Fedora 23
* Fedora 22
* Mac OS X El Capitan

Run the test after the merge to master (release script step).

**Comment by pietv** [comment]
@AFDudley following our conversation about what things better to do on Jenkins, assigning this to you.

**Comment by AFDudley** [comment]
Issue moved to [eris-ltd/operations #33](https://github.com/eris-ltd/operations/issues/33) via [**ZenHub**](https://www.zenhub.com/)
