### ISSUE TITLE
Test Maintenance Task 1: Adding Actors，unknown exit.

### ISSUE THREAD

**Issue by zephyrDK** [eris-ltd/eris-cli#769]
Please include in your bug report:
@pietv , hi, this time i have encountered an unknown exit when try "Maintaining your Permissioned Chain -- Maintenance Task 1: Adding Actors" 
the command has been executed, but  after several blocks generated, it encountered error waiting for event: timed out waiting for event. the detail is as follows:

blockchain1@ubuntu:~$ eris chains exec kchain -- mintx permission set_base 19EC156243F32334B8300647D634399E8C0427B4 call true --addr $root_addr --sign-addr=keys:4767 --node-addr=172.17.0.3:46657 --chainID kchain --wait --broadcast --debug
Sending request body (http://keys:4767/pub): {"addr":"B6C28D28D4AC021657F43E32005CFB6216DC4208"}
NOTE[06-23|03:22:42] Starting WSClient                        module=core_client impl=WSClient
Websocket Address ws://172.17.0.3:46657/websocket
Waiting for tx to be committed ...
Block{
  Header{
    ChainID:        kchain
    Height:         1175
    Time:           2016-06-23 03:22:42.426 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  E7F8454B37FB9F8363F8CB4857C2FC1698FB4134
    LastBlockParts: PartSet{T:1 9BEC8FDC504D}
    StateHash:      B887B5AE5A0737A653083094D4AF7D089085F3EC
  }#5A37AA0C1CED6061AA9220B67818252DBD234F1D
  Data{
    
  }#
  Validation{
    Precommits: Vote{1174/00/2(Precommit) E7F8454B37FB#PartSet{T:1 9BEC8FDC504D} /9ED7A9DEC788.../}
    Vote{1174/00/2(Precommit) E7F8454B37FB#PartSet{T:1 9BEC8FDC504D} /534417E66829.../}
    Vote{1174/00/2(Precommit) E7F8454B37FB#PartSet{T:1 9BEC8FDC504D} /8AFA0D112C07.../}
  }#
}#5A37AA0C1CED6061AA9220B67818252DBD234F1D
Block{
  Header{
    ChainID:        kchain
    Height:         1176
    Time:           2016-06-23 03:22:44.773 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  5A37AA0C1CED6061AA9220B67818252DBD234F1D
    LastBlockParts: PartSet{T:1 63834EBDBA63}
    StateHash:      4A332EF3CFCE7B724C12D93D4F661C8CFC2C80BF
  }#884C1285869234453D0FC1A9D3C1D1639612DCB4
  Data{
    
  }#
  Validation{
    Precommits: Vote{1175/00/2(Precommit) 5A37AA0C1CED#PartSet{T:1 63834EBDBA63} /AF5419222A9E.../}
    Vote{1175/00/2(Precommit) 5A37AA0C1CED#PartSet{T:1 63834EBDBA63} /F18D35914A29.../}
    Vote{1175/00/2(Precommit) 5A37AA0C1CED#PartSet{T:1 63834EBDBA63} /A28FAC23D4BD.../}
  }#
}#884C1285869234453D0FC1A9D3C1D1639612DCB4
Block{
  Header{
    ChainID:        kchain
    Height:         1177
    Time:           2016-06-23 03:22:47.273 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  884C1285869234453D0FC1A9D3C1D1639612DCB4
    LastBlockParts: PartSet{T:1 9D4EE0802B33}
    StateHash:      EFB9CA4A9EE5E200164003A9E418426BBBA4419B
  }#45F7E4FC58A9BDF0C74DC15DCFEB506156F844CD
  Data{
    
  }#
  Validation{
    Precommits: Vote{1176/00/2(Precommit) 884C12858692#PartSet{T:1 9D4EE0802B33} /2D2F1F9D6DDF.../}
    Vote{1176/00/2(Precommit) 884C12858692#PartSet{T:1 9D4EE0802B33} /FAE861A428BB.../}
    Vote{1176/00/2(Precommit) 884C12858692#PartSet{T:1 9D4EE0802B33} /6C405B02F283.../}
  }#
}#45F7E4FC58A9BDF0C74DC15DCFEB506156F844CD
Block{
  Header{
    ChainID:        kchain
    Height:         1178
    Time:           2016-06-23 03:22:49.658 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  45F7E4FC58A9BDF0C74DC15DCFEB506156F844CD
    LastBlockParts: PartSet{T:1 339BFF286AD5}
    StateHash:      E703D6E23C6F0E2D3C339FCF5E970364F4BF9889
  }#4AB5D487F82C03A95CC678753F15D049020D8005
  Data{
    
  }#
  Validation{
    Precommits: Vote{1177/00/2(Precommit) 45F7E4FC58A9#PartSet{T:1 339BFF286AD5} /F706837C3779.../}
    Vote{1177/00/2(Precommit) 45F7E4FC58A9#PartSet{T:1 339BFF286AD5} /8E178EEBA3D6.../}
    Vote{1177/00/2(Precommit) 45F7E4FC58A9#PartSet{T:1 339BFF286AD5} /FDE19898ED63.../}
  }#
}#4AB5D487F82C03A95CC678753F15D049020D8005
Block{
  Header{
    ChainID:        kchain
    Height:         1179
    Time:           2016-06-23 03:22:52.02 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  4AB5D487F82C03A95CC678753F15D049020D8005
    LastBlockParts: PartSet{T:1 FDA9F3F79B03}
    StateHash:      0AEAF59D929F99BD5FEAF437AF2E479AF329D5F5
  }#734DE2ED154F084A7160C9D0CCE622D619217611
  Data{
    
  }#
  Validation{
    Precommits: Vote{1178/00/2(Precommit) 4AB5D487F82C#PartSet{T:1 FDA9F3F79B03} /A559DF8380B6.../}
    Vote{1178/00/2(Precommit) 4AB5D487F82C#PartSet{T:1 FDA9F3F79B03} /EB5E94E6A563.../}
    Vote{1178/00/2(Precommit) 4AB5D487F82C#PartSet{T:1 FDA9F3F79B03} /5ADF43C18137.../}
  }#
}#734DE2ED154F084A7160C9D0CCE622D619217611
Block{
  Header{
    ChainID:        kchain
    Height:         1180
    Time:           2016-06-23 03:22:54.449 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  734DE2ED154F084A7160C9D0CCE622D619217611
    LastBlockParts: PartSet{T:1 26CE1F2681BD}
    StateHash:      C2D4C838E4EF86F74FC9AF4A9C51A19FBD8C2E7A
  }#73CE41948F9251E920D3A2D5DF958160C8072C99
  Data{
    
  }#
  Validation{
    Precommits: Vote{1179/00/2(Precommit) 734DE2ED154F#PartSet{T:1 26CE1F2681BD} /9CDFE17B29E2.../}
    Vote{1179/00/2(Precommit) 734DE2ED154F#PartSet{T:1 26CE1F2681BD} /722D149F900E.../}
    Vote{1179/00/2(Precommit) 734DE2ED154F#PartSet{T:1 26CE1F2681BD} /9F8A5D989410.../}
  }#
}#73CE41948F9251E920D3A2D5DF958160C8072C99
Block{
  Header{
    ChainID:        kchain
    Height:         1181
    Time:           2016-06-23 03:22:56.929 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  73CE41948F9251E920D3A2D5DF958160C8072C99
    LastBlockParts: PartSet{T:1 BA423525036A}
    StateHash:      27511C836D9A22F173430D61B5065228E05E4EEF
  }#72B39E36A499E3E4B880223AB1FA453AD48F9DF7
  Data{
    
  }#
  Validation{
    Precommits: Vote{1180/00/2(Precommit) 73CE41948F92#PartSet{T:1 BA423525036A} /0FC4F3B4AEE3.../}
    Vote{1180/00/2(Precommit) 73CE41948F92#PartSet{T:1 BA423525036A} /705A6D6611A1.../}
    Vote{1180/00/2(Precommit) 73CE41948F92#PartSet{T:1 BA423525036A} /1E1AF8047AB1.../}
  }#
}#72B39E36A499E3E4B880223AB1FA453AD48F9DF7
Block{
  Header{
    ChainID:        kchain
    Height:         1182
    Time:           2016-06-23 03:22:59.307 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  72B39E36A499E3E4B880223AB1FA453AD48F9DF7
    LastBlockParts: PartSet{T:1 0DA5B15404AB}
    StateHash:      27FB7A89DF20219CDE2050AA07823760187D8AC5
  }#36485EFC8D417148FD6296C0BE61F2C23BD5663A
  Data{
    
  }#
  Validation{
    Precommits: Vote{1181/00/2(Precommit) 72B39E36A499#PartSet{T:1 0DA5B15404AB} /AC060C3CDA43.../}
    Vote{1181/00/2(Precommit) 72B39E36A499#PartSet{T:1 0DA5B15404AB} /F4127AE15A95.../}
    Vote{1181/00/2(Precommit) 72B39E36A499#PartSet{T:1 0DA5B15404AB} /0D3B4E65316C.../}
  }#
}#36485EFC8D417148FD6296C0BE61F2C23BD5663A
Block{
  Header{
    ChainID:        kchain
    Height:         1183
    Time:           2016-06-23 03:23:01.644 +0000 UTC
    Fees:           0
    NumTxs:         0
    LastBlockHash:  36485EFC8D417148FD6296C0BE61F2C23BD5663A
    LastBlockParts: PartSet{T:1 770C97357D67}
    StateHash:      93AE23DE4886D67436F6CD6CDBCA806B06503C6D
  }#B9051A1907C25F9CD970718959699E25F0AA076E
  Data{
    
  }#
  Validation{
    Precommits: Vote{1182/00/2(Precommit) 36485EFC8D41#PartSet{T:1 770C97357D67} /59815581D090.../}
    Vote{1182/00/2(Precommit) 36485EFC8D41#PartSet{T:1 770C97357D67} /264027C45BB4.../}
    Vote{1182/00/2(Precommit) 36485EFC8D41#PartSet{T:1 770C97357D67} /826FA4F17B05.../}
  }#
}#B9051A1907C25F9CD970718959699E25F0AA076E
Encountered error waiting for event: timed out waiting for event
timed out waiting for event
Container interactive-284d017d-541a-4bd8-b8d2-3ccf0682b858 exited with status 1

- [ Client/Server: 1.11.1] `docker version`
- [ Eris CLI Version: 0.11.4 ] `eris version`
- [ go version go1.5.4 linux/amd64] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [ ubuntu 14.04 trusty] operating system details (osx/windows/linux)
- [ ] what you expected to happen
- [ ] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by compleatang** [comment]
@zephyrDK , @zramsay has been working on a tutorial for this.

**Comment by zramsay** [comment]
@zephyrDK see the tutorial here:
https://docs.erisindustries.com/tutorials/advanced/bond-unbond/

Lmk if that gets you going.

**Comment by zephyrDK** [comment]
@compleatang @zramsay , thanks! I follows this tutorial 
https://docs.erisindustries.com/tutorials/advanced/bond-unbond/, and it works.

**Comment by zephyrDK** [comment]
thanks, it works!






At 2016-07-19 00:04:17, "Zach" <notifications@github.com> wrote:


@zephyrDK see the tutorial here:
https://docs.erisindustries.com/tutorials/advanced/bond-unbond/

Lmk if that gets you going.
