### ISSUE TITLE
[docker 1.12.0-rc2/3] breaks linking/volumes-from via `/etc/hosts`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#780]
Issue first identified by @slowtokyo when Docker for Mac (beta) auto-updated to include `docker version 1.12.0-rc2` and `eris pkgs do...` failed (which requires a linked keys service running). Similar issue identified by @dave-ct in #762 and also encountered by @rguikers. Potentially related to #776. Similar to https://github.com/eris-ltd/eris-keys/issues/45 but different in that `/etc/hosts` wasn't to blame in that case. Note: issue is unrelated to https://github.com/docker/docker/issues/23792.

- [x] `docker version` => `1.12.0-rc2/3`
- [x] `eris version` => `0.11.4/0.12.0`

**Replicate:** (broken on any eris version)
- on `docker version 1.11.2`, run
```
eris services start keys
eris services exec keys -p "cat /etc/hosts"
```
see
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	keys c1c29896f4db keys-540b9182-7050-47e4-b006-9833c9971f91
172.17.0.3 c0ea72c2e90e
```
- on `docker version 1.12.0-rc2` (or rc3), run
```
eris services start keys
eris services exec keys -p "cat /etc/hosts"
```
see
```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.3	7e7c20fc470a
```
Note the missing line required for linking in the latter case. Either way, keys does not work as expected.

**Workaround:** 
- use ip, e.g: 
```
ip=$(eris services inspect keys NetworkSettings.IPAddress)
eris services exec keys "eris-keys gen --host=$ip --no-pass
```
Unfortunately this is not a viable solution for other commands.

**Comment by pietv** [comment]
Fixing this on the Eris side by explicitly setting hostnames on service containers.

**Comment by pietv** [comment]
The issue affects the command `eris keys gen` failing with the `interactive` container exited.

**Comment by zramsay** [comment]
works on `docker version 1.12.0-rc5` & independently with Peter's fix above ^
