### ISSUE TITLE
build & push images that'll go to dockerhub

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#782]
for resilience
- because https://github.com/docker/docker/issues/23792 could be problematic
- this line is also pointless if we haven't pushed recent images to the hub: https://github.com/eris-ltd/eris-cli/blob/2e20d78b5695e0b38ee0542ba3e9a4e48b7c88d9/initialize/writers.go#L154
- related to #763, #767

**Comment by AFDudley** [comment]
Given this: https://github.com/docker/docker/issues/23792#issuecomment-232920904

Can we close this issue? I don't entirely understand it. Is there another reason we would need to support pushing to both quay.io and dockerhub?

**Comment by zramsay** [comment]
to be handled by ops
