### ISSUE TITLE
harmonize docker image names

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#783]
only `eris-cm` matches the repo name & the other images have no consistency between them.
```
eris/keys
eris/erisdb
eris/epm
eris/eris-cm
```

ideas:
```
eris/ekeys
eris/edb
eris/epm
eris/ecm
```
or match repo names identically:
```
eris/eris-keys
eris/eris-db
eris/eris-pm
eris/eris-cm
```

**Comment by zramsay** [comment]
related to & can happen at same as #782

**Comment by zramsay** [comment]
+2 for matching repo names. Eventually we'll want to match the username with the GH org name

**Comment by pietv** [comment]
:+1: for `eris-*` over `e*` everything if there's a reason not to drop the `eris-` from the image name (`eris/eris/*` is duplicated).

**Comment by AFDudley** [comment]
we should remove the `eris-`

**Comment by compleatang** [comment]
I agree with Rick here. Both the repos and the docker image names should be changed imv.

Repos:

```
github.com/eris-ltd/eris-cli -> github.com/eris-ltd/cli
github.com/eris-ltd/eris-compilers -> github.com/eris-ltd/compilers
etc.
```

Docker Images:

```
quay.io/eris/epm -> quay.io/eris/pm
quay.io/eris/eris-cm -> quay.io/eris/cm
quay.io/eris/erisdb -> quay.io/eris/db
etc.
```

**Comment by benjaminbollen** [comment]
I want to offer the suggestion of using full names everywhere to be considered too
```
github.com/eris-ltd/commandline
github.com/eris-ltd/database
github.com/eris-ltd/chainmanager
github.com/eris-ltd/packagemanager
github.com/eris-ltd/keys
github.com/eris-ltd/compilers
```

for quay.io images 
```
quay.io/eris/packagemanager
quay.io/eris/chainmanager
quay.io/eris/database
quay.io/eris/keys
quay.io/eris/compilers
```

**Comment by pietv** [comment]
:+1: for renaming `cm` and `pm` to `github.com/eris-ltd/chainmanager` or `github.com/eris-ltd/packagemanager`

there's no point in renaming `cli` or `db` — the abbreviations are quite clear as they are now.

**Comment by compleatang** [comment]
moving to coding

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/coding #19](https://github.com/eris-ltd/coding/issues/19) via [**ZenHub**](https://www.zenhub.com/)
