### ISSUE TITLE
[Keys] Gen should have a `--save` flag and a `--pass` flag

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#794]
**Problem** -- some keys we don't want to be as unsafe as `eris keys gen` currently assumes. There isn't really a reason for us to default to `--no-pass` in the eris-keys gen level other than fast expedient, throwaway keys. But when generating keys that actually do want to be password protected we should expose that out to cli users via a flag. Also, for more important keys we don't want to assume they are only in the container and will have to do an `eris keys export` (copy and paste address). 

**Solutions** -- 

- [ ] add a `--pass` flag where the password is entered. Refactor `GenerateKey` to not be so opinionated about the `--no-pass` flag that is sent to eris-keys.  Note, currently eris-keys requires a password to be manually entered so the `--pass` flag should just be a boolFlag not a stringFlag.
- [x] add a `--save` flag that will run `ExportKeys` with the address returned from the `eris-keys gen` command.

**Comment by zramsay** [comment]
locked keys is gonna break a lot of assumptions cli has (will implement of course, but we'll definitely need a tut to explain wtf is going on)

**Comment by zramsay** [comment]
blocking on #697

**Comment by zramsay** [comment]
I've got [--save] working. [--pass] is a little tricky because of the interactive container. I'd also suggest we wait on the latter until a hardened key solution is available...otherwise it's just giving the illusion of security.

**Comment by zramsay** [comment]
also, using [--pass] (but not --save) furthers the problem of using execs rather than using the keys client like ecm does

**Comment by compleatang** [comment]
Great point re pass. I don't want to use keys client directly until it moves out of the same package as the server (which boats cli with all kinds of crypto...). Once that gets cleaned up tho I definitely agree that cli pm and cm should just use the go client library.

**Comment by zramsay** [comment]
++ yup those two things should definitely happen in sync ... that'll make the drop in integration easier too

**Comment by zramsay** [comment]
closed by #933

**Comment by zramsay** [comment]
gonna remove [eris keys pub] since it's not used (is a vestige of toadserver's needs)
