### ISSUE TITLE
better error handling when chain won't start

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#797]
**Problem** -- when a chain doesn't start users get an error message that looks like this:

```
eris chains new simplechain --dir $chain_dir_this 

Error moving keys: Docker: Cannot link to a non running container: /simplechain-07099eed-47a3-4668-a9d5-4e6e2af9ed3e AS /interactive-5588a485-1a7c-44df-a765-7dcc85328108/chain
```

That error is getting thrown during the phase of new where the keys are moved over to the keys server. The cause of the error is that the chain wasn't started for whatever reason (port conflicts, etc.). But for some reason the chain not starting error is either not getting thrown before reaching this point of the boot process, or isn't getting caught.

**Solution** -- figure out if there is an error we aren't catching and if so throw that error instead of the above error. 

Links to #468

**Comment by pietv** [comment]
Solution is to start the chain after preparation of `data` and `keys` container. If the chain fails to start the error will be known immediately. If the chain fails soon after start, that's maybe worthwhile to catch, but that means placing something like `Sleep(2)` in `defer` and then check again whether the chain is running. Imo that's dirty, but might be useful.

`defer` error checking is removed, they obscure the picture and not necessary.
