### ISSUE TITLE
[Chains] ChainName on `make` and `new` both map to `CHAIN_ID` but are not intended to be the same?

### ISSUE THREAD

**Issue by benjaminbollen** [eris-ltd/eris-cli#806]
on `eris chain make <NAME>` `NAME` is used as `CHAIN_ID` in `genesis.json` (and now also in `config.toml`)
but on `eris chain new <NAME>` this name is used as `CHAIN_ID` in the `ENV CHAIN_ID`, but this to me is confusing as I tend to name on `new` with respect to the validator, and also not the right behaviour?

Relates to the planned effort of separating `chain name` as a human_readable name, and `chain_id` as the hash of the `genesisDoc`

**Comment by zramsay** [comment]
closing in favour of #858
