### ISSUE TITLE
Error compiling contracts

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-cli#812]
`docker version`:
`eris version`:0.11.4
 `go version` (if applicable): go1.5.4
 `docker-machine version` (if applicable / !linux): linux
  operating system details (osx/windows/linux): linux/amd64
  what you expected to happen: contract should've deployed successfully
  what actually happened: "failed to send HTTP request Post    https://compilers.eris.industries:10114/compile: local error: internal error
Error compiling contracts
Post https://compilers.eris.industries:10114/compile: local error: internal error"

steps to reproduction: create a simplechain, create a simple contract, and deploy it

If issue is a feature request, tell us why this feature is useful.

**Comment by pietv** [comment]
Hi @somak12, thank you for reporting the issue! Indeed, we had an issue with a hosted compilers not being able to compile contracts for version 0.11.4. Please, try the deploy contracts sequence again — you shouldn't be seeing the error now. Thanks!
