### ISSUE TITLE
Unable to deploy contract - cannot connect to compilers - unable to generate an ABI file

### ISSUE THREAD

**Issue by yogaa** [eris-ltd/eris-cli#813]
Hi All,

 I am trying to run through the eris tutorial to set up a contract and after successfully executing all the prerequisite steps, i am unable to execute the below command 

$ eris pkgs do --chain simplechain --address $addr

Performing action. This can sometimes take a wee while
Executing Job                                 ←[1mdefaultAddr←[0;10m
Executing Job                                 ←[1msetStorageBase←[0;10m
Executing Job                                 ←[1mdeployStorageK←[0;10m
failed to send HTTP request Post https://compilers.eris.industries:10114/compile
: local error: internal error
Error compiling contracts
Post https://compilers.eris.industries:10114/compile: local error: internal error

Container interactive-949cd1cc-6139-43f2-91f2-dd81757d0027 exited with status 1

referring to the trouble shooting section given on the tutorials page we downloaded the compliers locally and re-run the  comamnd as 
"eris pkgs do --chain simplechain --address $addr --compiler 192.168.99.100:9091" and the command failed to execute 

P.S : the machine on which we are executing in on open network (without any restrictions)

- [ ] `docker version` - 1.11.2
- [ ] `eris version` -  0.11.4
- [ ] `go version` (if applicable) - 
- [ ] `docker-machine version` (if applicable / !linux)  - 
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

- [ ] operating system details (osx/windows/linux) -  windows 7
- [ ] what you expected to happen - to compile the eris pkgs command and generate an abi file
- [ ] what actually happened - generated an error
- [ ] steps to reproduction  - pls refer above

Below are the attached screen shots attached displaying the status of each command before executing the commands with **online complier** 
![eris - error 1](https://cloud.githubusercontent.com/assets/20512484/16909342/c6a6c210-4cef-11e6-8b46-24349fe5bad3.png)

and **compilers downloaded locally** 
![eris - error 3](https://cloud.githubusercontent.com/assets/20512484/16909581/55c5e10a-4cf1-11e6-9282-e4b6f18007b5.png)

attaching the command execution results with debug command

![debug 1](https://cloud.githubusercontent.com/assets/20512484/16911129/4e977480-4cfa-11e6-9eba-b2b036408ea6.png)
![debug 2](https://cloud.githubusercontent.com/assets/20512484/16911131/52386a36-4cfa-11e6-8b53-407d16f976cc.png)

Thanks & Regards,
Yogaa

**Comment by pietv** [comment]
Hi @yogaa, thank for the excellent bug report! I confirm we had an issue with compilers which for now should be fixed. Please, kindly try the deploying contracts sequence again, you shouldn't see the error anymore.

As a workaround for the future, there's a way to specify an alternative compiler address with a `--compiler` flag as in `eris pkgs do --chain CHAIN --address ADDR --compiler=https://compilers.eris.industries:10113` where `10113` is `10+<2 digits minor version>+<1 digit patch version>`. Thanks!

**Comment by yogaa** [comment]
Hi Peter,
 
 We are able compile now, also we where trying to download the compilers and execute the same commands but there was no luck doing that, please can you help us download a stable version of the compiler so that we can run the same code behind the corporate walls too.

thanks for the workaround and the compliment :)

Regards,
Yogaa

**Comment by yogaa** [comment]
Hi Peter,

 While we are trying to deploy the contract using the locally downloaded compilers using the given command _"eris pkgs do --chain simplechain --address $addr --compiler 192.168.99.101:9091"_ but we are unable to execute the same.

![local-complier-error1](https://cloud.githubusercontent.com/assets/20512484/16948619/4b9d4cb2-4dd3-11e6-8444-314e745926c2.png)

And the same command when we execute using the (online compilers) following command _"eris pkgs do --chain simplechain --address $addr"_ works perfectly fine.

![local-complier-error2](https://cloud.githubusercontent.com/assets/20512484/16948765/3166f6a8-4dd4-11e6-8c1e-e64b18f0f062.png)

 Attached is the screen shot, please can u look into the same and can help me run the commands using the downloaded compilers or if there is some another workaround like a tool / utility or something to share / download then it would be really helpful.

**Comment by pietv** [comment]
https://github.com/eris-ltd/eris-compilers/issues/70#issuecomment-233919165

**Comment by vjsub** [comment]
Hello,

Getting the same issue on 12.0. I see the compiler URL itself is changed for 12.0. Could you suggest if there is an alternate URL I should mention?

Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 setStorageBase
Executing Job                                 deployStorageK
failed to send HTTP request Post https://compilers.monax.io:10120: dial tcp: lookup compilers.monax.io on 10.0.2.3:53: no such host
Error compiling contracts: Compilers error:
Post https://compilers.monax.io:10120: dial tcp: lookup compilers.monax.io on 10.0.2.3:53: no such host
