### ISSUE TITLE
rc2 crashes on `eris pkgs do`

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#830]
- [x] `docker version`
```Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

- [x] `eris version` (RC2, installed from source, see install script below)
```
Eris CLI Version: 0.12.0 (a5229ff)
```
- [x] operating system details: Ubuntu 16.04.1 x64 (on digitalocean)
- [x] what you expected to happen: compile and deploy of my empty dummy contract
- [x] what actually happened: it crashed with the following output: https://gist.github.com/SCBuergel/c2db51009b53eb0a48ac9698775a7712
- [x] steps to reproduction
 - setup a clean Ubuntu 16.04.1 x64 machine on DO
 - installed eris 0.12-rc2 with the following script: https://gist.github.com/SCBuergel/4d6b0701edb5a80563ad05b0555b5024
 - created an empty contracts/dummyContract.sol:
```
contract dummyContract {
}
```
 - created a minimal epm.yaml:
```
jobs:

- name: deployDummyContract
  job:
    deploy:
      contract: contracts/dummyContract.sol
      wait: true
```
 - attempted running epm:
```
chain_dir=$HOME/.eris/chains/simplechain
addr=$(cat $chain_dir/addresses.csv | grep simplechain_full_000 | cut -d ',' -f 1)
eris pkgs do --chain simplechain --address $addr
```

~~If issue is a feature request, tell us why this feature is useful.
Because I really need Eris to do my job^^~~

**Comment by pietv** [comment]
@SCBuergel thanks very much for checking out the release! 👍 

How doesn't the dummy contract exactly fail for you? I've changed the the `contracts: contracts/dummyContract.sol` to `dummyContract.sol` in your `epm.yaml` file and it does work for me (otherwise it says: file not found). 

Did you rerun `eris init` after upgrading to rc2 (just in case)? Thank you!

**Comment by pietv** [comment]
Assuming your .sol file is called `dummyContract.sol`, of course.

**Comment by SCBuergel** [comment]
It fails during `eris pgks do...`, please check the gist for full details with debug on: https://gist.github.com/SCBuergel/c2db51009b53eb0a48ac9698775a7712

And yes, I didn't mention it but I put this contract into a folder called "contracts".

I did not upgrade to rc2, I ran it from binary, please check the other gist for the full install script (starting from a bare Ubuntu machine on DO): https://gist.github.com/SCBuergel/c2db51009b53eb0a48ac9698775a7712

**Comment by SCBuergel** [comment]
> Assuming your .sol file is called dummyContract.sol, of course.
Yes that is correct, as mentioned in the issue itself:
> created an empty contracts/dummyContract.sol:

**Comment by SCBuergel** [comment]
Btw: I ran into the very same issue on my local machine on some Ubuntu 15.10 but then reproduced it on a clean DO machine with the exact same crash behavior.

**Comment by pietv** [comment]
@SCBuergel thank you for the debug output: that's very useful. i'll take a look at it and reply you back.

**Comment by pietv** [comment]
@SCBuergel this issue should be fixed now in the #develop branch (needs installing from source). Please try when / if you're up for it. Thank you! 

```
git clone https://github.com/eris-ltd/eris-cli
cd eris-cli
git fetch origin develop
go get ./cmd/eris
go install ./cmd/eris
```

The issue was that on your setup Go couldn't find the `/etc/passwd` entry on your system to get info about your home directory, and Eris code missed the check for that.

**Comment by SCBuergel** [comment]
Thanks will check it out later.
> The issue was that on your setup Go couldn't find the /etc/passwd entry on your system to get info about your home directory, and Eris code missed the check for that.

I did not install from source but from the RC2 binary. Therefore I had no go installed at all.

**Comment by pietv** [comment]
Thank you! Yeah, I understood you used the RC2 branch binary. I mean, to try the fix you'd need to install from source. (I could build a binary for you if you'd like, though.)

**Comment by pietv** [comment]
> Therefore I had no go installed at all.
Go runtime accesses the `/etc/passwd` file on Unix (built from source or binary, doesn't matter).

**Comment by pietv** [comment]
May i close the issue?

**Comment by SCBuergel** [comment]
I dont have go running, looking forward to trying with the next binary release.
