### ISSUE TITLE
Native Docker for Mac Support

### ISSUE THREAD

**Issue by tbrooke** [eris-ltd/eris-cli#835]
Docker for Mac is out of beta and there appears to be discussion that the beta works #753 
and concerns about the installation #814 

But it still unsuccessfully checks for the default image on OSX El Capitan 

     Trying "default" Docker Machine: Could not evaluate the env vars for the eris docker-machine.
     Error:	 exit status 1 

It would be nice if it just worked

**Comment by pietv** [comment]
@tbrooke versions 0.11.4 and rc 0.12.0 should work on native Docker Mac without asking you for installing Docker Machine. Which version do you use? If it's > 0.11.3, please include output of the 'eris version -d'  and 'env|grep -i docker' commands (and if that's below or equal, please update). Thank you!

**Comment by tbrooke** [comment]
removed older Eris-cli and installed 0.11.4  - works fine
