### ISSUE TITLE
endless loop in `eris chains make`?

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#843]
After `eris init` I tried making a chain with `eris chains make --account-types=Root:2,Full:1 simplechain -d`. Some output seems to be running endlessly in a loop, `ctrl`+`c` does not stop it, see attached screenshot:

![screenshot](http://i.imgur.com/dqVU9gG.png "screenshot")

- [ ] `docker version`
```
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

- [ ] `eris version`
```
Eris CLI Version: 0.12.0-rc3
```
(Peter's binary build)

- [ ] `go version` (if applicable)
no, installed from source

- [ ] `docker-machine version` (if applicable / !linux)
```
docker-machine version 0.7.0, build a650a40
```
- [ ] operating system details (osx/windows/linux)
Ubuntu 16.04.1 x64 on DO

**Comment by zramsay** [comment]
can confirm this behaviour. just encountered it

**Comment by zramsay** [comment]
@SCBuergel you can downgrade the data image to rc2 in `~/.eris/eris.toml` and it'll work. That file should like:
```
IpfsHost = "http://0.0.0.0"
CompilersHost = "https://compilers.eris.industries"
CrashReport = "bugsnag"
Verbose = false
ERIS_REG_DEF = "quay.io"
ERIS_IMG_DATA = "eris/data:0.12.0-rc2"
ERIS_IMG_KEYS = "eris/keys:0.12.0-rc3"
ERIS_IMG_DB = "eris/erisdb:0.12.0-rc3"
ERIS_IMG_PM = "eris/epm:0.12.0-rc3"
ERIS_IMG_CM = "eris/eris-cm:0.12.0-rc3"
ERIS_IMG_IPFS = "eris/ipfs"
```

**Comment by pietv** [comment]
@SCBuergel may I close the issue (no endless loop with `ERIS_IMG_DATA = "eris/data:0.12.0-rc2"` in `eris.toml` after you rerun `eris init`)?

**Comment by pietv** [comment]
Closing. Please reopen if you encounter this again.
