### ISSUE TITLE
Move Dockerfiles for eris/data and eris/ipfs to cli's repository

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#846]
See relevant reasoning in common's issue.

**Comment by AFDudley** [comment]
Please QA https://github.com/eris-ltd/eris-cli/tree/common_67 (branched from develop)

**Comment by pietv** [comment]
Local tests pass (replaced `blob/master` with `blob/common_67`).

**Comment by pietv** [comment]
`tests/build_other_images.sh` LGTM, but can be properly tested in CI only.

**Comment by pietv** [comment]
Could be `docker build -f $repo/docker/x86/data/Dockerfile -t $testimage:latest .` instead of `cp`.

**Comment by pietv** [comment]
:+1: LGTM. (Might need to do rebase before merging.)

**Comment by compleatang** [comment]
closing since it was merged.
