### ISSUE TITLE
Cant pull docker images

### ISSUE THREAD

**Issue by infinius12345** [eris-ltd/eris-cli#847]
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

eris version
Eris CLI Version: 0.12.0

go version
go version go1.6 linux/amd64

- [ VBox -Ubuntu14.04 - Trusty Tahr]
- when using **quay.io/eris/compilers:0.12.0** i get the following error
docker pull quay.io/eris/compilers:0.12.0
0.12.0: Pulling from eris/compilers
759d6771041e: Retrying in 1 second 
8836b825667b: Downloading 
c2f5e51744e6: Downloading 
a3ed95caeb02: Waiting 
df0f22100b18: Waiting 
2d0ee169dcb4: Waiting 
9d8265e2b8cd: Waiting 
e99f61917111: Waiting 
91302a1f3173: Waiting 
86bb764ff08f: Waiting 
722f46acfcd4: Waiting 
4793b4db0f5a: Waiting 
21fb1451be13: Waiting 
033053632f95: Waiting 
d766b74f5e31: Waiting 
6d54273831be: Waiting 
550f0b5e04fa: Waiting 
e7913fc93a02: Waiting 
6a9cd6f4b057: Waiting 
6bdd3cc59b6c: Waiting 
e32e3e700e15: Waiting 
d26c4e48df21: Waiting 
85f1e6c39bb5: Waiting 
fe73d64c39a7: Waiting 
c38aa8e5887f: Waiting 
**x509: certificate signed by unknown authority**

-This only occurs when trying to pull from quay.io, I am able to pull every other image

Please help!

**Comment by pietv** [comment]
@infinius12345 thanks for reporting the issue! which command are you invoking when you see this error? `eris services start compilers` or `docker pull quay.io/eris/compilers:0.12.0`? if the former, does the latter work? 

Judging by the error message it looks like you have an issue with your docker VM? Are you using Docker Machine or native Docker? Try restarting those. 

If that's Docker Machine you're experiencing the issue with, please check that you have enough disk space on its root filesystem `docker-machine ssh MACHINE_NAME df -h`

**Comment by pietv** [comment]
If there's not enough disk space, you'd have to clean containers (`docker rm`), images (`docker rmi`), and volumes (`docker volume rm`).

**Comment by infinius12345** [comment]
its the same result for both the commands, i use virtual box VM's and native docker so i just made a new VM(So i am sure its neither the Memory or docker) and it gives me the same result whereas if i issue a command like docker pull infinius/idiservice it pulls the image successfully,

**Comment by pietv** [comment]
to my surprise I was able to (kind of) reproduce the situation on the Native Docker, but the second attempt it succeeded. I haven't been able to reproduce it on Docker Machine, but I use a DigitalOcean driver. 

The main reason you're experiencing the issue is the image size is > 1Gb. Question: do you have more or less than 4Gb of RAM on the computer (and no other memory hungry application is running)?

I will investigate this a little bit and will reply you back.

**Comment by infinius12345** [comment]
I am using a VM with 2gb dedicated RAM.. I have always been able to pull these files but for some reason its not working with any quay.io/eris files i always get **x509: certificate signed by unknown authority** when i try to pull

**Comment by zramsay** [comment]
@infinius12345 are you still encountering this problem?

**Comment by infinius12345** [comment]
@zramsay @pietv Apologies it has something to do with my firewall i should have closed this issue earlier thanks for your help

**Comment by compleatang** [comment]
@infinius12345 don't want to take too much of your time, but do you have any firewall tips that we can use to debug such instances more quickly and help users know where to look?
