### ISSUE TITLE
:10114/compile: local error: internal error

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#856]
I am running `eris pkgs do --chain simplechain --address $addr` and get the following error 
```
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 deployDummyContract
failed to send HTTP request Post https://compilers.eris.industries:10114/compile: local error: internal error
Error compiling contracts
Post https://compilers.eris.industries:10114/compile: local error: internal error

Container interactive-84c4e8d7-0363-4c62-9265-a2efd71f2a29 exited with status 1
```

Here the complete output for `-d`: https://gist.github.com/SCBuergel/c1318f33d642e8d1e626295a7d94ac68

This is my `epm.yaml`:
```
jobs:

- name: deployDummyContract
  job:
    deploy:
      contract: contracts/dummyContract.sol
      wait: true
```

I have a folder named `contracts`, containing a file `dummyContract.sol` with the following code:
```
contract dummyContract {
}
```

- [x] `docker version`
```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```
- [x] `eris version`
```
Eris CLI Version: 0.11.4
```
- [x] operating system details (osx/windows/linux) Ubuntu 16.04.1 x64

**Comment by SCBuergel** [comment]
This seems to be an issue with the `10114` compiler, I tried downgrading the compiler via `eris pkgs do --chain simplechain --address $addr -l https://compilers.eris.industries:10113` and all works fine as expected.

**Comment by hamster226** [comment]
2 hours before, i was using 10113. but now i got same massage : "local error : internal error".
can i find another compiler?

**Comment by somak12** [comment]
same with me. I was using 10113 , but now its giving internal error as well.

**Comment by zramsay** [comment]
The compilers should be back up at this time. Note that in rc3 we've introduced the `--local-compilers` flag for `eris pkgs do` which will pull the compilers image and start it as a service locally. The image is currently quite large but will soon be reduced. We'll be moving to local compilers by default in the near term (see #854).
