### ISSUE TITLE
Chain local node doesnt find genesis or key

### ISSUE THREAD

**Issue by infinius12345** [eris-ltd/eris-cli#866]
Linked to #862 after issuing all commmands in #858 and starting the local node i get the following error in the log 
No Key Given
No Genesis Given
No Genesis_CSV Given
No Chain Config Given
No Server Config Given
ecm version 0.12.0
&your new chain, kind marmot: advchain
running mintconfig 
(Running chain advchain (via ErisDB API)
jINFO[08-11|17:39:35] ErisDB Serve initializing.               module=eris/erisdb_server
jINFO[08-11|17:39:35] No server configuration, using default.  module=eris/erisdb_server
INFO[08-11|17:39:35] Writing to: /home/eris/.eris/chains/advchain/server_conf.toml module=eris/erisdb_server
Write and backup
xNOTE[08-11|17:39:35] Starting EventSwitch                     module=events impl=EventSwitch

where as doing ls on the directory gives me 
/.eris/chains$ **eris data exec advchain1 -- ls /home/eris/.eris/chains/advchain**
config.toml  genesis.json	  priv_validator.json.bak
data	     priv_validator.json  server_conf.toml

**Comment by compleatang** [comment]
Those first lines can be safely ignored. It is bad text, but means that they weren't given as env vars when the container booted.

Is advchain1 running?

**Comment by infinius12345** [comment]
Yes it says it is running, does that mean i can connect this node to another node through the same process stop , update config.toml and run again?

**Comment by compleatang** [comment]
yeah. you'd just update the seeds field in the config.toml and then perform the same (unfortunately too long) sequence.

**Comment by infinius12345** [comment]
Yes, but as long as it works its fine for now, and its unfortunate that i cant use docker-machine or it would have been simpler
