### ISSUE TITLE
[Tests] remove `eris init`'s and `eris clean`'s from tests_tooltests_jenkins

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#867]
**Problem** -- our unit tests can be more cleanly isolated. The test runner for those jobs should be as minimalistic as possible. Indeed, it should mostly be controlling `go tests` and that's it. 

**Solutions** -- a good start will be removing the eris inits and eris cleans from the file noted above. We'll need some deeper refactors as well.

**Comment by pietv** [comment]
A follow-up question: the test runner is the `test_tool.sh` script and the idea is to drop it altogether?

And what should be isolated from what? The `test_tool.sh` pulls some images before running the test suite (`go tests ./...`) and cleaning of leftover containers is never called. Each separate package should be initializing and cleaning after itself separately is the idea? (Sorry, don't have any insight what tests_tooltests_jenkins is).

**Comment by pietv** [comment]
Related: https://github.com/eris-ltd/eris-cli/issues/859

**Comment by compleatang** [comment]
Great question! Yes, the idea is this is a first step in the direction of #859. tests_tooltests_jenkins is a somewhat updated version of `test_tool`. I've worked to harmonize all of the test harnesses and significantly cleaned up `test_tool`, but for now we want to keep it as it will take a while to get jenkins running Windows and OSX jobs. That said, the tests_tooltests_jenkins will be the maintainers responsibility to maintain, so good for you to understand that file well to move in the direction of it basically just running `go tests` (for now; later we can do the full separation required for #859 ).

**Comment by pietv** [comment]
> tests_tooltests_jenkins is a somewhat updated version of test_tool [...] good for you to understand 

Gotha.

> to move in the direction of [...] just running `go tests`

Gotcha. Thank you for explaining this; it's much more clearere now. :+1:

**Comment by compleatang** [comment]
tests such as `eris init` `eris clean` and `eris upgrade` we may just have to accept lower go tests coverage and have better stack level tests... stack tests we run one at a time per machine so they can test the nuclear stuff. 

this also relates to #863 (in that ops should keep updated `quay.io/eris/data` and `quay.io/eris/test` available for the tests that need to turn on things and to store things).

**Comment by pietv** [comment]
:+1:

`eris init` can benefit from a mock pulling and `eris clean` from `perform.DockerBuild` to build fake images only to later cleaning them. `eris upgrade` is more tricky (but it's essentially `DockerBuild` use case — could mimic `eris clean` in this regard.) 

For this ticket, the playground will be essentially Jenkins (making sure Travis and Appveyor don't fail), gotcha.
