### ISSUE TITLE
[Chains] 'eris chains exec MYCHAIN --mintx permission set_base' never commit

### ISSUE THREAD

**Issue by Fukunaga42** [eris-ltd/eris-cli#868]
Please include in your bug report:

- [ 1.12.0] `docker version`
- [ 0.12.0] `eris version`
- [1.6 ] `go version` 
- [ 0.7.0] `docker-machine version`
- [ ubuntu 14.04] 

On this page:
https://docs.erisindustries.com/tutorials/advanced/chain-maintaining/
I have 3 validator node running on aws, and i run a root node on this aws instance, they are all synced. I have set up all the env var needed and seems ok about my config.
But when I try to run the last command on the 'Maintenance Task 1: Adding Actors' section:
> eris chains exec $chain_name -- mintx permission set_base $new_addr call true --addr $root_addr --sign-addr=keys:4767 --node-addr=chain:46657 --chainID $chain_name --wait --broadcast --debug

FIRST time I run the command:
`its tell me "Error invalid signature`
SECOND time i rn the command:
its seems ok but never commit on a block..

here you can see the full logs:
[logs.txt](https://github.com/eris-ltd/eris-cli/files/418027/logs.txt)

**Comment by zramsay** [comment]
thanks for the bug report @Fukunaga42 I'm working on replicating this issue an will update by the end of the week.

**Comment by compleatang** [comment]
@Fukunaga42 can you please verify that your chain is making blocks first. `invalid signatures` is usually because the chainID is not properly set so please also double check that and confirm for us as it will ease our ability to recreate.

**Comment by Fukunaga42** [comment]
Hi @compleatang if you click on log.txt you can see that the chain is making block.

**Comment by compleatang** [comment]
Great! Then it is definitely the chainID you gave to mintx. (BTW, this is much easier with PM). To check the chainID directly from the chain you can run `eris chains cat chainName status`. There is a field in the status report which is `"chain_id"` make sure that is `devChain`.

**Comment by Fukunaga42** [comment]
My chainID seems good
When I run `eris chains cat devchain status `

[
       	7,
       	{
       		"node_info": {
       			"pub_key": [
       				1,
       				"4E3DC2AA3D9DDCF30F78B1DC27E928B572BB6DD9DDB981EA8D69567E0DCA3594"
       			],
       			"moniker": "rootNode",
       			"chain_id": "devchain",
       			"host": "172.17.0.4",
       			"p2p_port": 46656,
       			"rpc_port": 46657,
       			"versions": {
       				"revision": "",
       				"tendermint": "0.5.2",
       				"p2p": "0.3.0",
       				"rpc": "0.4.0",
       				"wire": "0.5.0"
       			}
       		},
       		"genesis_hash": "C9D60A35D6986E585E9515EEBD0B3FB3B7A552B9",
       		"pub_key": [
       			1,
       			"F2F9441D0C3F3CEEACE63EAFF97E34B35981FB7D57C9BC0D70F1B220F6A574A6"
       		],
       		"latest_block_hash": "FADDCADEB57CCB6EAF87173BCE2293428F1B096E",
       		"latest_block_height": 317778,
       		"latest_block_time": 1471946020428999936
       	}
]

**Comment by Fukunaga42** [comment]
I retry:
`eris chains exec devchain -- mintx permission set_base 16AD92A29D7C78455BB920DB582DA227ECE8A97D call true --addr 2A40638DB572C823AAA46F3EA7AD2C85B16FC931 --sign-addr=keys:4767 --node-addr=chain:46657 --chainID devchain --wait --broadcast --debug `
And I run 
`eris chains logs devchain -f ` on another shell , you can see logs here
[logs.txt](https://github.com/eris-ltd/eris-cli/files/432134/logs.txt)

**Comment by compleatang** [comment]
Hmm. Those logs show no unusual activity; indeed, I don't see any transactions coming into the chain at all. 

Am assuming that on the `exec` call that you're getting the same or similar as previously pasted. 

Have you tried this with the PM using a paradigm like this: https://github.com/eris-ltd/eris-pm/blob/master/tests/fixtures/app03-basic_and_advanced_permission_txs_and_queries/epm.yaml

If the PM will work for you please do because we're in the midst of a massive refactor of the mintXXXX tooling.

**Comment by Fukunaga42** [comment]
OK I try with EPM and I have :
`Error broadcasting transaction: Trying to update permissions for unknown account A3CBA209E6C6451A30632377277D1D296EB41145
Error broadcasting transaction: Trying to update permissions for unknown account A3CBA209E6C6451A30632377277D1D296EB41145`

This message is right, this account is not on my blockchain actually cause I want to use this function to add this account on my blockchain , not only just to update an existing account!

So `mintx permission set_basemintx permission set_base` is it only for updating existing account on blockchain or is it usable for create new account on a blockchain ??

**Comment by zramsay** [comment]
updating the permissions on a blockchain. to create a new account, you have to `eris keys gen` and send tokens from an existing account to the new account.

**Comment by zramsay** [comment]
@Fukunaga42 hopefully you were able to work it out. Closing issue for now, but please re-open if you have additional problems. Note, however, that we are deprecating `mint-client` in favour of `eris-client` which be assimilated into `eris-db`
