### ISSUE TITLE
eris chains make fails

### ISSUE THREAD

**Issue by Name63** [eris-ltd/eris-cli#876]
Hello everyone,

Trying to make a new chain fails:

```bash
$ eris chains make --account-types=Root:2,Full:1 simplechain
Docker: {"message":"lstat /var/lib/docker/aufs/mnt/2c395c2be396988435b84c5b0efee2410b42c1d8bab19fe7fb8fbc3517e5c641/home/eris/.eris/chains/account-types: no such file or directory"}
```

Running below doesn't help:
```bash
eris clean --all --yes && eris init --yes
```

I have not installed any updates recently, just diced to run eris clean -a to start everything over

### docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

### eris version
Eris CLI Version: 0.11.4

### go version
Not installed

### docker-machine version` (if applicable / !linux)
docker-machine version 0.7.0, build a650a40

### operating system details (osx/windows/linux)
Ubuntu 16.04.1 LTS 4.4.0-34-generic x86_64

**Comment by pietv** [comment]
@Name63 Thanks for submitting the issue and for the great care describing it!

One follow-up question: you mentioned the Docker Machine version you're using. Do you actually use Docker Machine with Eris on Linux, or are you running Docker daemon natively?

I was able to reproduce the issue with Eris version 0.11.4 on Linux with Docker running using Docker Machine (but not with later Eris version nor with running Docker daemon natively).

We're investigating the issue right now and will get back to you with a fix (if applicable) and explanation.

As a workaround, would you be able to use the most recent binary distribution (version 0.12.0-rc3) which doesn't seem to have this error: [eris_0.12.0-rc3_linux_amd64](http://filebin.ca/2rzQOv5QdbQo/eris_0.12.0-rc3_linux_amd64)
```
$ mv eris_0.12.0-rc3_linux_amd64 eris
$ chmod +x eris
$ ./eris clean -y
$ ./eris init
$ ./eris chains make ...
```

Thanks.

**Comment by j-h-scheufen** [comment]
Hi @Name63,

can you make sure these two directories exist:
`~/.eris/chains/chain-types/`
`~/.eris/chains/account-types/`

Create them if necessary and try to re-run.
What I observed is that they are empty after `eris init`, but get populated with files upon the first `eris chains make` command, so if they are missing for whatever reason, this could cause an issue.
If this solves your problem, I would suggest we'll look into it as a bug that the directories were missing after `eris init`

**Comment by Name63** [comment]
@pietv 
> One follow-up question: you mentioned the Docker Machine version you're using. Do you actually use Docker Machine with Eris on Linux, or are you running Docker daemon natively?
I'm working on native engine, but tried to test this issue by running `eris make` with --machine flag against another docker machine.

@j-h-scheufen 
Checked, these directories exist and empty.

**Comment by zramsay** [comment]
related to #526 and potentially #865

**Comment by lixiaoyi1108** [comment]
Just met the same problem and check both account-type & account-types are empty. But I want to know how it could happen?

**Comment by pietv** [comment]
@Name63 please rerun the `eris init` command and try your experiment (`eris chains ...` command) again? That should be enough to fix the issue (in 0.11.4 and later versions). The problem was with one of the (improperly build) images `eris` runs. We're investigating this further. 

The image(s) in question are `quay.io/eris/data:*`. 

(To double check you're using the proper image: `docker images` command shows very recent `CREATED` timestamp (no later than a few hours) or `afc42e6de327` hash.)

**Comment by pietv** [comment]
@lixiaoyi1108 please follow the same recommendation above. Thanks.

**Comment by Name63** [comment]
@pietv  It works now, thanks.

**Comment by pietv** [comment]
@Name63 thank you for the update! cheers.

@lixiaoyi1108 please feel free to reopen the ticket if the issue persists for you. thanks!

**Comment by lixiaoyi1108** [comment]
run `eris init` doesn't work for me.

2016-08-19 14:01 GMT+08:00 Peter Vypov <notifications@github.com>:

**Comment by pietv** [comment]
Which error do you see? Are `chain-types` and `account-types` are empty or this is something else?
