### ISSUE TITLE
remove `eris chains rename`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#882]
**Problem:** it's cognitive overhead for a command that's likely not being used (who's really renaming their chains?)...and once the dump => restore sequence is sorted, that can be the way to rename a chain anyways. As well, the tests are needlessly complex & fragile.

**Solution:** command be gone.

**Comment by pietv** [comment]
:+1: agree.

**Comment by zramsay** [comment]
closed by #884
