### ISSUE TITLE
[Pkgs] remove --services flag from pkgs do

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#885]
**Problem** -- there is some technical debt in how we deal with services being ran in pkgs do. Currently we give it a SliceVarP which is marshalled into a services slice. These services are started before the pkgs do runs. However, this is technical debt from a prior architecture which no longer applies. eris pkgs do should only run against eris chains and not services.

**Solution** -- all the code around starting services (other than compilers and keys) should be removed. The code around determining whether a "chain" is a "service" or not should also be removed. Chains are chains, services are "other things".  Tests may need to be refactored, but I'm pretty sure that part of the code is not very cleanly tested.

**Comment by zramsay** [comment]
removed in #1083
