### ISSUE TITLE
[Chains] start needs to know how to read the chain's config.toml

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#889]
**Problem** -- we have too many config files. On the chains team's side they have effectively compiled their config file into a single file which let's erisdb know how to start. While it would, in theory, be great to remove chain definition files completely (including the dreaded `default` in order to reduce our indirection and cognitive overhead for new users), doing so would create the massive problem that cli would not have a record of which docker image version it should utilize to operate the chain. Normally this would be fine. Except when a user upgrades cli and init's (which would write a new version of the erisdb image into eris.toml).

**Solution** -- chains team currently writes sufficient version information into the config.toml for cli to be able to start the proper docker image. It should use it.

**Comment by zramsay** [comment]
blocking on https://github.com/eris-ltd/eris-cm/pull/31

**Comment by zramsay** [comment]
- unblocked but dealt with in #651
- the problem of tracking the image will be dealt with in #336 and #908
