### ISSUE TITLE
[Core] OSX Beta Docker Connection Host Issue

### ISSUE THREAD

**Issue by akshithg** [eris-ltd/eris-cli#895]
- [x] `docker version`
1.12.0
- [x] `eris version`
0.12.0
- [x] `go version`
go1.7 darwin/amd64
- [x] `docker-machine version`
0.8.0, build b85aac1
- [x] operating system details
osx
- [x] what you expected to happen
```
eris chains new dual_integrator --dir dual_integrator/dual_integrator_full_000
```
Suposed to run successfully.
- [x] what actually happened
**Fails**
```
Sending Call to eris-keys server         path=http://keys:4767
                                         type=ed25519,ripemd160
                                     endpoint=gen
Could not connect to eris-keys server. Start it with `eris services start keys`. Error: Post http://keys:4767/gen: dial tcp 218.93.250.18:4767: i/o timeout
```
The key service is up. Verified with `eris services ls`
- [x] steps to reproduction

You should be able to reproduce the error with the above configuration

More details:
`eris services inspect keys NetworkSettings.IPAddress` returns  `172.17.0.2`
It should be returning `218.93.250.18`

Problem with Docker?

**Comment by pietv** [comment]
@akshithg thank you for reporting the issue!

> Problem with Docker

likely an issue with Docker daemon running natively. One follow-up question. Do you run the `eris chains new` command while running Docker on Docker daemon natively or on a Docker Machine?

> `eris services inspect keys NetworkSettings.IPAddress` returns `172.17.0.2`
It should be returning 218.93.250.18

Looks about right. Why do you think it should be returning your external IP address? Either it is running on a Docker Machine or not, the Docker daemon is running in a VM, it will be returning the VM IP address.

**Comment by pietv** [comment]
Will try to reproduce the issue and get back to you with either a fix/workaround or more questions.

**Comment by akshithg** [comment]
Thanks @pietv .
I run Docker on Docker daemon natively

Regarding the IP, I was discussing the same issue with @compleatang over slack. While trying to figure he asked me to:
> run `eris services inspect keys NetworkSettings.IPAddress` and make sure that matches the 218...

on running it I got `172.17.0.2` Thought reporting it was wise.

**Comment by akshithg** [comment]
@compleatang @pietv is there a temporary workaround for this issue?
One way would be to switch from docker daemon to docker machine. Any other suggestions?

**Comment by compleatang** [comment]
At this time, moving to docker machine is much more reliable in our view. Peter is working on the issue but it won't make it into 0.12.0 which we're in the process of finalizing for release next week.

**Comment by dazzaji** [comment]
Just reading this thread for first time now... I suppose it's time to dive into The Machine: devopscube.com/docker-machine-tutorial-getting-started-guide/

**Comment by zramsay** [comment]
closing in favour of #951
