### ISSUE TITLE
[Core] expose eris init timeout as a globalConfigVariable in eris.toml

### ISSUE THREAD

**Issue by AdamScislowicz** [eris-ltd/eris-cli#896]
Please include in your bug report:

- docker 1.12.1-beta24 build: 11508
- eris-cli version: a5229ffaf8e78e526aa6246ba79ab1aa620c5cd4
- go version: 1.6.2 linux/amd64
- docker:ubuntu 16.04 on OSX
- eris init to complete
- eris init times out
- run 'eris init'

issue is in initialize/writers.go, here the timeout is hardcoded to 5 * time.Minute ...

**Comment by compleatang** [comment]
Thanks for the report Adam! We added that ticker when docker was having issues during their previous release cycle, but generally we think it's a good idea to keep a timeout override throughout the init process as there are a number of non deterministic bad things that can happen. 

There are a couple of approaches we could take to address lower capacity/bandwidth scenarios. In the immediate term if you're OK building from source then just patch it manually. In the short term we can easily expose that as an eris.toml setting. Would that work? 

So you know we are also working diligently to reduce our Docker image sizes, which are due for a significant upgrade when 0.12.0 is released.

**Comment by AdamScislowicz** [comment]
Hi. Indeed I was able to work around it with a local change to the static timeout value and a rebuild. I will revisit this around the 0.12.0 releases. Thanks for the quick response.
