### ISSUE TITLE
[Chains] cm code should be merged into this repository

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#899]
**Problem** -- cm is simply manipulating some files and making API calls. There is no reason we're running it in a docker container. 

**Solution** -- cm should run as an imported library. cli should: 
- import cm as a library
- populate a cm do struct
- call MakeChain with cm's do struct -> https://github.com/eris-ltd/eris-cm/blob/master/maker/maker.go#L21

This will be a much simpler solution than our current paradigm.

**Comment by zramsay** [comment]
related to #900

**Comment by zramsay** [comment]
closing since it's been on `unstable-develop` for awhile now and the tests generally pass with `./tests/test_chains_make.sh`
