### ISSUE TITLE
[Pkgs] pm code should be merged into this repository

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#900]
**Problem** -- pm is slow as hell. And testing it properly is a nightmare in the current paradigm is a nightmare.

**Solution** -- as with cm, pm should be:
- imported as a library
- have its do struct populated -> https://github.com/eris-ltd/eris-pm/blob/master/definitions/do.go
- call `RunPackage` with the appropriate do struct.

**Comment by zramsay** [comment]
closing since it's been on `unstable-develop` for awhile now and the tests generally pass with `./tests/test_epm.sh`
