### ISSUE TITLE
chains graduate test

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#92]

**Comment by compleatang** [comment]
zach, see if you can take a crack at this one.

**Comment by zramsay** [comment]
I have a ~ idea of what should happen here. My hunch is that `test` should stage the chain to make sure it'll be able to graduate w/o problem & thus avoid going through the motions of graduating it. An analogy from git might be checking mergeability before doing starting a merge. Thing is, I'm not sure what conditions need to be met for a chain to be considered graduate-able.

**Comment by zramsay** [comment]
not sure what all the checks should be ... there could be plenty given the contents of /definitions/

**Comment by compleatang** [comment]
closed by 9e972ba
