### ISSUE TITLE
Eris init does not start properly on new docker installation

### ISSUE THREAD

**Issue by rhom2016** [eris-ltd/eris-cli#924]
Please include in your bug report:

- [ 1.12.0] `docker version`
- [ 0.11.4] `eris version`
- [N/A] `go version` (if applicable)
- [ 0.8.0] `docker-machine version` (if applicable / !linux)
- [ osx 10.11.6] operating system details (osx/windows/linux)
- [ eris init to initiate a new docker machine and then pulling images from quay.io] what you expected to happen
- [ initial eris init errors out after creating docker machine, but second eris init works fine

```
bash-3.2$ eris init
Trying "default" Docker Machine: Could not evaluate the env vars for the eris docker-machine.
Error:	exit status 1

The marmots could not find a Docker Machine VM they could connect to
Our marmots recommend that you have a VM dedicated to eris dev-ing
Would you like the marmots to create a machine for you? (y/n): y
The marmots will create an Eris machine
Creating the Eris Docker Machine
This will take some time, please feel free to go feed your marmot
There was an error starting the newly created docker-machine.
Error:	exit status 1

bash-3.2$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
eris   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.1   
bash-3.2$ eris init
Eris root directory doesn't exist. The marmots will initialize it for you

WARNING: Approximately 1 gigabyte of Docker images are about to be pulled
onto your host machine. Please ensure that you have sufficient bandwidth to
handle the download. For a remote Docker server this should only take a few
minutes but can sometimes take 10 or more. These times can double or triple
on local host machines. If you already have the images, they'll be updated.

Skip confirmation with      ERIS_PULL_APPROVE=true

Do you wish to continue? (y/n): y

Pulling default Docker images from quay.io
Pulling image 1 out of 7                image=quay.io/eris/base
```
late] what actually happened
- [ ] steps to reproduction

If issue is a feature request, tell us why this feature is useful.

**Comment by pietv** [comment]
@rhom2016 Thank you for reporting the issue! The fact that the Docker Machine has been created and the error saying it didn't is definitely an issue, I will be reproducing it and reply you back soon.

In the meantime, I advise you setting the environment explicitly pointing to your Docker Machine in your `~/.bashrc` or on the command line to prevent the "environment" related message from appearing:

```
$ eval $(docker-machine env eris)
```
The Docker Machine related error messages have been ironed out in the #develop branch version right now if you'd want to try that. It is becoming a new release shortly. Thanks.

**Comment by zramsay** [comment]
@rhom2016 hopefully you were able to get things working. Am closing issue for now, please re-open if you continue running into problems. This [documentation on setting up docker-machine for eris](https://docs.erisindustries.com/tutorials//tool-specific/docker_machine/) should also help.
