### ISSUE TITLE
we need to remove docker volume dirs when we remove containers

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#93]

**Comment by zramsay** [comment]
actually that might not be as big a deal as making sure we remove intermediate image layers when building images

**Comment by zramsay** [comment]
`eris data rm --all` would be nice too, to get a fresh slate w/o file bloat.

**Comment by compleatang** [comment]
This is gonna be a bit dangerous in the efficiency sense (like having to waste days re-downloading a chain). I'm not adverse to `eris data rm --all` but, let's just add a confirm step.

**Comment by zramsay** [comment]
The use case I think is while learning the tool, a ton of files/images bloated and crashed my remote box while playing around.  Probably wouldn't be used much by someone who already knows what they're doing.

**Comment by compleatang** [comment]
cool. makes sense.

**Comment by zramsay** [comment]
I no longer consider my last comment relevant (it's really just for noobs). Could just have a helper that says "if you've been starting a lot of services (& have bloat), ax your docker containers with `docker rm -v -f $(docker ps -a -q)`, or say that somewhere in the documentation
