### ISSUE TITLE
[Services] `eris services start ... --attach`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#934]
**Problem** -- by default eris services are dropped to the background and either fail or are turned off. However, the same services likely expose setup sequences or other short running processes which users want to see the output too as in real time and follow the container through its process.

**Solution** -- `--attach` flag should not drop the service into the background, but rather attach to the standard output of the service and follow (in docker's terminology). This would probably require a flag partner -> `--cmd` which would usually be utilized when the attach flag is given. This should not overwrite the entrypoint, only the command. If folks properly assemble their dockerfiles this will be fine. On bad dockerfiles it may be weird but I think it helps to curate the UX.

**Comment by zramsay** [comment]
as with #935, i'm not convinced this feature is useful enough, especially given our momentum decoupling from docker (to a certain extent). recommend closing.

**Comment by compleatang** [comment]
++
