### ISSUE TITLE
[Services] make should be smarter

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#935]
**Problem** -- services make isn't very smart. It's fine for wrapping up a docker image into a service. Indeed, this is a few nice neat lines of code:

```
docker build -t genesisservice .
eris services make genesisservice genesisservice
eris services start genesisservice
```

But the problem comes if I need to set some more complicated defaults at the service definition level that I don't necessarily want at the Dockerfile level. To accomplish this would require that a particular application distribute a `genesisservice.toml` file with their application, then their `make` script or whatever would have to move that into the services directory. Also, we can lose that docker build. Instead these potentially four lines of code become two.

**Solution** -- adopt a convention that IFF in the current directory (perhaps with a flag) there exists a Dockerfile and/or a nameofservice.toml (perhaps with a flag) that eris services make will build the dockerfile in into a docker image named the same as the service name (without namespacing) and will read/write the namesofservice.toml from the pwd into .eris directory. If there is not a Dockerfile in the pwd or in the directory given, then the current make process should apply.

**Comment by zramsay** [comment]
do we want to be adding more docker wrapping? i'm not convinced this feature is desireable enough to warrant additional code. recommend closing

**Comment by compleatang** [comment]
++
