### ISSUE TITLE
[Chains] Investigate scenarios when `chains make` may delete Eris home directory

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#936]
- Check `eris chains make` container imports and exports where directory removal is involved.

**Comment by zramsay** [comment]
i suspect whatever caused this behaviour will be gone after #1072 & AFAICT it has not been replicated

**Comment by pietv** [comment]
I think this can be closed now; the behaviour has fixed by one of the `eris.toml` file generation fixes.
