### ISSUE TITLE
remove services exec and chains exec as executable commands

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-cli#94]

**Comment by compleatang** [comment]
i'm not sure we actually gain much with services exec and chains exec. Particularly for chains exec where we basically require data_containers then it would probably be better to reduce the redundancy of the code by taking chains exec out. Services exec would be good though if users don't have data containers turned on.

**Comment by ebuchman** [comment]
Agreed. imo we only really need exec on the data. if you're not using a data container you can go *@$# yourself

**Comment by compleatang** [comment]
`gofmt` yourself indeed. it wasn't one of my better ideas....

**Comment by compleatang** [comment]
changing the title to reflect what we really want to happen here. also, don't forget to remove the tests from chains_test.go and services_test.go
