### ISSUE TITLE
[Core] eris clean (without flags) should not remove chains dir

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#952]
**Problem** - -  users need their chain definition files. We encourage users to liberally use eris clean. However eris clean removes chains dir. 

**Solution** - - only remove chains dirs on - - all or - - dir. 

I feel pretty strongly about this issue unless there is a crystal clear argument for current state of develop branch we should change it.

**Comment by compleatang** [comment]
`0.12.0` cannot ship without this change. This is **very dangerous** for folks that need to keep their chain information around.

**Comment by zramsay** [comment]
closed by #973
