### ISSUE TITLE
Install Eris blockchain tools on IoT error 

### ISSUE THREAD

**Issue by f3r10** [eris-ltd/eris-cli#961]
Hello, I tried to install eris-cli at raspberry pi but "https://eris-iot-repo.s3.amazonaws.com/eris-deb DIST experimental" return a 403 http code response, there are any solution?

Thanks in advance

**Comment by zramsay** [comment]
Hi @f3r10, the `DIST` in this case should be replace with your distribution, likely `debian` or `raspbian` (ping @shuangjj for which are supported). [This script](https://github.com/eris-ltd/hello-eris/blob/master/cloud/arm/setup/setup.sh) should also work as a source installation.

**Comment by f3r10** [comment]
Thanks @zramsay now works perfect
