### ISSUE TITLE
Solve `ImportData` endless loop

### ISSUE THREAD

**Issue by pietv** [eris-ltd/eris-cli#962]
`data.ImportData()` runs in an endless loop when the container directory `do.Destination` cannot be created.

**Comment by zramsay** [comment]
closed by #1042 ?

**Comment by pietv** [comment]
That one was about missing `do.Source`, this one about `do.Destination`. I run a check, but probably needs a separate PR (or not).

**Comment by zramsay** [comment]
replaced by #1115
