### ISSUE TITLE
[Pkgs] compilers flag should respect the image defaults set in eris.toml

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#972]
**Problem** -- we're consolidating the monax built images to be opinionated and pulled from .eris/eris.toml.  We even have a compilers image space currently in the eris.toml. However current develop is not respecting this image but rather is using `latest` which is what the compilers service definition is utilizing.

**Solution** -- we need to either remove the compilers service definition file or we need to remove the compilers image from the eris.toml.

**Comment by zramsay** [comment]
I'm in favour of removing the service definition file - it adds complexity & we can assume defaults that flags can overide (preserving flexibility for advanced users)

**Comment by compleatang** [comment]
Cool. Let's get this before 0.12.0 official then. That will match with all the other serv def changes we're making.

**Comment by pietv** [comment]
I suggest this be synchronized also with `keys` and `ipfs` images. There are entries for both keys and IPFS in `eris.toml` just as service definition files. Removing service definitions for all of them will reduce flexibility in setting ports, for example, and this crutch `exec_host = "ERIS_IPFS_HOST"` has to be solved for both as well.

It should be easier to teach `LoadServiceDefinition` to read `eris.toml` and remove `image` field for those definitions.

**Comment by zramsay** [comment]
++ ^ great idea

**Comment by compleatang** [comment]
closed by #974
