### ISSUE TITLE
[Chains] More concise and clear way to know `my chain is on and making blocks`

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#984]
**Problem** -- currently users have to check the logs or the status and read the block height to know that their chain is on and is making blocks. We can and should do much better.

**Solution** -- add a `--quiet` flag to `eris chains status` that will simply return an error code that can be parsed by shelled out calling (in js) or directly (in bash) with `if [ "$?" -ne 0 ] then; ...`

**Comment by benjaminbollen** [comment]
Perhaps we should promise that status only returns a non-error if the healtz is fine - ;) @zramsay

**Comment by zramsay** [comment]
superceeded by #1011
