### ISSUE TITLE
[Util] Something keeps writing the `default` dir in my chains directory

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#985]
(there's nothing getting written inside of it though)

**Comment by zramsay** [comment]
ah, forgot to update `/common` to not drop that. also, should we get rid of `~/.eris/services/global` ? https://github.com/eris-ltd/common/blob/master/go/common/dirs_and_files.go#L51

**Comment by zramsay** [comment]
closed by #987
