### ISSUE TITLE
'eris chains start --init-dir' not working with paths outside ~/.eris

### ISSUE THREAD

**Issue by rguikers** [eris-ltd/eris-cli#991]
Please include in your bug report:
- [ ] `docker version`
- [ ] `eris version`
  0.12RC3
- [ ] `go version` (if applicable)
- [ ] `docker-machine version` (if applicable / !linux)
- [ ] operating system details (osx/windows/linux)
- [ ] what you expected to happen

assuming a local directory '/chain/test' with chain configuration. Start a new chain with 
`eris chains start test --init-dir /chains/test`
Would expect it to start the chain. First copy the chain dir to ~/.eris/chains
- [ ] what actually happened

The chain is not started. error is :

```
The chain directory provided does not exist, re-run with an existing directory
```

Seems that the chain is not copied to the ~/.eris/chains directory.
When manually copying the chain it works as expected (at least when the chain name is identical to the directory name)
- [ ] steps to reproduction
  see above

**Comment by zramsay** [comment]
hmm. good issue @rguikers. This is part bug and part feature. The tool very much assumes the path given is somewhere in ~/.eris/chains/chainName (since that's where `chains make` outputs files to). A fix will come with #964.

**Comment by rguikers** [comment]
Thanks Zach, when using the chain after creating it with 'eris chains make' this sounds logical. In my development environment i'm using a specific genesis.json with predefined keys for unit testing. In that case it would help to keep the chain close to the development code.

**Comment by pietv** [comment]
@rguikers the fix for this issue is implemented in the current #develop branch. Please feel free to test it when you can.

```
$ eris chains start --init-dir <arbirtrary path> <chain name>
```

**Comment by rguikers** [comment]
Thanks Peter
