### ISSUE TITLE
[Compilers] Better handle pragma warnings

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#997]
@VoR0220 commented on [Mon Oct 10 2016](https://github.com/eris-ltd/eris-compilers/issues/97)

Problem: Pragma warnings gives us an error that's essentially indecipherable. Need to better handle this.

Solution: This is going to be tricky because it's not in a neat JSON format. Might be worth the time to actually include the error in the combined-json output per a Solidity PR. Will have to talk it over and gauge what exactly we should do.

**Comment by zramsay** [comment]
is this also blocking on updates to Solidity?

**Comment by VoR0220** [comment]
This is the reason for the blocking. With that said i think I've come up with a temporary hack.

**Comment by VoR0220** [comment]
closing as completed in the above PRs. Better solution to follow with #1166 .
